#!/usr/bin/env node
// `bot/export-issues.mjs`: MIG-21's historic export.  `node bot/tests/export-issues.test.mjs`
//
// Two things are being asserted here and they are not the same thing.
//
// **That the grammar matches what this registry actually posted.** Not a
// grammar somebody typed into a test beside the one they typed into the parser
// — the first block below RENDERS the four decisions with `bot/ingest.mjs` and
// `bot/lib/policy/comment.mjs`, the modules that wrote every historic comment,
// and reads them back. A heading changed in either renderer breaks this file,
// which is the only way an export of a closed archive can be kept honest:
// after ROLL-42 switches Issues off there is no corpus left to re-run against,
// so the coupling has to be watched while the corpus still exists.
//
// **That nothing a stranger typed can cross.** The fixture thread carries
// logins, an email, a paragraph of free text and a comment that imitates the
// bot's marker byte for byte. The assertions are over the SERIALISED output —
// every planted needle is searched for in the JSON, rather than checked member
// by member, because a member-by-member check only ever covers the members
// somebody thought of.
//
// Nothing here touches the network.

import assert from "node:assert/strict";

import { renderComment } from "../ingest.mjs";
import { renderPolicySection } from "../lib/policy/comment.mjs";
import {
  BOT_LOGINS,
  composeRecords,
  exportFacts,
  issueScope,
  keyCollisions,
  readDecision,
  refuseUncomposable,
  resolveWriter,
} from "../export-issues.mjs";

let failures = 0;
let passed = 0;
async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok    ${name}`);
  } catch (e) {
    failures++;
    console.error(`  FAIL  ${name}\n        ${String(e.message).split("\n").join("\n        ")}`);
  }
}

const BOT = { login: BOT_LOGINS[0], type: "Bot" };

/**
 * A whole bot comment, rendered by the two modules that render the real ones.
 *
 * `bot/decide.mjs:143` joins the halves with a single newline; anything else
 * here would be testing a document this registry never posts.
 */
function botComment({ repo, tag, id, version, outcome, errors = [], reviews = [], approvedBy = null }) {
  const items = [
    ...errors.map((code) => ({ level: "error", code, where: "release", message: "the check that failed" })),
    ...reviews.map((code) => ({ level: "review", code, where: "version", message: "a decision for a person" })),
    { level: "pass", code: "E_DIGEST_MISMATCH", where: "asset", message: "sha256 abc…, 100 bytes, noarch" },
  ];
  const f = { items, errors: errors.map((code) => ({ code })), reviews: reviews.map((code) => ({ code })) };
  const derived = { plugin: { id }, version: { version } };
  const checks = renderComment(f, derived, { repo, tag });
  const decision = {
    outcome,
    repo,
    tag,
    fingerprint: "be6bc6b4f4139c5d",
    artifact_digests: ["sha256:abc"],
    publish_after: "2026-08-20T07:19:05Z",
    sla_deadline: "2026-09-15T10:37:55Z",
    queue_entry: { delay_hours: 24 },
    reasons: reviews.map((code) => ({ level: "review", code, message: "a decision for a person" })),
    // The approver, whom `renderPolicySection` prints as `**@login**` and whom
    // PRIV-10 says this export must turn into `system`. Planted so the needle
    // scan below has something to find if anybody ever scrapes it back out.
    approved_by: approvedBy,
    approved_at: approvedBy ? "2026-09-12T16:56:15Z" : null,
  };
  return `${checks}\n${renderPolicySection(decision, derived)}`;
}

// ── the grammar, generated by the renderers it reads ────────────────────────

await test("the four publication verdicts, rendered by the modules that render the real ones", () => {
  const base = { repo: "owner/name", tag: "v0.1.0", id: "dice-roller", version: "0.1.2" };
  const read = (outcome, extra = {}) =>
    readDecision({ ...BOT, date: "2026-08-20T07:19:05Z", body: botComment({ ...base, outcome, ...extra }) });

  const refused = read("refuse", { errors: ["E_OWNERSHIP_UNPROVEN"] });
  assert.equal(refused.fact?.state, "refused", "`**Not published.**` is a refusal");
  assert.deepEqual(refused.fact.reasons, ["E_OWNERSHIP_UNPROVEN"], "and its codes come from the checks' table");

  assert.equal(read("publish").fact?.state, "approved", "`**Published.**` is an approval");
  assert.equal(read("delay").fact?.state, "approved",
    "and so is `**Publishing itself at …**` — the policy said yes; the queue entry is what makes it happen");

  const held = read("review", { reviews: ["R_FIRST_LISTING"] });
  assert.equal(held.fact, undefined, "a hold is not a decision");
  assert.equal(held.drop, "held", "and it is counted under its own name rather than as a parse failure");
});

await test("the repository and the tag come out of the marker, which the run composed", () => {
  const body = botComment({ repo: "KNICE-TECH/astra-chess", tag: "v0.1.17", id: "astra-chess", version: "0.1.17", outcome: "publish" });
  const { fact } = readDecision({ ...BOT, date: "2026-09-02T08:11:20Z", body });
  assert.equal(fact.repository, "KNICE-TECH/astra-chess");
  assert.equal(fact.tag, "v0.1.17");
  assert.equal(fact.plugin_id, "astra-chess");
  assert.equal(fact.version, "0.1.17");
  assert.equal(fact.date, "2026-09-02T08:11:20Z");
});

await test("a refusal names no plugin and no version, because the run never derived one", () => {
  // Rendered with an `id`/`version` the ingest half will not print on a
  // blocked report: the refusal's own headline carries neither, and inventing
  // them from the issue form is the thing the approval binding exists to stop.
  const body = botComment({ repo: "owner/name", tag: "v9.9.9", id: "ghost", version: "9.9.9", outcome: "refuse", errors: ["E_INPUT_TAG"] });
  const { fact } = readDecision({ ...BOT, date: "2026-08-12T00:20:18Z", body });
  assert.equal(fact.state, "refused");
  assert.equal(fact.plugin_id, null, "DEC-7 lets both be absent, and absent is the honest record");
  assert.equal(fact.version, null);
});

await test("a code bot/lib/codes.mjs does not declare is dropped and counted", () => {
  const body = botComment({ repo: "owner/name", tag: "v1", id: "x", version: "1.0.0", outcome: "refuse", errors: ["E_INPUT_REPO"] })
    .replace("| ❌ | `E_INPUT_REPO` |", "| ❌ | `E_RETIRED_IN_2025` |\n| ❌ | `E_INPUT_REPO` |");
  const r = readDecision({ ...BOT, date: "2026-08-12T00:20:18Z", body });
  assert.deepEqual(r.fact.reasons, ["E_INPUT_REPO"], "the declared code survives");
  assert.deepEqual(r.dropped, ["unknown_code"], "and the undeclared one is named, not carried as an opaque string");
});

// ── the stranger's bytes ────────────────────────────────────────────────────

const NEEDLES = [
  "Belnash3",
  "teletemagame-dev",
  "astra-maintainer-7",
  "author@example.com",
  "please list this, it is my first plugin and I worked on it for months",
  "I am rejecting this because the licence looks copied",
];

/** A thread shaped like the real ones: a form, humans, and the bot. */
function fixtureCorpus() {
  const issues = [
    {
      number: 1,
      title: "[listing] Belnash3/image-gen",
      labels: [{ name: "listing" }, { name: "needs-triage" }],
      user: { login: "Belnash3", type: "User" },
      created_at: "2026-09-09T18:00:00Z",
      body: "### Source repository\n\nBelnash3/image-gen\n\n### Release tag\n\nv0.1.0\n\n### What does it do?\n\n"
        + "please list this, it is my first plugin and I worked on it for months. reach me at author@example.com",
    },
    {
      number: 2,
      title: "[release] teletemagame-dev/minecraft-for-astra v0.3.1",
      labels: [],
      user: { login: "teletemagame-dev", type: "User" },
      created_at: "2026-08-20T17:00:00Z",
      body: "/release teletemagame-dev/minecraft-for-astra v0.3.1",
    },
    {
      number: 3,
      title: "[notice] doom 0.1.3 publishes itself at 2026-08-19T21:00:26Z",
      labels: [],
      user: BOT,
      created_at: "2026-08-19T21:00:26Z",
      body: "`mihailinl/AstraPlugins@doom-v0.1.3` reached the registry without a submission issue.\n\n"
        + botComment({ repo: "mihailinl/AstraPlugins", tag: "doom-v0.1.3", id: "doom", version: "0.1.3", outcome: "delay" }),
    },
    {
      number: 4,
      title: "Plugin report: telegram-client 0.2.0 (broken)",
      labels: [],
      user: { login: "ilysharealcat", type: "User" },
      created_at: "2026-09-01T00:00:00Z",
      body: "it crashes and the author never answers. my email is author@example.com",
    },
    { number: 5, title: "[listing] someone/thing", labels: [], user: { login: "someone", type: "User" }, created_at: "2026-09-01T00:00:00Z", body: "unlabelled, the way #46 and #67 arrived", pull_request: undefined },
    { number: 6, number_is_pr: true, title: "[listing] not a real one", labels: [{ name: "listing" }], user: BOT, created_at: "2026-09-01T00:00:00Z", body: "x", pull_request: { url: "…" } },
  ];
  const comments = [
    {
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: { login: "Belnash3", type: "User" },
      created_at: "2026-09-09T18:00:30Z",
      body: "/recheck",
    },
    {
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: BOT,
      created_at: "2026-09-09T18:01:35Z",
      body: botComment({ repo: "Belnash3/image-gen", tag: "v0.1.0", id: "image-gen", version: "0.1.0", outcome: "refuse", errors: ["E_OWNERSHIP_UNPROVEN"] }),
    },
    {
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: BOT,
      created_at: "2026-09-12T16:57:54Z",
      // A hold a maintainer cleared: the comment names the approver, and the
      // record must not. This is PRIV-10's whole sentence, as a fixture.
      body: botComment({ repo: "Belnash3/image-gen", tag: "v0.1.1", id: "image-gen", version: "0.1.1", outcome: "publish", approvedBy: "astra-maintainer-7" }),
    },
    {
      // The stranger imitating the marker, byte for byte, with a verdict that
      // would list a plugin nobody submitted.
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: { login: "Belnash3", type: "User" },
      created_at: "2026-09-12T17:00:00Z",
      body: botComment({ repo: "Belnash3/image-gen", tag: "v9.9.9", id: "image-gen", version: "9.9.9", outcome: "publish" }),
    },
    {
      // And the same imitation from an account whose login is the bot's, which
      // GitHub does not allow and this file does not rely on it not allowing.
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: { login: BOT_LOGINS[0], type: "User" },
      created_at: "2026-09-12T17:00:01Z",
      body: botComment({ repo: "Belnash3/image-gen", tag: "v8.8.8", id: "image-gen", version: "8.8.8", outcome: "publish" }),
    },
    {
      issue_url: "https://api.github.com/repos/o/r/issues/1",
      user: { login: "mihailinl", type: "User" },
      created_at: "2026-09-12T17:01:00Z",
      body: "I am rejecting this because the licence looks copied",
    },
    {
      issue_url: "https://api.github.com/repos/o/r/issues/2",
      user: BOT,
      created_at: "2026-08-20T17:27:37Z",
      body: botComment({ repo: "teletemagame-dev/minecraft-for-astra", tag: "v0.3.1", id: "minecraft-for-astra", version: "0.3.1", outcome: "delay" }),
    },
    {
      issue_url: "https://api.github.com/repos/o/r/issues/4",
      user: BOT,
      created_at: "2026-09-01T00:01:00Z",
      body: botComment({ repo: "knice/telegram-client", tag: "v0.2.0", id: "telegram-client", version: "0.2.0", outcome: "publish" }),
    },
  ];
  return { issues, comments };
}

await test("a report issue is out of scope, so its text is never read", () => {
  assert.equal(issueScope({ title: "Plugin report: telegram-client 0.2.0 (broken)", labels: [] }), null);
  assert.equal(issueScope({ title: "[listing] a/b", labels: [] }), "listing", "a listing form that lost its label");
  assert.equal(issueScope({ title: "x", labels: [{ name: "listing" }] }), "listing");
  assert.equal(issueScope({ title: "[release] a/b v1", labels: [] }), "release-ping",
    "release-ping.yml applies no label on purpose, so the title is the only handle");
  assert.equal(issueScope({ title: "[notice] doom 0.1.3 publishes itself", labels: [] }), "notice");
});

await test("the corpus: every decision, and only the decisions", () => {
  const { facts, counts } = exportFacts(fixtureCorpus());
  // A floor, so an emptied parser goes red rather than quiet.
  assert.ok(facts.length >= 4, `the fixture thread holds four decisions and this found ${facts.length}`);
  assert.deepEqual(
    facts.map((f) => `${f.repository}@${f.tag} ${f.state}`).sort(),
    [
      "Belnash3/image-gen@v0.1.0 refused",
      "Belnash3/image-gen@v0.1.1 approved",
      "mihailinl/AstraPlugins@doom-v0.1.3 approved",
      "teletemagame-dev/minecraft-for-astra@v0.3.1 approved",
    ],
    "the imitations yield nothing, and the report thread is not read at all",
  );
  // Three issue bodies and four comments: two humans, two imitations, and the
  // two forms themselves. An issue body is read exactly like a comment, which
  // is what lets the `[notice]` case below work at all.
  assert.equal(counts.dropped.not_the_bot, 7, "every document whose author is not the bot, body or comment");
  assert.equal(counts.issues_read, 5, "the pull request this endpoint also returns is not an issue");
  assert.equal(counts.issues_in_scope, 4, "and the report thread is not in scope");
});

await test("a [notice] issue's BODY is a decision, and eight of them exist on this repository", () => {
  const { facts } = exportFacts(fixtureCorpus());
  const notice = facts.find((f) => f.repository === "mihailinl/AstraPlugins");
  assert.ok(notice, "a comment-only export drops every release that had no submission issue");
  assert.equal(notice.state, "approved");
  assert.equal(notice.date, "2026-08-19T21:00:26Z", "the issue's own date, not a comment's");
});

await test("nothing a stranger typed reaches the facts or the records", () => {
  const { facts } = exportFacts(fixtureCorpus());
  const composed = composeRecords(facts);

  // Over the SERIALISED output rather than member by member: a member-by-member
  // check only ever covers the members somebody thought of, and the whole
  // reason this export is split is that the half doing the composing should be
  // unable to name a member nobody listed.
  const text = `${JSON.stringify(facts)}\n${JSON.stringify(composed.map((c) => c.record))}`;
  for (const needle of NEEDLES) {
    // `Belnash3` and `teletemagame-dev` are repository owners, which PRIV-2
    // permits in `repo` and which the marker composed from the run. They are in
    // the list so that the two that are NOT permitted are visibly a different
    // kind of thing.
    if (needle === "Belnash3" || needle === "teletemagame-dev") continue;
    assert.ok(!text.includes(needle), `"${needle.slice(0, 40)}…" is in the output and PRIV-2 forbids it`);
  }
  for (const { record } of composed) {
    for (const [member, value] of Object.entries(record)) {
      for (const s of Array.isArray(value) ? value : [value]) {
        assert.ok(!String(s).includes("@"), `\`${member}\` holds an @, which is where a login and an address start`);
      }
    }
  }
});

// ── the records ─────────────────────────────────────────────────────────────

/**
 * DEC-7's member list, as contract 0.13.0 §2 writes it.
 *
 * Copied deliberately rather than imported: `schema/decision-v1.json` is
 * B-T2.1's — and **it IS on `main`**: all three of B-T2.1's schemas are tracked,
 * and this sentence said "is not on `main`" until 2026-09-22. The point of the
 * assertion is unchanged: this export composes nothing the contract did not
 * name.
 *
 * WHAT THE STALENESS COSTS HERE IS SPECIFIC: the old sentence ended "when the
 * schema lands, RC-R3-2 compares the two directions" — a future tense over a
 * thing that has happened. **RC-R3-2's comparison is therefore owed now, and
 * nothing is tracking that it is owed**, because the only note saying so
 * described it as waiting for a landing that already occurred.
 */
const DEC7_MEMBERS = new Set([
  "schema", "decision_id", "submission_id", "decided_at", "actor", "moderator", "trigger", "plugin_id",
  "version", "repo", "repository_id", "repository_owner_id", "tag", "commit", "artifact_digests",
  "fingerprint", "state", "reasons", "category", "appeal_of", "outcome", "declared_interest",
  "publish_after", "run", "advisory",
]);

await test("one migration record per fact, actor system, and only DEC-7's members", () => {
  const { facts } = exportFacts(fixtureCorpus());
  const composed = composeRecords(facts);
  assert.equal(composed.length, facts.length, "MIG-21: one record each");
  for (const { key, record } of composed) {
    assert.match(key, /^history:[^@]+@[^:]+:[0-9T:-]+Z:(refused|approved)$/, "BOT-35's `history:` key (contract 2.5.0)");
    assert.equal(record.actor, "system", "PRIV-10: every historic approver is `system`");
    assert.equal(record.trigger, "migration", "DEC-7's trigger, reserved for MIG-20 and MIG-21");
    assert.ok(record.state === "refused" || record.state === "approved",
      "MIG-21: never `published`, so an export record can never form MIG-20's baseline");
    assert.equal(record.schema, undefined, "B-T2.2's writer stamps the schema");
    assert.equal(record.decision_id, undefined, "and derives the id, in one place");
    for (const member of Object.keys(record)) {
      assert.ok(DEC7_MEMBERS.has(member), `\`${member}\` is not a member DEC-7 names`);
    }
  }
});

await test("a login written into a record is refused by the allowlist, not by a blocklist", () => {
  const record = { decided_at: "2026-08-20T07:19:05Z", actor: "system", trigger: "migration", repo: "a/b", tag: "v1", state: "approved" };
  assert.doesNotThrow(() => refuseUncomposable(record));
  assert.throws(() => refuseUncomposable({ ...record, login: "Belnash3" }), /not a member this export composes/,
    "this is the `comment.user.login` mutation the plan asks to be watched");
  assert.throws(() => refuseUncomposable({ ...record, moderator: "Belnash3" }),
    /not a member this export composes/,
    "and `moderator` is a DEC-7 member that this export must still never write");
  assert.throws(() => refuseUncomposable({ ...record, actor: "moderator" }), /does not match its own grammar/);
  assert.throws(() => refuseUncomposable({ ...record, state: "published" }), /does not match its own grammar/);
});

await test("two decisions about one tag get two `history:` keys and two records; one decision read twice is refused", () => {
  // Until contract 2.5.0 both facts below shared `migration:a/b@v1`, and
  // composing them was refused: the live archive had 24 such keys across 102
  // facts on 2026-09-24. `history:` adds the time and the state, so MIG-21's
  // "one record each" holds, and over that archive no key is shared.
  const facts = [
    { repository: "a/b", tag: "v1", plugin_id: null, version: null, state: "refused", date: "2026-08-01T00:00:00Z", reasons: [] },
    { repository: "a/b", tag: "v1", plugin_id: "bee", version: "1.0.0", state: "approved", date: "2026-08-02T00:00:00Z", reasons: [] },
  ];
  assert.deepEqual(keyCollisions(facts), []);
  assert.deepEqual(composeRecords(facts).map((c) => c.key), [
    "history:a/b@v1:2026-08-01T00:00:00Z:refused",
    "history:a/b@v1:2026-08-02T00:00:00Z:approved",
  ]);
  // The same decision twice, same time and same state, is one line of the
  // archive read twice. Writing one record for it would hide the double read,
  // so it is still refused, by key.
  const twice = [facts[0], { ...facts[0] }];
  assert.deepEqual(keyCollisions(twice), [{ key: "history:a/b@v1:2026-08-01T00:00:00Z:refused", facts_sharing_it: 2 }]);
  assert.throws(() => composeRecords(twice), /derive one id and overwrite each other/,
    "silently writing one record for two facts is the failure this refusal exists to prevent");
});

await test("--compose refuses by name while B-T2.2's writer is absent, and takes it when it is there", async () => {
  // The first half of this test asserted the refusal until 2026-09-20. B-T2.2
  // landed `bot/lib/decisions.mjs`, so `resolveWriter({})` now resolves, and
  // the title's second clause — "and takes it when it is there" — is the half
  // that still has work to do. The refusal branch is kept by passing a root
  // where the module genuinely is not, so the sentence it prints is still
  // pinned for whoever meets it in a checkout without the module.
  await assert.rejects(
    () => resolveWriter({ root: "/nowhere", load: async () => { throw new Error("ENOENT"); } }),
    /decision-record writer/,
    "there is no second composer here, and the refusal says whose the first one is",
  );
  const writer = await resolveWriter({
    root: "/nowhere",
    load: async () => ({ writeDecisionRecord: () => ({ path: "log/decisions/2026/08/abc.json" }) }),
  }).catch((e) => e);
  assert.ok(writer instanceof Error, "a root with no decisions.mjs still refuses, before the loader is asked");
});

// ── result ──────────────────────────────────────────────────────────────────

console.log();
if (failures) {
  console.log(`FAIL  ${passed} passed, ${failures} failed`);
  process.exit(1);
}
console.log(`PASS  ${passed} passed, 0 failed`);
