#!/usr/bin/env node
// The registry bot's own suite.  `node bot/tests/ingest.test.mjs`
//
// Three things are being asserted, and they are not the same thing:
//
//   1. **The shared corpus.** Every one of the golden bundles vendored from
//      AstraPlugins/testdata/bundles is fed through the WHOLE ingest pipeline —
//      release, attestation, archive, manifest probe, names, derivation — and
//      has to produce the verdict recorded in `vectors.json`'s `expect.registry`
//      column. tools/selftest.mjs already checks the structural half against the
//      same file; this checks the program a submission actually meets.
//
//   2. **One test per failure class**, each asserting the FIXED CODE. The
//      acceptance criterion for task 3.3 is that every failure class produces a
//      fixed code and an actionable comment, and a code nobody asserts is a code
//      that quietly becomes E_MANIFEST_INVALID.
//
//   3. **The conforming case ingests with zero human action.** That is the
//      whole point of the task, and it is the one test that would fail silently
//      if the bot became too strict — a bot that rejects everything passes every
//      negative test in this file.
//
// Nothing here touches the network. `bot/fixtures/ingest/make.mjs` builds the
// bundles and a GitHub that answers from a table, which is also why the tests
// can assert things a live GitHub would never let them arrange — an asset URL
// pointing at another repository, an attestation for the wrong bytes.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ingest, renderComment, DEFAULT_SIGNER_WORKFLOW } from "../ingest.mjs";
import { CODES, codeDef } from "../lib/codes.mjs";
import { deriveLocaleText } from "../lib/locales.mjs";
import { summarise } from "../lib/derive.mjs";
import { loadPolicy } from "../../tools/lib/sources.mjs";
import { classifyFile, scanHostRpcs } from "../lib/rpcscan.mjs";
import { checkNames, foldDisplayName, loadTrademarks } from "../lib/names.mjs";
import { extractSignerFacts, loadWorkflowAllowlist } from "../lib/attestation.mjs";
import { proveOwnership } from "../lib/ownership.mjs";
import { isRecheckCommand, parseIssueForm } from "../lib/issue.mjs";
import { findProbe, runProbe } from "../lib/probe.mjs";
import { makeBundle, fakeGitHub, fakeGh, fakeOwnership, FIXTURE_SIGNER_WORKFLOW } from "../fixtures/ingest/make.mjs";

const REPO_ROOT = path.resolve(fileURLToPath(new URL("../..", import.meta.url)));
const VECTOR_DIR = path.join(REPO_ROOT, "tests", "vectors");

// ── a test harness, in twenty lines ─────────────────────────────────────────

let passed = 0;
const failures = [];
let group = "";
/** Every code any test saw the bot emit, for the canary at the end. */
const emitted = new Set();

function section(name) { group = name; console.log(`\n${name}`); }
async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok    ${name}`);
  } catch (e) {
    failures.push({ group, name, error: e });
    console.log(`  FAIL  ${name}\n        ${e.message.split("\n").join("\n        ")}`);
  }
}
function assert(cond, message) { if (!cond) throw new Error(message); }
function assertEqual(actual, expected, message) {
  if (actual !== expected) throw new Error(`${message}\n  expected: ${expected}\n  actual:   ${actual}`);
}

// ── the world every test starts from ────────────────────────────────────────

const REPO = "a-stranger/dice-roller";
const TAG = "v0.2.0";
const SUBMITTER = "a-stranger";
/** The one commit `tools/testkeys/fixtures/trust-active-signed.json` allows. */
const ALLOWED_WORKFLOW_SHA = "0".repeat(40);

/**
 * A root.json carrying the TEST roots, written to a temp file.
 *
 * Built from `tools/testkeys/*.pub.json` rather than committed, so it cannot
 * drift from the keys that signed the trust fixture, and so no file in this
 * repository ever looks like a provisioned production root. The real
 * `registry/v1/root.json` stays empty, and one of the tests below asserts that
 * an ingest against it fails closed.
 */
function testRootsFile() {
  const keys = ["root-a", "root-b"].map((n) =>
    JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "tools", "testkeys", `TEST-ONLY-DO-NOT-TRUST-${n}.pub.json`), "utf8")));
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "astra-testroots-"));
  const file = path.join(dir, "root.json");
  fs.writeFileSync(file, JSON.stringify({
    $banner: "TEST ROOTS — generated by bot/tests/ingest.test.mjs, never committed, never trusted by a daemon.",
    schema: "astra.registry.root/1",
    status: "provisioned",
    roots: keys.map((k) => ({ key_id: k.key_id, public_key: k.public_key, role: k.role })),
  }, null, 2));
  return file;
}

const ROOTS_FILE = testRootsFile();
const TRUST_FILE = path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-active-signed.json");

/**
 * Run one ingest against a world assembled from the arguments.
 *
 * Every dependency is injected. Production passes none of them, so this is a
 * seam and not a mode: there is no flag on `bot/ingest.mjs` that turns the
 * attestation check off, which there would have to be if the tests needed one.
 */
async function run({
  assets, repo = REPO, tag = TAG, submitter = SUBMITTER, root = REPO_ROOT,
  signerDigest = ALLOWED_WORKFLOW_SHA, attestRepo = repo, ghFail = null,
  ownershipOk = true, signerUri = undefined, subjectOverride = null, certRepo = null,
  rootsFile = ROOTS_FILE, trustFile = TRUST_FILE,
  signerWorkflow = DEFAULT_SIGNER_WORKFLOW,
} = {}) {
  const github = fakeGitHub({ repo, tag, assets });
  const result = await ingest(
    { repo, tag, submitter, root, rootsFile, trustFile, signerWorkflow },
    {
      fetchRelease: github.fetchRelease.bind(github),
      headAsset: github.headAsset.bind(github),
      downloadAsset: github.downloadAsset.bind(github),
      proveOwnership: fakeOwnership(ownershipOk),
      ghRunner: (args) => {
        // The digest `gh` is asked about is the digest of the file on disk, so
        // the fake computes it the same way the real one would: from the bytes
        // it was handed.
        const file = args[2];
        const bytes = fs.readFileSync(file);
        const digest = subjectOverride ?? crypto.createHash("sha256").update(bytes).digest("hex");
        return fakeGh({ repo: attestRepo, signerDigest, subjectDigest: digest, signerUri, certRepo, fail: ghFail })(args);
      },
    },
  );
  for (const i of result.findings) emitted.add(i.code);
  return result;
}

const codes = (r) => r.findings.map((i) => i.code);
const errorCodes = (r) => r.findings.filter((i) => i.level === "error").map((i) => i.code);
function assertBlockedWith(r, code) {
  assert(r.blocked, `expected a block; got ${JSON.stringify(r.findings.map((i) => `${i.level}:${i.code}`))}`);
  assert(errorCodes(r).includes(code),
    `expected ${code}; the blocking codes were ${JSON.stringify(errorCodes(r))}`);
}

/** Every scratch tree these tests made, removed when the run ends. */
const scratch = [];
process.on("exit", () => {
  for (const d of scratch) fs.rmSync(d, { recursive: true, force: true });
});

/** A registry tree holding one already-listed plugin, so updates can be tested. */
function registryWith({ id = "dice-roller", version = "0.1.0", repo = REPO, name = "Dice Roller", i18n } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "astra-reg-"));
  scratch.push(dir);
  const pdir = path.join(dir, "plugins", id, "versions");
  fs.mkdirSync(pdir, { recursive: true });
  fs.writeFileSync(path.join(dir, "plugins", id, "plugin.json"), JSON.stringify({
    schema: "astra.registry.plugin/1",
    id, name,
    summary: "Rolls dice when you ask it to.",
    license: "MIT",
    source: { kind: "github", repo },
    added_at: "2026-01-01",
    // A listing that already carries localized card names, so a submission can
    // be compared against the names a Russian user actually reads rather than
    // only against the English ones a reviewer does.
    ...(i18n ? { i18n } : {}),
  }, null, 2));
  fs.writeFileSync(path.join(pdir, `${version}.json`), JSON.stringify({
    schema: "astra.registry.version/1",
    id, version,
    published_at: "2026-01-01T00:00:00Z",
    release: { kind: "github_release", repo, tag: `v${version}` },
    staging: true,
    staging_reason: "Test fixture: the release this points at is a fake, so there is no digest to pin.",
    artifacts: {
      "linux-x64": {
        url: `https://github.com/${repo}/releases/download/v${version}/dice-roller-${version}-linux-x64.astraplugin`,
        filename: `dice-roller-${version}-linux-x64.astraplugin`,
      },
    },
  }, null, 2));
  return dir;
}

/**
 * The name the CLI gives a bundle: `<id>-<version>-<target>.astraplugin`. The
 * registry enforces it (a stale bundle from the previous version is the most
 * likely wrong-but-plausible asset), so the fixtures have to use it too.
 */
const bundleName = (spec = {}) =>
  `${spec.id ?? "dice-roller"}-${spec.version ?? "0.2.0"}-${
    spec.os === "windows" ? "windows-x64" : "linux-x64"}.astraplugin`;

const conformingAsset = (spec = {}) => ({ name: bundleName(spec), bytes: makeBundle(spec) });

// ═══════════════════════════════════════════════════════════════════════════

section("the shared corpus (AstraPlugins/testdata/bundles, whole pipeline)");

const vectors = JSON.parse(fs.readFileSync(path.join(VECTOR_DIR, "vectors.json"), "utf8")).vectors;

await test(`the corpus is the ${vectors.length} vectors the shared file records`, () => {
  const onDisk = fs.readdirSync(VECTOR_DIR).filter((f) => f.endsWith(".astraplugin"));
  assertEqual(onDisk.length, vectors.length, "every vector file has an entry and every entry has a file");
});

for (const v of vectors) {
  await test(`${v.name} — the pipeline ${v.expect.registry}s it`, async () => {
    const r = await run({
      assets: [{
        // Named the way the CLI names bundles, from the vector's own recorded
        // facts: the corpus files are named after the property they test, and
        // the registry's filename rule is a separate check with its own test.
        name: `${v.plugin_id ?? "vector-plugin"}-${v.version ?? "1.0.0"}-${v.platform_key ?? "linux-x64"}.astraplugin`,
        bytes: fs.readFileSync(path.join(VECTOR_DIR, v.file)),
      }],
    });
    const verdict = r.blocked ? "reject" : "accept";
    assertEqual(verdict, v.expect.registry,
      `${v.name}: ${v.why_it_matters?.slice(0, 120) ?? ""}\n  findings: ${JSON.stringify(r.findings.filter((i) => i.level === "error" || i.level === "warn"))}`);
  });
}

// ═══════════════════════════════════════════════════════════════════════════

section("the acceptance case: a conforming release, no human");

await test("an update to an already-listed plugin ingests with zero human action", async () => {
  const root = registryWith({});
  const r = await run({ assets: [conformingAsset()], root });
  assert(!r.blocked, `blocked: ${JSON.stringify(r.findings.filter((i) => i.level === "error"))}`);
  assert(!r.needsReview,
    `held for review: ${JSON.stringify(r.findings.filter((i) => i.level === "review"))}`);
  assertEqual(r.derived.plugin.id, "dice-roller", "the id came out of the bundle");
  assertEqual(r.derived.version.version, "0.2.0", "so did the version");
  assertEqual(r.derived.plugin.license, "MIT", "and the licence");
  assertEqual(r.derived.version.artifacts["linux-x64"].size, conformingAsset().bytes.length, "and the size");
  assert(codes(r).includes("E_DERIVED_LISTING_INVALID"),
    "the derived listing is run past tools/validate.mjs and the row is recorded either way");
  assert(r.findings.some((i) => i.code === "E_DERIVED_LISTING_INVALID" && i.level === "pass"),
    "…and it passed");
});

await test("a first listing is held for a human, and nothing else is wrong with it", async () => {
  const r = await run({ assets: [conformingAsset()], root: registryWith({ id: "something-else" }) });
  assert(!r.blocked, `nothing should block: ${JSON.stringify(errorCodes(r))}`);
  assert(r.needsReview, "a first listing is one of the three events a human owns");
  assert(codes(r).includes("R_FIRST_LISTING"), JSON.stringify(codes(r)));
});

await test("two platforms in one release become two artifact keys", async () => {
  const root = registryWith({});
  const r = await run({
    assets: [
      { name: "dice-roller-0.2.0-linux-x64.astraplugin", bytes: makeBundle({ os: "linux" }) },
      { name: "dice-roller-0.2.0-windows-x64.astraplugin", bytes: makeBundle({ os: "windows" }) },
    ],
    root,
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assertEqual(Object.keys(r.derived.version.artifacts).sort().join(","), "linux-x64,windows-x64", "both hosts listed");
});

await test("everything except the repository and the tag comes out of the bundle", async () => {
  const root = registryWith({});
  const r = await run({
    assets: [conformingAsset({
      name: "Dice Roller Deluxe",
      description: "Rolls polyhedral dice and reads the result aloud.",
      author: "Someone Else Entirely",
      license: "Apache-2.0",
      capabilities: ["tools", "tts"],
    })],
    root,
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assertEqual(r.derived.plugin.name, "Dice Roller Deluxe", "the display name is the manifest's");
  assertEqual(r.derived.plugin.author.name, "Someone Else Entirely", "so is the author");
  assertEqual(r.derived.plugin.license, "Apache-2.0", "so is the licence");
  assertEqual(r.derived.version.capabilities.join(","), "tools,tts", "so are the capabilities");
  assertEqual(r.derived.plugin.source.repo, REPO, "and the repository is the one fact that was typed");
});

// ═══════════════════════════════════════════════════════════════════════════

section("failing closed");

await test("with no signed trust.json, nothing is listed and the reason says so", async () => {
  // The absent file is named deliberately. This pointed at the REAL
  // `registry/v1/trust.json` and passed because that file did not exist — so
  // the day one was signed and published it began failing with
  // `expected E_TRUST_UNPROVISIONED; the blocking codes were
  // ["E_WORKFLOW_NOT_ALLOWED"]`. That is the run getting further, correctly:
  // the test was asserting a state of the world, not a behaviour.
  //
  // What it exists for survives. With nothing delegated there is no allowlist
  // to check an attestation against, and the bot must stop at the anchor rather
  // than proceed on a catalogue nobody vouched for.
  const r = await run({
    assets: [conformingAsset()],
    rootsFile: path.join(REPO_ROOT, "registry", "v1", "root.json"),
    trustFile: path.join(REPO_ROOT, "registry", "v1", "trust.json.no-such-file"),
  });
  assertBlockedWith(r, "E_TRUST_UNPROVISIONED");
  assert(r.findings.length === 1, "and it stops there rather than spending a stranger's bandwidth");
});

await test("the published trust.json delegates a non-empty allowlist", () => {
  // The other half, assertable only now that one is signed: the committed
  // document verifies under the committed roots and yields an allowlist. If it
  // ever stops doing so — expired, a key rotated out, the file edited — every
  // ingest silently returns to the state above, and the message a submitter
  // gets says the anchor is missing rather than that it went stale.
  const verdict = loadWorkflowAllowlist({
    trustFile: path.join(REPO_ROOT, "registry", "v1", "trust.json"),
    rootsFile: path.join(REPO_ROOT, "registry", "v1", "root.json"),
  });
  assert(verdict.ok, verdict.message ?? "the committed trust.json does not verify under the roots");
  assert(
    verdict.allowlist.length > 0,
    "it verifies but delegates no reusable-workflow commit, so every release ingest would stop at E_WORKFLOW_NOT_ALLOWED",
  );
});

await test("a trust.json signed by a stranger is not a trust.json", () => {
  const verdict = loadWorkflowAllowlist({
    trustFile: path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-stranger-signed.json"),
    rootsFile: ROOTS_FILE,
  });
  assert(!verdict.ok, "a document signed by a key no root vouches for must not deliver an allowlist");
  assertEqual(verdict.code, "E_TRUST_UNPROVISIONED", verdict.message);
});

await test("a trust.json tampered with after signing is refused", () => {
  const verdict = loadWorkflowAllowlist({
    trustFile: path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-reserve-signed-tampered.json"),
    rootsFile: ROOTS_FILE,
  });
  assert(!verdict.ok, verdict.message ?? "");
});

await test("the reserve root is a root", () => {
  const verdict = loadWorkflowAllowlist({
    trustFile: path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-reserve-signed.json"),
    rootsFile: ROOTS_FILE,
  });
  assert(verdict.ok, "replacing a root must be a signature, not a flag day");
});

await test("a missing manifest probe fails the run rather than skipping the check", async () => {
  const empty = fs.mkdtempSync(path.join(os.tmpdir(), "astra-noprobe-"));
  const saved = process.env.ASTRA_MANIFEST_PROBE;
  delete process.env.ASTRA_MANIFEST_PROBE;
  try {
    const out = await runProbe({ pluginToml: "", botDir: empty });
    assertEqual(out.findings[0].code, "E_PROBE_UNAVAILABLE", JSON.stringify(out.findings));
    assertEqual(out.manifest, null, "nothing is reported about a manifest nothing parsed");
    emitted.add(out.findings[0].code);
  } finally {
    if (saved !== undefined) process.env.ASTRA_MANIFEST_PROBE = saved;
  }
});

await test("the probe the tests run is the real one, built from the daemon's crate", () => {
  assert(findProbe() !== null,
    "build it: bot/manifest-probe/link-deps.sh && cargo build --release --manifest-path bot/manifest-probe/Cargo.toml");
});

// ═══════════════════════════════════════════════════════════════════════════

section("the two typed facts");

await test("E_INPUT_REPO — a repository that is not owner/name", async () => {
  const r = await run({ assets: [conformingAsset()], repo: "https://github.com/a/b" });
  assertBlockedWith(r, "E_INPUT_REPO");
});

await test("E_INPUT_TAG — a tag with a space in it", async () => {
  const r = await run({ assets: [conformingAsset()], tag: "v0.2.0 latest" });
  assertBlockedWith(r, "E_INPUT_TAG");
});

await test("E_RELEASE_NOT_FOUND — the tag does not exist", async () => {
  const github = fakeGitHub({ repo: REPO, tag: "v9.9.9", assets: [conformingAsset()] });
  const r = await ingest(
    { repo: REPO, tag: TAG, submitter: SUBMITTER, root: REPO_ROOT, rootsFile: ROOTS_FILE, trustFile: TRUST_FILE },
    { fetchRelease: github.fetchRelease.bind(github), proveOwnership: fakeOwnership() },
  );
  for (const i of r.findings) emitted.add(i.code);
  assertBlockedWith(r, "E_RELEASE_NOT_FOUND");
});

await test("E_NO_BUNDLE_ASSETS — a release with no .astraplugin on it", async () => {
  const r = await run({ assets: [{ name: "dice-roller.tar.gz", bytes: Buffer.from("nope") }] });
  assertBlockedWith(r, "E_NO_BUNDLE_ASSETS");
});

await test("E_OWNERSHIP_UNPROVEN — the submitter does not control the repository", async () => {
  const r = await run({ assets: [conformingAsset()], ownershipOk: false });
  assertBlockedWith(r, "E_OWNERSHIP_UNPROVEN");
});

section("the asset");

await test("E_ASSET_URL_FOREIGN — an asset served from another repository's release", async () => {
  const r = await run({
    assets: [{
      name: "dice-roller-0.2.0-linux-x64.astraplugin",
      bytes: makeBundle(),
      url: "https://github.com/someone-else/other/releases/download/v1/dice-roller-0.2.0-linux-x64.astraplugin",
    }],
  });
  assertBlockedWith(r, "E_ASSET_URL_FOREIGN");
});

await test("E_ASSET_FILENAME — a stale bundle from the previous version", async () => {
  const r = await run({
    assets: [{ name: "dice-roller-0.1.9-linux-x64.astraplugin", bytes: makeBundle() }],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_ASSET_FILENAME");
});

await test("E_ASSET_SIZE — the bytes are not the bytes the release advertised", async () => {
  const r = await run({
    assets: [{ name: "dice-roller-0.2.0-linux-x64.astraplugin", bytes: makeBundle(), apiSize: 12 }],
  });
  assertBlockedWith(r, "E_ASSET_SIZE");
});

await test("E_ARTIFACT_TOO_LARGE — refused from the HEAD, before the download", async () => {
  const r = await run({
    assets: [{ name: "dice-roller-0.2.0-linux-x64.astraplugin", bytes: makeBundle(), headSize: 1024 ** 3 }],
  });
  assertBlockedWith(r, "E_ARTIFACT_TOO_LARGE");
});

section("provenance");

await test("E_ATTESTATION_MISSING — a hand-built bundle", async () => {
  const r = await run({ assets: [conformingAsset()], ghFail: "no attestations found for a-stranger/dice-roller" });
  assertBlockedWith(r, "E_ATTESTATION_MISSING");
});

await test("E_ATTESTATION_INVALID — the verification failed for some other reason", async () => {
  const r = await run({ assets: [conformingAsset()], ghFail: "signature verification failed" });
  assertBlockedWith(r, "E_ATTESTATION_INVALID");
});

await test("E_ATTESTATION_SUBJECT_MISMATCH — attested bytes that are not these bytes", async () => {
  const r = await run({ assets: [conformingAsset()], subjectOverride: "f".repeat(64) });
  assertBlockedWith(r, "E_ATTESTATION_SUBJECT_MISMATCH");
});

await test("E_ATTESTATION_REPO_MISMATCH — built somewhere other than the listed repository", async () => {
  const r = await run({ assets: [conformingAsset()], attestRepo: "someone-else/other" });
  // `gh --repo` would refuse it too; the bot checks the certificate itself so
  // the answer does not depend on which flags a future gh honours.
  assert(r.blocked, JSON.stringify(codes(r)));
  assert(errorCodes(r).some((c) => c.startsWith("E_ATTESTATION")), JSON.stringify(errorCodes(r)));
});

await test("E_ATTESTATION_REPO_MISMATCH — a certificate naming another repository", async () => {
  const r = await run({ assets: [conformingAsset()], certRepo: "someone-else/other" });
  assertBlockedWith(r, "E_ATTESTATION_REPO_MISMATCH");
});

await test("E_WORKFLOW_NOT_ALLOWED — a valid attestation from a workflow nobody pinned", async () => {
  const r = await run({ assets: [conformingAsset()], signerDigest: "c".repeat(40) });
  assertBlockedWith(r, "E_WORKFLOW_NOT_ALLOWED");
  const finding = r.findings.find((i) => i.code === "E_WORKFLOW_NOT_ALLOWED");
  assert(finding.message.includes("c".repeat(40)), "the comment names the commit that was refused");
});

await test("the default signer-workflow pin names a file that actually exists", () => {
  // **The transposition this catches.** The constant read
  // `release-plugin.yml` while the file in AstraPlugins is
  // `plugin-release.yml`. `gh attestation verify --signer-workflow` matches on
  // that path, so the pin matched no attestation ever produced — every honest
  // submission would have come back E_ATTESTATION_MISSING and the failure would
  // have looked like the author's fault. No fixture could catch it, because the
  // fake `gh` ignored the flag entirely.
  //
  // Asserted against the real directory when it is reachable, and against the
  // fixture constant always, so the pair cannot drift even off a machine that
  // does not have AstraPlugins checked out beside this repository.
  assertEqual(DEFAULT_SIGNER_WORKFLOW, FIXTURE_SIGNER_WORKFLOW,
    "the pin and the workflow the fixtures are signed by must be one string");
  const [owner, repo, ...rest] = DEFAULT_SIGNER_WORKFLOW.split("/");
  assertEqual(`${owner}/${repo}`, "mihailinl/AstraPlugins", "the pin names the Astra repository");
  const relative = rest.join("/");
  assert(relative.startsWith(".github/workflows/"), `not a workflow path: ${relative}`);
  const checkout = path.resolve(REPO_ROOT, "..", "AstraPlugins");
  const dir = path.join(checkout, ".github", "workflows");
  if (!fs.existsSync(dir)) return; // not checked out beside us; the pair above still held
  const names = fs.readdirSync(dir);
  assert(names.includes(path.basename(relative)),
    `${DEFAULT_SIGNER_WORKFLOW} names a workflow that does not exist. ` +
    `AstraPlugins/.github/workflows/ contains ${JSON.stringify(names)}`);
});

await test("E_ATTESTATION_MISSING — a pin that matches no attestation", async () => {
  // The class the transposition belonged to, made catchable: `gh` is asked
  // about a workflow path the build was not signed by, and answers the way the
  // real one does. Before `fakeGh` read `--signer-workflow` this test passed
  // whatever the constant said.
  const r = await run({
    assets: [conformingAsset()],
    signerWorkflow: "mihailinl/AstraPlugins/.github/workflows/release-plugin.yml",
  });
  assertBlockedWith(r, "E_ATTESTATION_MISSING");
});

await test("an attestation carrying no resolved signer commit proves nothing", () => {
  const facts = extractSignerFacts([{
    verificationResult: { statement: { subject: [{ digest: { sha256: "a".repeat(64) } }] } },
  }]);
  assertEqual(facts.signerDigest, null, "a field that is absent must be null, never a default");
});

section("names");

await test("E_TYPOSQUAT_COLLISION — an id that folds onto a listed one", async () => {
  const r = await run({ assets: [conformingAsset({ id: "diceroller" })], root: registryWith({}) });
  assertBlockedWith(r, "E_TYPOSQUAT_COLLISION");
});

await test("R_TYPOSQUAT_NEAR — one edit away is a decision, not a rejection", async () => {
  const r = await run({ assets: [conformingAsset({ id: "dice-rollers" })], root: registryWith({}) });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assert(codes(r).includes("R_TYPOSQUAT_NEAR"), JSON.stringify(codes(r)));
});

await test("R_DISPLAY_NAME_COLLISION — same name, different spacing", () => {
  const found = checkNames(
    { id: "other-thing", name: "Dice  Roller", repoOwner: "x" },
    [{ id: "dice-roller", name: "Dice Roller" }],
    { flagDistance: 1, trademarks: loadTrademarks() },
  );
  assert(found.some((i) => i.code === "R_DISPLAY_NAME_COLLISION"), JSON.stringify(found));
  for (const i of found) emitted.add(i.code);
});

await test("a display name folds on case and whitespace only, never on digits", () => {
  assertEqual(foldDisplayName("  Dice   ROLLER "), "dice roller", "case and runs of space");
  assert(foldDisplayName("Mp3 Tools") !== foldDisplayName("Mpo Tools"),
    "an id fold would collide these two; a display name must not");
});

await test("R_DISPLAY_NAME_COLLISION — a BYTE-IDENTICAL name is the strongest case, not an exception", async () => {
  // The rule read `folds equal && other.name !== candidate.name`. The second
  // clause excluded the exactly-equal case, so every weaker variant was held
  // for a human and the strongest one published unattended: an already-listed
  // plugin could repaint its store card as a popular plugin's, exactly, with no
  // review and no delay.
  const found = checkNames(
    { id: "roll-dice-pro", name: "Dice Roller", repoOwner: "mallory" },
    [{ id: "dice-roller", name: "Dice Roller" }],
    { flagDistance: 1, trademarks: loadTrademarks() },
  );
  assert(found.some((i) => i.code === "R_DISPLAY_NAME_COLLISION"),
    `an identical name must be held: ${JSON.stringify(found)}`);
  for (const i of found) emitted.add(i.code);

  // And end to end, through the decision: the whole point is that it stops
  // being an unattended publish.
  const r = await run({
    assets: [conformingAsset({ id: "roll-dice-pro", name: "Dice Roller" })],
    root: registryWith({}),
  });
  assert(codes(r).includes("R_DISPLAY_NAME_COLLISION"), JSON.stringify(codes(r)));
});

await test("R_DISPLAY_NAME_MIXED_SCRIPT — one Cyrillic letter in a Latin name", async () => {
  // U+0456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I where the ASCII `i`
  // belongs. NFKC does not touch it — it unifies compatibility variants of the
  // same character, not two characters that are drawn alike — and
  // `unsafeDisplayText` does not either, because a homoglyph is not invisible.
  // The card was pixel-identical to the listed plugin's and published with no
  // finding at all.
  const homoglyph = "D\u0456ce Roller";
  assert(homoglyph !== "Dice Roller", "the fixture must actually differ byte-wise");
  const found = checkNames(
    { id: "roll-dice-pro", name: homoglyph, repoOwner: "mallory" },
    [{ id: "dice-roller", name: "Dice Roller" }],
    { flagDistance: 1, trademarks: loadTrademarks() },
  );
  assert(found.some((i) => i.code === "R_DISPLAY_NAME_MIXED_SCRIPT"), JSON.stringify(found));
  assert(found.some((i) => i.code === "R_DISPLAY_NAME_COLLISION"),
    `and it must fold onto the name it is drawn as: ${JSON.stringify(found)}`);
  for (const i of found) emitted.add(i.code);

  // A name written entirely in one alphabet is ordinary and says nothing.
  const cyrillic = checkNames(
    { id: "kosti", name: "\u0418\u0433\u0440\u0430 \u0432 \u043a\u043e\u0441\u0442\u0438", repoOwner: "x" },
    [{ id: "dice-roller", name: "Dice Roller" }],
    { flagDistance: 1, trademarks: loadTrademarks() },
  );
  assertEqual(cyrillic.length, 0, `a Russian name is not a homoglyph attack: ${JSON.stringify(cyrillic)}`);
});

await test("the trademark table catches spot1fy as well as sp0tify", () => {
  // `foldId`'s table is single-valued: `1`→`l`, and nothing maps `1`→`i`. So
  // `Sp0tify Controller` was caught (`0`→`o`) and `Spot1fy Controller` folded
  // to `spotlfy` and matched no mark — the table caught one digit substitution
  // and missed the one next to it. The trademark rule compares SKELETONS now.
  const tm = loadTrademarks();
  for (const name of ["Sp0tify Controller", "Spot1fy Controller", "SpotIfy Controller"]) {
    const found = checkNames({ id: "media-tool", name, repoOwner: "x" }, [], { flagDistance: 1, trademarks: tm });
    assert(found.some((i) => i.code === "E_TRADEMARK"), `${name} must be caught: ${JSON.stringify(found)}`);
  }
  // And the id side of the same rule.
  const byId = checkNames({ id: "spot1fy-tools", name: "Media Tool", repoOwner: "x" }, [], { flagDistance: 1, trademarks: tm });
  assert(byId.some((i) => i.code === "E_TRADEMARK"), JSON.stringify(byId));
});

await test("E_TRADEMARK — a plugin named for somebody else's service", async () => {
  const r = await run({ assets: [conformingAsset({ id: "spotify-tools", name: "Spotify Tools" })] });
  assertBlockedWith(r, "E_TRADEMARK");
});

await test("…and a plugin that merely says which service it talks to is fine", () => {
  const found = checkNames(
    { id: "music-for-spotify", name: "Music controls for Spotify", repoOwner: "x" },
    [],
    { flagDistance: 1, trademarks: loadTrademarks() },
  );
  assertEqual(found.length, 0, `naming the service you integrate with is not a claim: ${JSON.stringify(found)}`);
});

await test("E_ID_RESERVED / E_ID_RESERVED_PREFIX — names that read as first-party", async () => {
  const a = await run({ assets: [conformingAsset({ id: "registry" })] });
  assertBlockedWith(a, "E_ID_RESERVED");
  const b = await run({ assets: [conformingAsset({ id: "astra-tools" })] });
  assertBlockedWith(b, "E_ID_RESERVED_PREFIX");
});

section("metadata, licence, platform");

await test("E_LICENSE_NOT_ALLOWED — a licence nobody here has read", async () => {
  // BUSL-1.1, and it has to be a licence that is genuinely absent from
  // `policy/spdx-allowlist.json` rather than one that merely was. This said
  // `GPL-3.0-only` and stopped testing anything the day the copyleft family was
  // added to the allowlist: the fixture kept naming "a licence nobody here has
  // read" while naming one that had been read and admitted.
  //
  // BUSL is a good long-term choice for this. It is a real, widely used licence
  // and it is source-available rather than open source, so it is not a candidate
  // for the allowlist while §4 of POLICY.md says open source only — which is
  // what this check is enforcing.
  const r = await run({ assets: [conformingAsset({ license: "BUSL-1.1" })] });
  assertBlockedWith(r, "E_LICENSE_NOT_ALLOWED");
});

await test("E_LICENSE_MISSING — no licence at all", async () => {
  const r = await run({ assets: [conformingAsset({ license: "" })] });
  assertBlockedWith(r, "E_LICENSE_MISSING");
});

await test("E_METADATA_UNSAFE_TEXT — a right-to-left override in the display name", async () => {
  const r = await run({ assets: [conformingAsset({ name: "Dice ‮RolleR‬" })] });
  assertBlockedWith(r, "E_METADATA_UNSAFE_TEXT");
});

await test("E_METADATA_MISSING — a manifest that does not say what the plugin is", async () => {
  const r = await run({ assets: [conformingAsset({ description: "" })] });
  assertBlockedWith(r, "E_METADATA_MISSING");
});

await test("E_METADATA_TOO_LONG — a display name past the card's width", async () => {
  const r = await run({ assets: [conformingAsset({ name: "D".repeat(200) })] });
  assertBlockedWith(r, "E_METADATA_TOO_LONG");
});

await test("E_CAPABILITY_UNKNOWN — the capability that drifted", async () => {
  const r = await run({ assets: [conformingAsset({ capabilities: ["ui_panels"] })] });
  assertBlockedWith(r, "E_CAPABILITY_UNKNOWN");
  assert(r.findings.find((i) => i.code === "E_CAPABILITY_UNKNOWN").message.includes("ui_contributions"),
    "the daemon's crate names the correct spelling and the bot passes it through");
});

await test("E_MIN_ASTRA_TOO_NEW — a plugin that needs an Astra nobody has", async () => {
  const github = fakeGitHub({ repo: REPO, tag: TAG, assets: [conformingAsset({ minAstraVersion: "99.0.0" })] });
  const r = await ingest(
    { repo: REPO, tag: TAG, submitter: SUBMITTER, root: registryWith({}), rootsFile: ROOTS_FILE,
      trustFile: TRUST_FILE, hostAstraVersion: "0.9.0" },
    {
      fetchRelease: github.fetchRelease.bind(github),
      headAsset: github.headAsset.bind(github),
      downloadAsset: github.downloadAsset.bind(github),
      proveOwnership: fakeOwnership(true),
      ghRunner: (args) => fakeGh({
        repo: REPO, signerDigest: ALLOWED_WORKFLOW_SHA,
        subjectDigest: crypto.createHash("sha256").update(fs.readFileSync(args[2])).digest("hex"),
      })(args),
    },
  );
  for (const i of r.findings) emitted.add(i.code);
  assertBlockedWith(r, "E_MIN_ASTRA_TOO_NEW");
});

await test("E_MIN_ASTRA_INVALID — a requirement that requires nothing", async () => {
  const r = await run({ assets: [conformingAsset({ minAstraVersion: "nightly" })] });
  assertBlockedWith(r, "E_MIN_ASTRA_INVALID");
});

await test("E_PLATFORM_UNSUPPORTED — a host Astra ships no daemon for", async () => {
  const r = await run({ assets: [conformingAsset({ os: "macos" })] });
  assertBlockedWith(r, "E_PLATFORM_UNSUPPORTED");
});

// ═══════════════════════════════════════════════════════════════════════════

section("the card, in more than one language");

// Every case here is a real bundle through the real pipeline. The rules
// themselves are pinned against AstraPlugins/testdata/locales by
// tools/validate.mjs — that is coupling C16, and it is what stops the CLI and
// this repository refusing different things. What these tests add is the half a
// corpus cannot carry: that the rule reaches a submission at all, that the
// finding names the file the author has to open, and that what comes out is
// what a store renders.

/** A `locales/<code>.json` entry for `makeBundle`'s `extraFiles`. */
const locale = (code, keys) => ({
  name: `locales/${code}.json`,
  data: Buffer.from(JSON.stringify(keys, null, 2), "utf8"),
});
const EN_CARD = {
  "listing.name": "Dice Roller",
  "listing.description": "Rolls dice when you ask it to.",
};
const RU_CARD = {
  "listing.name": "Бросок костей",
  "listing.description": "Бросает кости, когда вы попросите.",
};

await test("a bundle's Russian card reaches the listing, and it is the only thing read out of locales/", async () => {
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", { ...EN_CARD, "action.roll.label": "Roll" }),
        locale("ru", { ...RU_CARD, "action.roll.label": "Бросить" }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assertEqual(r.derived.plugin.i18n.ru.name, "Бросок костей", "the Russian card name was not derived");
  assertEqual(r.derived.plugin.i18n.ru.summary, "Бросает кости, когда вы попросите.", "nor the summary");
  assertEqual(r.derived.plugin.i18n.en, undefined,
    "`en` must never be a key: the flat name and summary ARE the English, and a document that can " +
    "carry it twice will eventually carry two different versions of it");
  // **That assertion alone has no teeth**, and a mutation is what showed it: an
  // `en` block built from a conforming `en.json` is identical to the English
  // card and is dropped by the rule below it, so widening the loop to all ten
  // codes changed nothing here. The case where the two differ is the case that
  // can actually reach a store, so it is the one asserted.
  const disagreeing = deriveLocaleText({
    files: [{ name: "locales/en.json", bytes: Buffer.from(JSON.stringify({ ...EN_CARD, "listing.name": "Something Else" }), "utf8") }],
    facts: { name: "Dice Roller", description: "Rolls dice when you ask it to." },
    limits: loadPolicy(REPO_ROOT).limits,
    summarise,
  });
  assertEqual(disagreeing.i18n?.en, undefined,
    "English reached the i18n member as a second, disagreeing copy of the card it is supposed to be");
  assertEqual(JSON.stringify(Object.keys(r.derived.plugin.i18n.ru).sort()), '["name","summary"]',
    "the interface strings (action.roll.label) are the daemon's business, not the card's");
});

await test("a locale block is never half a block — the missing half comes from English", async () => {
  // **This test was wrong when it was first written, and a mutation is what
  // said so.** It used a German file carrying BOTH reserved keys, so the fill
  // it claimed to exercise never ran: deleting the fill left every assertion
  // green. The path that actually reaches it is a plugin whose `en.json`
  // declares only `listing.description` — parity then permits every other
  // locale to declare only that too, and a block would otherwise be emitted
  // with a summary and no name, which the schema's `required` refuses.
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", { "listing.description": "Rolls dice when you ask it to." }),
        locale("ru", { "listing.description": "Бросает кости, когда вы попросите." }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, `a half block reached the schema: ${JSON.stringify(errorCodes(r))}`);
  assertEqual(r.derived.plugin.i18n.ru.name, "Dice Roller",
    "the missing half must be filled from English, not left out of the block");
  assertEqual(r.derived.plugin.i18n.ru.summary, "Бросает кости, когда вы попросите.",
    "and the half that IS translated must survive the fill");
});

await test("…and a name identical to English is kept, because that is what a brand is", async () => {
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", EN_CARD),
        locale("de", { "listing.name": "Dice Roller", "listing.description": "Würfelt, wenn Sie fragen." }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assertEqual(r.derived.plugin.i18n.de.name, "Dice Roller", "a brand name repeated in another locale was dropped");
  assertEqual(r.derived.plugin.i18n.de.summary, "Würfelt, wenn Sie fragen.", "and the German summary with it");
});

await test("a long localized description is cut to the card line, by the same cut the English one gets", async () => {
  // `listing.description` may be up to 4,000 characters — it is the manifest's
  // description — and the card line is 200. The English one has always been
  // summarised; a locale block that was not would be refused by the schema and
  // the author would be told the registry has a bug.
  const long = `${"Бросает кости, когда вы попросите. ".repeat(20)}`;
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", { ...EN_CARD, "listing.description": "Rolls dice when you ask it to." }),
        locale("ru", { "listing.name": "Бросок костей", "listing.description": long }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, `an unsummarised locale block reached the schema: ${JSON.stringify(errorCodes(r))}`);
  const summary = r.derived.plugin.i18n.ru.summary;
  assert([...summary].length <= 200, `the Russian card line is ${[...summary].length} code points`);
  assert(summary.endsWith("…"), `and it must be marked as cut rather than merely short: ${JSON.stringify(summary)}`);
});

await test("a block that says exactly what the English card says is not emitted", async () => {
  const r = await run({
    assets: [conformingAsset({ extraFiles: [locale("en", EN_CARD), locale("fr", EN_CARD)] })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assertEqual(r.derived.plugin.i18n, undefined,
    "a French block identical to the English card renders identically to no block, and costs every user its bytes");
});

await test("E_LOCALE_NO_ENGLISH — translations with nothing to fall back to", async () => {
  const r = await run({ assets: [conformingAsset({ extraFiles: [locale("ru", RU_CARD)] })] });
  assertBlockedWith(r, "E_LOCALE_NO_ENGLISH");
});

await test("E_LOCALE_UNKNOWN_CODE — the region tag that exists nowhere in this system", async () => {
  // `zh-CN` is the spelling this project used in its own documentation tree for
  // months. Astra's Chinese is `zh`, matching is exact string equality, and a
  // file named anything else is packed, digested, signed, installed and read by
  // nothing, with no error at any point.
  const r = await run({
    assets: [conformingAsset({ extraFiles: [locale("en", EN_CARD), locale("zh-CN", EN_CARD)] })],
  });
  assertBlockedWith(r, "E_LOCALE_UNKNOWN_CODE");
  assertEqual(r.findings.find((i) => i.code === "E_LOCALE_UNKNOWN_CODE").where, "locales/zh-CN.json",
    "the finding must name the file, not the stage");
});

await test("E_LOCALE_MALFORMED — the nested shape the daemon drops whole, silently", async () => {
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [{
        name: "locales/en.json",
        data: Buffer.from(JSON.stringify({ listing: { name: "Dice Roller" } }), "utf8"),
      }],
    })],
  });
  assertBlockedWith(r, "E_LOCALE_MALFORMED");
});

await test("E_LOCALE_KEY_MISSING and E_LOCALE_KEY_EXTRA — parity, in both directions", async () => {
  const missing = await run({
    assets: [conformingAsset({
      extraFiles: [locale("en", { ...EN_CARD, greeting: "Hello" }), locale("ru", RU_CARD)],
    })],
  });
  assertBlockedWith(missing, "E_LOCALE_KEY_MISSING");

  const extra = await run({
    assets: [conformingAsset({
      extraFiles: [locale("en", EN_CARD), locale("ru", { ...RU_CARD, extra: "Лишний" })],
    })],
  });
  assertBlockedWith(extra, "E_LOCALE_KEY_EXTRA");
});

await test("parity is over plural FAMILIES, or it fires on a file the CLI itself wrote", async () => {
  // `astra-plugin locale add ru` writes `msg.done.few` and `msg.done.many`,
  // which `en.json` cannot legally contain. A raw-key parity rule would refuse
  // the bundle its own toolchain produced and recommended.
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", { ...EN_CARD, "msg.done.one": "Rolled {n} die", "msg.done.other": "Rolled {n} dice" }),
        locale("ru", {
          ...RU_CARD,
          "msg.done.one": "{n} бросок", "msg.done.few": "{n} броска",
          "msg.done.many": "{n} бросков", "msg.done.other": "{n} броска",
        }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, `the four Russian plural rows were refused: ${JSON.stringify(errorCodes(r))}`);
});

await test("E_LISTING_TEXT_MISMATCH — the card and the manifest saying two things", async () => {
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [locale("en", { ...EN_CARD, "listing.name": "Something Else" })],
    })],
  });
  assertBlockedWith(r, "E_LISTING_TEXT_MISMATCH");
});

await test("W_LOCALE_NO_CARD_TEXT — a plugin that translates its interface and not its card", async () => {
  const r = await run({
    assets: [conformingAsset({ extraFiles: [locale("en", { greeting: "Hello" }), locale("ru", { greeting: "Привет" })] })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assert(codes(r).includes("W_LOCALE_NO_CARD_TEXT"), JSON.stringify(codes(r)));
  assertEqual(r.derived.plugin.i18n, undefined, "nothing to put on a card is not something to put on a card");
});

await test("E_LISTING_NOT_ENGLISH — the failure this whole feature was filed from", async () => {
  // The live one, word for word: a listing published through the correct
  // zero-touch path, in Russian, because nothing in this system had ever asked
  // what language a listing was in.
  const r = await run({
    assets: [conformingAsset({
      description: "Шахматы против локального бота или выбранной модели Astra с игровым чатом.",
    })],
  });
  assertBlockedWith(r, "E_LISTING_NOT_ENGLISH");
  const message = r.findings.find((i) => i.code === "E_LISTING_NOT_ENGLISH").message;
  assert(message.includes("SCRIPT check"),
    "a gate that overstates its reach is one people route around: the message has to say it cannot tell English from French");
});

await test("…and an English sentence quoting a Russian word still passes", async () => {
  const r = await run({
    assets: [conformingAsset({ description: "Plays chess against a local bot. The UI button says Шахматы." })],
    root: registryWith({}),
  });
  assert(!errorCodes(r).includes("E_LISTING_NOT_ENGLISH"),
    `60% and not 100% is the whole point: ${JSON.stringify(errorCodes(r))}`);
});

await test("W_LISTING_NAME_NOT_LATIN — a product name is not prose, and is not left unobserved either", async () => {
  const r = await run({
    assets: [conformingAsset({ name: "Бросок костей" })],
    root: registryWith({}),
  });
  assert(!errorCodes(r).includes("W_LISTING_NAME_NOT_LATIN"), "a name must not block a release");
  assert(codes(r).includes("W_LISTING_NAME_NOT_LATIN"), JSON.stringify(codes(r)));
});

await test("E_TRADEMARK — an honest English card and an impersonating Russian one", async () => {
  // The hole that mattered most. `checkNames` ran exactly once, on the English
  // name out of plugin.toml, so a bundle whose en.json said `Dice Roller` and
  // whose ru.json said `Telegram` would have put a card named Telegram in front
  // of every Russian user — on a listing a human approved by reading a clean
  // English card.
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", EN_CARD),
        locale("ru", { "listing.name": "Telegram", "listing.description": "Бросает кости, когда вы попросите." }),
      ],
    })],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_TRADEMARK");
  assertEqual(r.findings.find((i) => i.code === "E_TRADEMARK").where, "locales/ru.json",
    "the finding has to name the language, or the author reads the English name and sees nothing wrong");
});

await test("R_DISPLAY_NAME_COLLISION — two cards that are the same card in Russian", async () => {
  const root = registryWith({
    id: "other-dice",
    name: "Something Else",
    i18n: { ru: { name: "Бросок костей", summary: "Кости." } },
  });
  const r = await run({
    assets: [conformingAsset({ extraFiles: [locale("en", EN_CARD), locale("ru", RU_CARD)] })],
    root,
  });
  assert(codes(r).includes("R_DISPLAY_NAME_COLLISION"),
    `a collision only a Russian user can see is still a collision: ${JSON.stringify(codes(r))}`);
});

await test("a Cyrillic name that borrows a Latin brand is not a homoglyph attack", async () => {
  // `Клиент Telegram` is what an honest Russian name for a third-party client
  // looks like. Flagging it would put every honest Cyrillic listing in a review
  // queue, which ends with the rule switched off inside a week.
  const r = await run({
    assets: [conformingAsset({
      id: "chat-bridge",
      name: "Chat Bridge",
      extraFiles: [
        locale("en", { "listing.name": "Chat Bridge", "listing.description": "Rolls dice when you ask it to." }),
        locale("ru", { "listing.name": "Мост Chat", "listing.description": "Бросает кости, когда вы попросите." }),
      ],
    })],
    root: registryWith({}),
  });
  assert(!codes(r).includes("R_DISPLAY_NAME_MIXED_SCRIPT"),
    `an honest Russian name was held for a human: ${JSON.stringify(codes(r))}`);
});

await test("W_LOCALE_STALE — a translation of English that has since been rewritten", async () => {
  // Debian's Description-md5, as a derived value: the lock records a digest of
  // the English each translation was made against. When it stops matching, the
  // string falls back to English rather than the release being refused —
  // showing a confidently wrong sentence in a language nobody here can
  // proof-read is worse than showing a correct one in the wrong language.
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", EN_CARD),
        locale("ru", RU_CARD),
        {
          name: "locales.lock.json",
          data: Buffer.from(JSON.stringify({
            schema: "astra.plugin.locales/1",
            source: "en",
            locales: { ru: { "listing.name": "0".repeat(12), "listing.description": "0".repeat(12) } },
          }), "utf8"),
        },
      ],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, `a stale translation must not refuse a release: ${JSON.stringify(errorCodes(r))}`);
  assert(codes(r).includes("W_LOCALE_STALE"), JSON.stringify(codes(r)));
  assertEqual(r.derived.plugin.i18n, undefined,
    "both strings demote to English, which leaves a block identical to the English card, which is not emitted");
});

await test("…and a lock that matches today's English is not stale", async () => {
  const digest = (s) => crypto.createHash("sha256").update(Buffer.from(s, "utf8")).digest("hex").slice(0, 12);
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", EN_CARD),
        locale("ru", RU_CARD),
        {
          name: "locales.lock.json",
          data: Buffer.from(JSON.stringify({
            schema: "astra.plugin.locales/1",
            source: "en",
            locales: {
              ru: {
                "listing.name": digest(EN_CARD["listing.name"]),
                "listing.description": digest(EN_CARD["listing.description"]),
              },
            },
          }), "utf8"),
        },
      ],
    })],
    root: registryWith({}),
  });
  assert(!codes(r).includes("W_LOCALE_STALE"),
    `the digests agree, so nothing is stale: ${JSON.stringify(codes(r))}`);
  assertEqual(r.derived.plugin.i18n.ru.name, "Бросок костей", "a fresh translation must survive");
});

await test("E_LOCALE_CARD_TOO_LONG — a name past the card's width, in one language", async () => {
  const r = await run({
    assets: [conformingAsset({
      extraFiles: [
        locale("en", EN_CARD),
        locale("ru", { "listing.name": "Б".repeat(70), "listing.description": "Бросает кости." }),
      ],
    })],
  });
  assertBlockedWith(r, "E_LOCALE_CARD_TOO_LONG");
});

await test("E_LOCALE_TOO_LARGE — refused before the parse, not after it", async () => {
  // inspectBundle materialises every listed file as a Buffer bounded only by
  // max_extract_bytes (500 MB). Icons are capped at 128 KiB and READMEs at
  // 16 KiB; locale files were capped by nothing, and a flat-but-valid 200 MB
  // en.json would take the ingest runner out mid-derivation and leave the
  // submitter's issue with no verdict at all.
  const fat = {};
  for (let i = 0; i < 400; i++) fat[`k${i}`] = "x".repeat(1024);
  const r = await run({
    assets: [conformingAsset({ extraFiles: [locale("en", { ...EN_CARD, ...fat })] })],
  });
  assertBlockedWith(r, "E_LOCALE_TOO_LARGE");
});

await test("E_LOCALE_BUNDLE_MISMATCH — one release, two platforms, two different cards", async () => {
  // `deriveListing` is handed the FIRST bundle's files, with a comment saying
  // the icon and the README are one picture across platforms. True for those.
  // False for locale files, which reach the installed plugin per platform.
  const r = await run({
    assets: [
      {
        name: "dice-roller-0.2.0-linux-x64.astraplugin",
        bytes: makeBundle({ os: "linux", extraFiles: [locale("en", EN_CARD), locale("ru", RU_CARD)] }),
      },
      {
        name: "dice-roller-0.2.0-windows-x64.astraplugin",
        bytes: makeBundle({
          os: "windows",
          extraFiles: [locale("en", EN_CARD), locale("ru", { ...RU_CARD, "listing.name": "Другое имя" })],
        }),
      },
    ],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_LOCALE_BUNDLE_MISMATCH");
});

await test("a plugin that ships no locales/ is not asked about any of this", async () => {
  const r = await run({ assets: [conformingAsset()], root: registryWith({}) });
  assert(!codes(r).some((c) => c.startsWith("E_LOCALE") || c.startsWith("W_LOCALE")),
    `the overwhelming majority of bundles, for ever: ${JSON.stringify(codes(r))}`);
});

await test("E_LOCALE_CARD_TOO_LARGE and the exemption note, at the unit they are decided in", async () => {
  // Two codes with no end-to-end fixture, and they are here rather than absent.
  // The budget needs nine locales of maximum-length CJK, which is a bundle
  // fixture testing arithmetic and nothing else; the exemption needs an entry in
  // the real policy/listing-language-exemptions.json, and a test that edits the
  // shipped policy file in order to prove the shipped policy file is read is a
  // test that can pass for the wrong reason.
  const limits = loadPolicy(REPO_ROOT).limits;
  const files = [{ name: "locales/en.json", bytes: Buffer.from(JSON.stringify(EN_CARD), "utf8") }];
  for (const code of ["ru", "uk", "de", "fr", "es", "pt", "ja", "zh", "ko"]) {
    files.push({
      name: `locales/${code}.json`,
      bytes: Buffer.from(JSON.stringify({
        "listing.name": "名".repeat(64),
        "listing.description": "説".repeat(200),
      }), "utf8"),
    });
  }
  const codesOf = (x) => x.findings.map((i) => i.code);
  const facts = { name: "Dice Roller", description: "Rolls dice when you ask it to." };

  // The rule, at a budget low enough to reach: the number is policy and the
  // mechanism is what this asserts.
  const over = deriveLocaleText({ files, facts, limits: { ...limits, max_listing_i18n_bytes: 512 }, summarise });
  assert(codesOf(over).includes("E_LOCALE_CARD_TOO_LARGE"),
    `the per-listing budget did not fire: ${JSON.stringify(codesOf(over))}`);
  assertEqual(over.i18n, undefined, "and nothing is emitted, rather than the budget being advisory");
  for (const i of over.findings) emitted.add(i.code);

  // And the shipped number, from the other side. **This is the assertion that
  // matters more**, because the way this ceiling goes wrong is not that it
  // fails to fire — it is that somebody lowers it and every honest CJK listing
  // starts losing its translations with a message about a budget. Nine locales
  // at the schema's own caps, in three-byte characters, is the worst case a
  // listing can legitimately reach.
  const worst = deriveLocaleText({ files, facts, limits, summarise });
  assert(!codesOf(worst).includes("E_LOCALE_CARD_TOO_LARGE"),
    "nine locales at 64 + 200 characters each satisfies every per-string cap and must not be refused by the total: " +
    `${Buffer.byteLength(JSON.stringify(worst.i18n ?? {}), "utf8")} bytes against a ceiling of ${limits.max_listing_i18n_bytes}`);
  assertEqual(Object.keys(worst.i18n ?? {}).length, 9, "the worst case must actually have been built");

  const exempt = deriveLocaleText({
    files: [],
    facts: { name: "Шахматы", description: "Шахматы против локального бота." },
    limits,
    summarise,
    languageExempt: true,
  });
  assert(!codesOf(exempt).includes("E_LISTING_NOT_ENGLISH"), "an exemption must actually excuse the rule");
  assert(codesOf(exempt).includes("N_LISTING_LANGUAGE_EXEMPT"),
    `and must say so rather than passing quietly: ${JSON.stringify(codesOf(exempt))}`);
  for (const i of exempt.findings) emitted.add(i.code);
});

// ═══════════════════════════════════════════════════════════════════════════

section("versions and identity");

await test("E_VERSION_NOT_NEW — republishing a version that is already listed", async () => {
  const r = await run({ assets: [conformingAsset()], root: registryWith({ version: "0.2.0" }) });
  assertBlockedWith(r, "E_VERSION_NOT_NEW");
});

await test("E_VERSION_NOT_NEW — a release that goes backwards", async () => {
  const r = await run({ assets: [conformingAsset({ version: "0.1.5" })], root: registryWith({ version: "0.3.0" }) });
  assertBlockedWith(r, "E_VERSION_NOT_NEW");
});

await test("E_VERSION_INCONSISTENT — one release, two versions", async () => {
  const r = await run({
    assets: [
      { name: "dice-roller-0.2.0-linux-x64.astraplugin", bytes: makeBundle({ os: "linux", version: "0.2.0" }) },
      { name: "dice-roller-0.2.1-windows-x64.astraplugin", bytes: makeBundle({ os: "windows", version: "0.2.1" }) },
    ],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_VERSION_INCONSISTENT");
});

await test("E_MANIFEST_ID_MISMATCH — one release carrying two different plugins", async () => {
  const r = await run({
    assets: [
      { name: "dice-roller-0.2.0-linux-x64.astraplugin", bytes: makeBundle({ os: "linux" }) },
      { name: "other-thing-0.2.0-windows-x64.astraplugin", bytes: makeBundle({ os: "windows", id: "other-thing", name: "Other Thing" }) },
    ],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_MANIFEST_ID_MISMATCH");
});

await test("R_IDENTITY_CHANGED — the same plugin from a different repository", async () => {
  const r = await run({ assets: [conformingAsset()], root: registryWith({ repo: "someone-else/dice-roller" }) });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assert(codes(r).includes("R_IDENTITY_CHANGED"), JSON.stringify(codes(r)));
});

section("the host-RPC heuristic");

await test("E_HOST_RPC_UNDECLARED — author source calling one of the four", async () => {
  const r = await run({
    assets: [conformingAsset({
      capabilities: ["tools"],
      extraFiles: [{ name: "handler.py", data: "def go(host):\n    host.FireTrigger('x')\n" }],
    })],
    root: registryWith({}),
  });
  assertBlockedWith(r, "E_HOST_RPC_UNDECLARED");
});

await test("…and declaring the capability makes it legitimate", async () => {
  const r = await run({
    assets: [conformingAsset({
      capabilities: ["tools", "triggers"],
      extraFiles: [{ name: "handler.py", data: "def go(host):\n    host.FireTrigger('x')\n" }],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
});

await test("W_HOST_RPC_UNDECLARED — the rest warn instead of blocking", async () => {
  const r = await run({
    assets: [conformingAsset({
      capabilities: ["tools"],
      extraFiles: [{ name: "handler.py", data: "host.PushToUi({})\n" }],
    })],
    root: registryWith({}),
  });
  assert(!r.blocked, JSON.stringify(errorCodes(r)));
  assert(codes(r).includes("W_HOST_RPC_UNDECLARED"), JSON.stringify(codes(r)));
});

await test("a vendored SDK stub is not evidence of anything", () => {
  const findings = scanHostRpcs(
    [{ name: "site-packages/astra_plugin_sdk/plugin_pb2.py", bytes: Buffer.from("FireTrigger SetVariable SendChatMessage") }],
    { capabilities: ["tools"], permissions: {} },
  );
  assert(!findings.some((i) => i.level === "error"),
    `the Python SDK's descriptor names every method of every service: ${JSON.stringify(findings)}`);
  for (const i of findings) emitted.add(i.code);
});

await test("a compiled file is reported, never held against the author", () => {
  const findings = scanHostRpcs(
    [{ name: "bin/plugin", bytes: Buffer.concat([Buffer.from([0, 1, 2]), Buffer.from("FireTrigger")]) }],
    { capabilities: ["tools"], permissions: {} },
  );
  assert(findings.some((i) => i.code === "W_HOST_RPC_IN_OPAQUE_FILE"), JSON.stringify(findings));
  assert(!findings.some((i) => i.level === "error"), "a linked client carries every method name");
  for (const i of findings) emitted.add(i.code);
});

await test("the scan's scope is printed on every run, passing or not", () => {
  const findings = scanHostRpcs([], { capabilities: [], permissions: {} });
  assert(findings.some((i) => i.code === "N_HOST_RPC_SCAN_SCOPE"),
    "a checklist that shows only what passed reads as a clean bill of health");
});

await test("classifyFile puts each kind of file in the right bucket", () => {
  assertEqual(classifyFile("src/index.js", Buffer.from("x")), "source", "author source");
  assertEqual(classifyFile("node_modules/x/index.js", Buffer.from("x")), "vendored", "somebody else's source");
  assertEqual(classifyFile("bin/plugin", Buffer.from([0, 1, 2])), "opaque", "a compiled file");
  assertEqual(classifyFile("LICENSE", Buffer.from("MIT")), "source", "text with no extension is still text");
  assertEqual(classifyFile("generated/evil.py", Buffer.from("x")), "weak-vendor",
    "a directory name the bundle author chose is not evidence of a toolchain");
  assertEqual(classifyFile("vendor/evil.py", Buffer.from("x")), "weak-vendor", "same");
});

await test("renaming a directory does not turn the scan off", () => {
  // The hole: `generated/` and `vendor/` were silent skips, and both are
  // directory names the bundle author picks. The identical file produced
  // E_HOST_RPC_UNDECLARED at `src/evil.py` and NOTHING at `generated/evil.py`,
  // where it published unattended — and the note row reported it as somebody
  // else's code.
  const evil = Buffer.from("host.SendChatMessage(x)\nhost.SetThemeContribution(y)\n");
  const declared = { capabilities: [], permissions: {} };

  const inSrc = scanHostRpcs([{ name: "src/evil.py", bytes: evil }], declared);
  assert(inSrc.some((i) => i.code === "E_HOST_RPC_UNDECLARED"), JSON.stringify(inSrc));

  for (const dir of ["generated", "vendor"]) {
    const found = scanHostRpcs([{ name: `${dir}/evil.py`, bytes: evil }], declared);
    for (const i of found) emitted.add(i.code);
    assert(found.some((i) => i.code === "R_HOST_RPC_IN_VENDOR_DIR"),
      `${dir}/ must still be searched: ${JSON.stringify(found)}`);
    // `review` and not `warn`: policy.mjs holds on review and publishes through
    // everything softer, so a warn would leave the bypass in place.
    assert(found.some((i) => i.level === "review"), JSON.stringify(found));
    const note = found.find((i) => i.code === "N_HOST_RPC_SCAN_SCOPE");
    assert(!note.message.includes("skipped:"), `nothing was skipped: ${note.message}`);
  }
});

await test("node_modules is believed only when the bundle corroborates it", () => {
  const evil = Buffer.from("host.FireTrigger('x')\n");
  const declared = { capabilities: [], permissions: {} };

  // A lone `node_modules/` with no package metadata anywhere: the author's own
  // code under somebody else's directory name.
  const bare = scanHostRpcs([{ name: "node_modules/evil/index.js", bytes: evil }], declared);
  assert(bare.some((i) => i.code === "E_HOST_RPC_UNDECLARED"), JSON.stringify(bare));

  // The same file beside a `package.json`, which is what a package manager
  // actually writes.
  const real = scanHostRpcs([
    { name: "node_modules/evil/package.json", bytes: Buffer.from("{}") },
    { name: "node_modules/evil/index.js", bytes: evil },
  ], declared);
  assert(!real.some((i) => i.level === "error"), JSON.stringify(real));
});

await test("N_HOST_RPC_SCAN_SCOPE names what it skipped, it does not just count it", () => {
  const found = scanHostRpcs([
    { name: "site-packages/sdk/plugin_pb2.py", bytes: Buffer.from("FireTrigger") },
    { name: "src/main.py", bytes: Buffer.from("print(1)") },
  ], { capabilities: ["tools"], permissions: {} });
  const note = found.find((i) => i.code === "N_HOST_RPC_SCAN_SCOPE");
  assert(note.message.includes("site-packages/sdk/plugin_pb2.py"),
    `a count reads as somebody else's code whatever the files are: ${note.message}`);
});

await test("[permissions] satisfies the scan too, so Phase 4 does not break this check", () => {
  const findings = scanHostRpcs(
    [{ name: "handler.py", bytes: Buffer.from("host.FireTrigger()") }],
    { capabilities: [], permissions: { fire_trigger: { reason: "…" } } },
  );
  assert(!findings.some((i) => i.level === "error"), JSON.stringify(findings));
});

section("ownership, in detail");

// The world every one of these is about, observed in a real Actions run on
// 2026-08-14 against `astra-registry#13` and `#14`: every cryptographic check
// passed and the submission was refused on ownership alone, because the fast
// path answered 403 (the bot's token belongs to `astra-registry`, and GitHub
// will not disclose a third party's collaborators to it) and the release had
// been published by `@github-actions[bot]`, which is what the documented
// `plugin-release.yml` does. Neither arm can fire for an honest first
// submission, so the file has to be the thing an author is asked for — and the
// refusal has to lead with it.

const RECENT_RELEASE = new Date(Date.now() - 3 * 86_400_000).toISOString();

/** A world where the bot can see nothing and the file does not exist. */
const blind = async (url) => ({ ok: false, status: url.includes("/collaborators/") ? 403 : 404 });

await test("a 403 from the fast path is not a refusal by itself", async () => {
  // The whole defect, in one assertion: 403 means "the bot cannot see", and the
  // run has to carry on to the proof the author was actually asked for.
  const out = await proveOwnership({
    repo: "org/thing", login: "someone", releaseAuthor: null, token: null,
    fetchImpl: async (url) =>
      url.includes("/collaborators/")
        ? { ok: false, status: 403 }
        : { ok: true, status: 200, text: async () => "someone\n" },
  });
  assert(out.ok, `a 403 must not decide anything: ${JSON.stringify(out)}`);
  assertEqual(out.method, "well-known", JSON.stringify(out.tried));
});

await test("a 403 is never reported to the author as a finding against them", async () => {
  const out = await proveOwnership({
    repo: "org/thing", login: "someone", releaseAuthor: "github-actions[bot]",
    releasePublishedAt: RECENT_RELEASE, token: null, fetchImpl: blind,
  });
  assert(!out.ok, "with no file there is nothing to grant on");
  assert(!/403/.test(out.detail),
    `a 403 is a fact about the bot's token, not about the submitter: ${out.detail}`);
  assert(!/collaborator-permission/.test(out.detail),
    `nor is the name of a check the author cannot influence: ${out.detail}`);
  // It stays in the audit trail, which is where "how did this get decided"
  // is answered — just not in the comment a stranger reads.
  assert(out.tried.some((t) => t.method === "collaborator-permission" && /403/.test(t.outcome)),
    JSON.stringify(out.tried));
});

await test("a 403 plus a release published by CI is the real #13/#14 case", async () => {
  const out = await proveOwnership({
    repo: "Rel0d1x/command-intent-guard", login: "Rel0d1x",
    releaseAuthor: "github-actions[bot]", releasePublishedAt: RECENT_RELEASE,
    token: null, fetchImpl: blind,
  });
  assert(!out.ok, JSON.stringify(out));
  // Not "three checks failed". One instruction, first, naming the exact path.
  assert(out.detail.startsWith("**Commit `.well-known/astra-plugin-owner`"), out.detail);
  assert(out.detail.includes("Rel0d1x/command-intent-guard's default branch"), out.detail);
  assert(out.detail.includes("`Rel0d1x`"), "and the exact line to put in it");
  assert(out.detail.includes("/recheck"), "and how to run it again");
  assert(!/github-actions/.test(out.detail),
    `who pressed the button in CI is not something the author can act on: ${out.detail}`);
});

await test("the missing-file refusal says the file is missing, not that the author is", async () => {
  const out = await proveOwnership({
    repo: "org/thing", login: "someone", releaseAuthor: null, token: null, fetchImpl: blind,
  });
  assert(out.detail.includes("there is no `.well-known/astra-plugin-owner` on that branch (HTTP 404)"),
    out.detail);
});

await test("a file naming somebody else refuses, and prints who it does name", async () => {
  // The typo case. `Rel0dlx` and `Rel0d1x` differ by one glyph, and the whole
  // point of printing the file's contents is that the author can see it.
  const out = await proveOwnership({
    repo: "org/thing", login: "Rel0d1x", releaseAuthor: null, token: null,
    fetchImpl: async (url) =>
      url.includes("/collaborators/")
        ? { ok: false, status: 403 }
        : { ok: true, status: 200, text: async () => "# owners\nRel0dlx\n" },
  });
  assert(!out.ok, "a file that names somebody else proves nothing about this submitter");
  assertEqual(out.method, null, JSON.stringify(out.tried));
  assert(out.detail.includes("`Rel0dlx`"), `it has to show what the file says: ${out.detail}`);
  assert(out.detail.startsWith("**Commit `.well-known/astra-plugin-owner`"), out.detail);
});

await test("a stranger cannot list a repository whose file does not name them", async () => {
  // The property the whole check exists for, stated as a test rather than as a
  // comment: the file is on the victim's default branch, and mallory is not in
  // it. Nothing else in the pipeline asks this question.
  const out = await proveOwnership({
    repo: "victim/plugin", login: "mallory", releaseAuthor: "victim",
    releasePublishedAt: RECENT_RELEASE, token: null,
    fetchImpl: async (url) =>
      url.includes("/collaborators/")
        ? { ok: false, status: 403 }
        : { ok: true, status: 200, text: async () => "victim\n" },
  });
  assert(!out.ok, JSON.stringify(out));
});

await test("the file is compared case-insensitively, and `@` and comments are forgiven", async () => {
  const out = await proveOwnership({
    repo: "org/thing", login: "SomeOne", releaseAuthor: null, token: null,
    fetchImpl: async (url) =>
      url.includes("/collaborators/")
        ? { ok: false, status: 403 }
        : { ok: true, status: 200, text: async () => "# who may list this\n@someone   # the author\n" },
  });
  assert(out.ok && out.method === "well-known", JSON.stringify(out));
});

await test("a 403 with no file still lets a release ping through, which is what carries every later release", async () => {
  // `resolveSubmitter` (bot/lib/notify.mjs) makes the submitter the release's
  // own author on the ping and backstop paths, so this arm is the only one that
  // can answer there. It is circular and says so; what protects that path is the
  // pin — a ping may only name a repository that is already listed.
  const out = await proveOwnership({
    repo: "org/thing", login: "someone", releaseAuthor: "someone",
    releasePublishedAt: RECENT_RELEASE, token: null, fetchImpl: blind,
  });
  assert(out.ok, "an already-listed plugin must keep releasing with nobody in the loop");
  assertEqual(out.method, "release-author", JSON.stringify(out.tried));
});

await test("a 200 saying `write` is a DENIAL, and the owner file does not get a vote", async () => {
  // The one place the owner file does NOT win, and the reason is the same
  // reason a 403 does not lose: GitHub answering and GitHub declining are
  // different facts. Here it answered — about this person, on this repository,
  // just now — and said `write`. The file speaks where GitHub will not; it does
  // not overrule GitHub where it will, or a contributor could add themselves in
  // a pull request and outrank an explicit non-maintainer role.
  const out = await proveOwnership({
    repo: "victim/plugin", login: "mallory", releaseAuthor: "mallory",
    releasePublishedAt: RECENT_RELEASE, token: null,
    fetchImpl: async (url) => {
      if (url.includes("/collaborators/")) {
        return { ok: true, status: 200, json: async () => ({ role_name: "write" }) };
      }
      // A file listing mallory, and a release mallory published. Neither may win.
      if (url.includes("well-known")) return { ok: true, status: 200, text: async () => "mallory\n" };
      return { ok: false, status: 404 };
    },
  });
  assert(!out.ok, `an explicit non-owner role must end it: ${JSON.stringify(out)}`);
  assertEqual(out.method, null, JSON.stringify(out.tried));
  assertEqual(out.tried.length, 1, "and the weaker checks are not even run: " + JSON.stringify(out.tried));
});

await test("a 200 saying `none` is a denial too — the removed collaborator case", async () => {
  const out = await proveOwnership({
    repo: "victim/plugin", login: "mallory", releaseAuthor: "mallory",
    releasePublishedAt: RECENT_RELEASE, token: null,
    fetchImpl: async (url) =>
      url.includes("/collaborators/")
        ? { ok: true, status: 200, json: async () => ({ role_name: "none" }) }
        : { ok: true, status: 200, text: async () => "mallory\n" },
  });
  assert(!out.ok, JSON.stringify(out));
});

await test("release-author expires — a permanent fact must not be permanent access", async () => {
  // The module's own header rejects a challenge file because it "survives the
  // author being removed from the organisation". Method 3 did exactly that: an
  // ex-collaborator could still get their pre-removal release listed. It is now
  // capped, so the claim it makes is "they had access recently" rather than
  // "they had access once".
  const stale = new Date(Date.now() - 400 * 86_400_000).toISOString();
  const answer = async (url) => ({ ok: false, status: url.includes("/collaborators/") ? 403 : 404 });
  const fresh = await proveOwnership({
    repo: "org/thing", login: "x", releaseAuthor: "x", releasePublishedAt: RECENT_RELEASE,
    token: null, fetchImpl: answer,
  });
  assert(fresh.ok && fresh.method === "release-author", JSON.stringify(fresh));
  const old = await proveOwnership({
    repo: "org/thing", login: "x", releaseAuthor: "x", releasePublishedAt: stale,
    token: null, fetchImpl: answer,
  });
  assert(!old.ok, `a 400-day-old release is not proof of current access: ${JSON.stringify(old)}`);
  assert(old.detail.includes("400 days ago"), old.detail);
  assert(old.tried.some((t) => t.method === "release-author" && t.outcome.includes("400 days old")),
    JSON.stringify(old.tried));
  // Even here the refusal leads with the fix rather than with the expiry.
  assert(old.detail.startsWith("**Commit `.well-known/astra-plugin-owner`"), old.detail);
});

await test("maintain counts, write does not", async () => {
  const answer = (role) => async (url) =>
    url.includes("/collaborators/")
      ? { ok: true, status: 200, json: async () => ({ role_name: role }) }
      : { ok: false, status: 404 };
  const maintain = await proveOwnership({ repo: "o/r", login: "u", fetchImpl: answer("maintain") });
  assert(maintain.ok && maintain.method === "collaborator-permission", JSON.stringify(maintain));
  const write = await proveOwnership({ repo: "o/r", login: "u", fetchImpl: answer("write") });
  assert(!write.ok, "push access is not maintainership");
});

await test("the owner file is read, not claimed", async () => {
  const out = await proveOwnership({
    repo: "org/thing", login: "someone", releaseAuthor: "nobody",
    fetchImpl: async (url) =>
      url.includes(".well-known/astra-plugin-owner")
        ? { ok: true, status: 200, text: async () => "# owners\n@someone\nother\n" }
        : { ok: false, status: 404 },
  });
  assert(out.ok && out.method === "well-known", JSON.stringify(out));
  assert(out.detail.includes("read live on this run"),
    `and the run says so, because live reading is what makes removal a revocation: ${out.detail}`);
});

// ── the loop, closed at the source ──────────────────────────────────────────
//
// The refusal is now useful, but the point of the exercise is that an honest
// author never sees it. That means three files have to name the same path, and
// nothing but a test keeps them agreeing.

await test("the submission form asks for the file, with the exact path, before the submission", () => {
  const form = fs.readFileSync(
    path.join(REPO_ROOT, ".github", "ISSUE_TEMPLATE", "plugin-listing.yml"), "utf8");
  assert(form.includes(".well-known/astra-plugin-owner"),
    "the form must name the file an author is refused for not having");
  assert(/echo YOUR-GITHUB-LOGIN > \.well-known\/astra-plugin-owner/.test(form),
    "and give the line that creates it, so it is a copy rather than a translation");
  assert(/one commit/i.test(form), "and say what it costs");
  // A required confirmation, not a paragraph somebody scrolls past.
  const confirmations = [...form.matchAll(/- label: ([\s\S]*?)\n\s+required: true/g)].map((m) => m[1]);
  assert(confirmations.some((c) => c.includes(".well-known/astra-plugin-owner")),
    `the owner file has to be one of the required confirmations: ${JSON.stringify(confirmations)}`);
  // `bot/lib/issue.mjs` reads every `- [ ]` line in the rendered body and
  // `bot/lib/intake.mjs` refuses an unticked one, so adding it here needs no
  // parser change — but a prose block that is not a checkbox would be read by
  // nothing at all.
});

await test("the fixed remedy and the run's own message name the same file", () => {
  const remedy = codeDef("E_OWNERSHIP_UNPROVEN").remedy;
  assert(remedy.startsWith("Commit `.well-known/astra-plugin-owner`"),
    `the remedy has to lead with the fix, not with the diagnosis: ${remedy}`);
  assert(remedy.includes("/recheck"), remedy);
  assert(/write access, not of legal ownership/.test(remedy),
    "and be honest about what the file proves");
});

section("the submission form");

const ISSUE_BODY = [
  "### Source repository", "", "you/dice-roller", "",
  "### Release tag carrying the .astraplugin assets", "", "v0.2.0", "",
  "### What does it do, and why should it be listed?", "", "It rolls dice.", "",
  "### Confirmations", "",
  "- [X] I own or maintain this repository.",
  "- [X] I have read POLICY.md, including the data-handling section.",
].join("\n");

await test("the two facts come out of the rendered form", () => {
  const parsed = parseIssueForm(ISSUE_BODY);
  assertEqual(parsed.repo, "you/dice-roller", "the repository");
  assertEqual(parsed.tag, "v0.2.0", "the tag");
  assertEqual(parsed.confirmations.filter((c) => c.checked).length, 2, "both confirmations");
});

await test("a pasted URL, a stray @ and backticks are all the same repository", () => {
  const body = ISSUE_BODY.replace("you/dice-roller", "`https://github.com/you/dice-roller.git/`");
  assertEqual(parseIssueForm(body).repo, "you/dice-roller", "people paste the address bar");
});

await test("an unfilled optional field is not a value", () => {
  const body = ISSUE_BODY.replace("It rolls dice.", "_No response_");
  assertEqual(parseIssueForm(body).why, null, "`_No response_` is GitHub's placeholder, not prose");
});

await test("a form with no tag yields no tag, rather than a plausible one", () => {
  const body = ISSUE_BODY.replace("### Release tag carrying the .astraplugin assets\n\nv0.2.0\n\n", "");
  assertEqual(parseIssueForm(body).tag, null, "missing must read as missing");
});

await test("/recheck is a command only when it is the whole line", () => {
  assert(isRecheckCommand("/recheck"), "the command");
  assert(isRecheckCommand("  /RECHECK  "), "case and spacing do not matter");
  assert(!isRecheckCommand("I think you should /recheck this"), "a mention is not a command");
});

section("the comment a stranger reads");

await test("every blocking finding is followed by what to do about it", async () => {
  // Same licence as the check above, and for the same reason: it has to be one
  // the allowlist really refuses, or this asserts the text of a finding that
  // never happens.
  const r = await run({ assets: [conformingAsset({ license: "BUSL-1.1" })] });
  assert(r.comment.includes("E_LICENSE_NOT_ALLOWED"), "the code is in the comment");
  assert(r.comment.includes(codeDef("E_LICENSE_NOT_ALLOWED").remedy.slice(0, 40)),
    "and so is the sentence that says what to do");
  assert(r.comment.includes("### What to do"), "under a heading somebody will read");
});

await test("a clean run says what was not checked, not just what passed", async () => {
  const r = await run({ assets: [conformingAsset()], root: registryWith({}) });
  assert(r.comment.includes("N_HOST_RPC_SCAN_SCOPE"), "the heuristic's scope is on every report");
  assert(r.comment.includes("what none of them prove"), "and the report points at the document that says so");
});

await test("docs/BOT-CHECKS.md describes exactly the codes that exist", async () => {
  const { execFileSync } = await import("node:child_process");
  execFileSync(process.execPath, [path.join(REPO_ROOT, "bot", "gen-checks-doc.mjs"), "--check"],
    { cwd: REPO_ROOT, stdio: "pipe" });
});

await test("no code reaches a comment without a declaration behind it", () => {
  const undeclared = [...emitted].filter((c) => !Object.hasOwn(CODES, c));
  assertEqual(undeclared.join(", "), "",
    "every code the bot can emit must be in bot/lib/codes.mjs with a title and a remedy");
  // The reverse direction is a warning rather than a failure: codes for
  // failure classes that are hard to provoke (a corrupt central directory, a
  // derived listing this repository's own validator rejects) are declared and
  // documented before they are ever seen in the wild.
  const unseen = Object.keys(CODES).filter((c) => !emitted.has(c));
  console.log(`        ${emitted.size}/${Object.keys(CODES).length} codes exercised; not yet provoked: ${unseen.join(", ") || "none"}`);
});

// ── result ──────────────────────────────────────────────────────────────────

console.log();
if (failures.length) {
  console.log(`FAIL  ${passed} passed, ${failures.length} failed`);
  process.exit(1);
}
console.log(`PASS  ${passed} passed, 0 failed`);
