#!/usr/bin/env node
// The publication policy's own suite.  `node bot/tests/policy.test.mjs`
//
// Task 3.5's acceptance is one sentence — *"a normal patch release is live
// without a human; a `dom_access` request is not"* — and both halves are the
// first two tests below, run through the **whole** pipeline against the bot's
// fixture corpus: a real bundle, a real archive walk, the real manifest probe,
// the real derivation, and then the policy. Asserting the policy function in
// isolation would prove that `decide()` returns what `decide()` returns; these
// prove that a release does or does not reach the catalogue.
//
// Everything else here exists because the interesting half of this task is not
// the happy path. A delay that never ends, a queue entry that republishes a
// release the checks have since started refusing, a clock that a swapped asset
// can wait out — each of those is a way for "zero-touch" to mean "unsupervised
// and wrong", and each has a test.
//
// Nothing touches the network.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { decideRelease, writeOutputs } from "../decide.mjs";
import { DEFAULT_SIGNER_WORKFLOW } from "../ingest.mjs";
import {
  CLEAN_RELEASES_FOR_TRUSTED,
  DELAY_HOURS,
  HIGH_RISK,
  POLICY_CODES,
  REVIEW_SLA_HOURS,
  TRUSTED_DELAY_HOURS,
  decide,
  queueFile,
  readQueue,
  requestedAuthority,
  slaReport,
  trackRecord,
} from "../lib/policy.mjs";
import { proveMaintainer } from "../lib/maintainer.mjs";
import {
  WATCH_AFTER_DAYS,
  findListingByRepo,
  newReleases,
  parseReleasePing,
  parseReleasesAtom,
  watchPlan,
} from "../lib/notify.mjs";
import { pollFeed, runDrain, runWatch } from "../watch.mjs";
import { triage } from "../triage.mjs";
import { makeBundle, fakeGitHub, fakeGh, fakeOwnership } from "../fixtures/ingest/make.mjs";
import { loadSources } from "../../tools/lib/sources.mjs";

const REPO_ROOT = path.resolve(fileURLToPath(new URL("../..", import.meta.url)));

/** `loadSources`, named for what the assertions below are actually asking. */
const requireSources = (root) => loadSources(root);

// ── harness ─────────────────────────────────────────────────────────────────

let passed = 0;
const failures = [];
let group = "";
function section(name) { group = name; console.log(`\n${name}`); }
async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok    ${name}`);
  } catch (e) {
    failures.push({ group, name, error: e });
    console.log(`  FAIL  ${name}\n        ${e.message.split("\n").join("\n        ")}`);
  }
}
function assert(cond, message) { if (!cond) throw new Error(message); }
function assertEqual(actual, expected, message) {
  if (actual !== expected) throw new Error(`${message}\n  expected: ${expected}\n  actual:   ${actual}`);
}

const scratch = [];
process.on("exit", () => { for (const d of scratch) fs.rmSync(d, { recursive: true, force: true }); });
function tmp(prefix) {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  scratch.push(d);
  return d;
}

// ── the world ───────────────────────────────────────────────────────────────

const REPO = "a-stranger/dice-roller";
/** This registry itself — what a maintainer's permission is checked against. */
const REGISTRY_REPO = "mihailinl/astra-registry";
const TAG = "v0.2.0";
const SUBMITTER = "a-stranger";
const ALLOWED_WORKFLOW_SHA = "0".repeat(40);
const NOW = new Date("2026-08-10T12:00:00Z");

function testRootsFile() {
  const keys = ["root-a", "root-b"].map((n) =>
    JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "tools", "testkeys", `TEST-ONLY-DO-NOT-TRUST-${n}.pub.json`), "utf8")));
  const file = path.join(tmp("astra-policy-roots-"), "root.json");
  fs.writeFileSync(file, JSON.stringify({
    $banner: "TEST ROOTS — generated by bot/tests/policy.test.mjs, never committed, never trusted by a daemon.",
    schema: "astra.registry.root/1",
    status: "provisioned",
    roots: keys.map((k) => ({ key_id: k.key_id, public_key: k.public_key, role: k.role })),
  }, null, 2));
  return file;
}
const ROOTS_FILE = testRootsFile();
const TRUST_FILE = path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-active-signed.json");

/**
 * A registry tree, written from a description.
 *
 * `staging: false` matters here in a way it does not in the ingest suite: a
 * staging entry is not a clean release (nobody could verify its artifact), so
 * the graduation test has to write listings that carry digests.
 */
function registryTree(specs) {
  const dir = tmp("astra-policy-reg-");
  for (const spec of specs) {
    const id = spec.id ?? "dice-roller";
    const repo = spec.repo ?? REPO;
    const pdir = path.join(dir, "plugins", id, "versions");
    fs.mkdirSync(pdir, { recursive: true });
    fs.writeFileSync(path.join(dir, "plugins", id, "plugin.json"), `${JSON.stringify({
      schema: "astra.registry.plugin/1",
      id,
      // Derived from the id unless a test says otherwise. Two fixture listings
      // sharing one display name is now a finding in its own right
      // (R_DISPLAY_NAME_COLLISION covers the byte-identical case), and a
      // fixture that trips a real rule by accident tests the wrong thing.
      name: spec.name ?? (id === "dice-roller" ? "Dice Roller" : id),
      summary: "Rolls dice when you ask it to.",
      license: "MIT",
      source: { kind: "github", repo },
      added_at: "2026-01-01",
      ...(spec.unlisted ? { unlisted: true } : {}),
    }, null, 2)}\n`);
    for (const v of spec.versions ?? [{ version: "0.1.0" }]) {
      const staging = v.staging ?? true;
      fs.writeFileSync(path.join(pdir, `${v.version}.json`), `${JSON.stringify({
        schema: "astra.registry.version/1",
        id,
        version: v.version,
        published_at: v.published_at ?? "2026-01-01T00:00:00Z",
        release: { kind: "github_release", repo, tag: v.tag ?? `v${v.version}` },
        ...(staging
          ? { staging: true, staging_reason: "Test fixture: the release this points at is a fake." }
          : {}),
        // Always recorded, the way `bot/lib/derive.mjs` records it: a listing
        // that predates capability recording reads as "asks for nothing",
        // which makes its next release look like a widening. That is a
        // one-off 24 h delay per legacy listing and it fails safe, but a
        // fixture that reproduced it in every test would be measuring the
        // fixture rather than the policy.
        capabilities: v.capabilities ?? ["tools"],
        ...(v.permissions ? { permissions: v.permissions } : {}),
        artifacts: {
          "linux-x64": {
            url: `https://github.com/${repo}/releases/download/v${v.version}/${id}-${v.version}-linux-x64.astraplugin`,
            filename: `${id}-${v.version}-linux-x64.astraplugin`,
            ...(staging ? {} : { sha256: "b".repeat(64), size: 1024 }),
          },
        },
      }, null, 2)}\n`);
    }
  }
  return dir;
}

const bundleName = (spec = {}) =>
  `${spec.id ?? "dice-roller"}-${spec.version ?? "0.2.0"}-${spec.os === "windows" ? "windows-x64" : "linux-x64"}.astraplugin`;
const conforming = (spec = {}) => ({ name: bundleName(spec), bytes: makeBundle(spec) });

/** One ingest-and-decide against a world assembled from the arguments. */
async function run({
  assets = [conforming()], repo = REPO, tag = TAG, submitter = SUBMITTER, root,
  now = NOW, out = null, issue = null, approvedBy = null, approvedAt = null,
} = {}) {
  const github = fakeGitHub({ repo, tag, assets });
  return decideRelease(
    {
      repo, tag, submitter, root, issue, now, approvedBy, approvedAt,
      rootsFile: ROOTS_FILE, trustFile: TRUST_FILE, signerWorkflow: DEFAULT_SIGNER_WORKFLOW,
      out,
    },
    {
      fetchRelease: github.fetchRelease.bind(github),
      headAsset: github.headAsset.bind(github),
      downloadAsset: github.downloadAsset.bind(github),
      proveOwnership: fakeOwnership(true),
      ghRunner: (args) => fakeGh({
        repo,
        signerDigest: ALLOWED_WORKFLOW_SHA,
        subjectDigest: crypto.createHash("sha256").update(fs.readFileSync(args[2])).digest("hex"),
      })(args),
    },
  );
}

const codes = (r) => r.decision.reasons.map((x) => x.code);
const hours = (a, b) => Math.round((new Date(a).getTime() - new Date(b).getTime()) / 3600000);

// ═══════════════════════════════════════════════════════════════════════════

section("the acceptance criterion, end to end");

await test("a normal patch release goes live with no human", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0" }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root });
  assertEqual(r.decision.outcome, "publish",
    `${JSON.stringify(r.findings.filter((f) => f.level === "error" || f.level === "review"))} / ${JSON.stringify(r.decision.reasons)}`);
  assert(r.decision.publishes_now, "and it publishes on this run, not a later one");
  assertEqual(r.decision.publish_after, null, "nothing to wait for");
  assert(codes(r).includes("P_PUBLISHED"), JSON.stringify(codes(r)));

  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assert(fs.existsSync(path.join(out, "plugins", "dice-roller", "versions", "0.2.0.json")),
    "the listing the publish job commits is on disk");
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8"), "", "nothing to delete");
  assert(r.comment.includes("**Published.**"), "and the author is told, in the comment, in those words");
});

await test("a dom_access request does not", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "dom_access"] })] });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_NEW_HIGH_RISK"), JSON.stringify(codes(r)));
  assert(!r.decision.publishes_now, "nothing publishes");
  assertEqual(hours(r.decision.sla_deadline, NOW), REVIEW_SLA_HOURS, "and the author is given the deadline");

  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assert(!fs.existsSync(path.join(out, "plugins")), "no listing is produced for a held release");
  assert(r.comment.includes("R_NEW_HIGH_RISK"), "the comment names the reason");
  assert(r.comment.includes(POLICY_CODES.R_NEW_HIGH_RISK.remedy.slice(0, 40)),
    "…and says what to do about it");
});

section("the three events that block on a person, and nothing else");

await test("a first listing blocks, and says it is the only time", async () => {
  const r = await run({ root: registryTree([{ id: "something-else" }]) });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_FIRST_LISTING"), JSON.stringify(codes(r)));
});

await test("a repository change blocks", async () => {
  const r = await run({ root: registryTree([{ repo: "someone-else/dice-roller" }]) });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_IDENTITY_CHANGED"), JSON.stringify(codes(r)));
});

await test("a first listing that also wants dom_access says it once, not twice", async () => {
  const r = await run({
    root: registryTree([{ id: "something-else" }]),
    assets: [conforming({ capabilities: ["tools", "dom_access"] })],
  });
  assertEqual(r.decision.outcome, "review", "");
  assert(codes(r).includes("R_FIRST_LISTING"), JSON.stringify(codes(r)));
  assert(!codes(r).includes("R_NEW_HIGH_RISK"),
    "a human is already reading it; a second row saying so tells them nothing");
});

await test("a check the bot cannot rule on is held with the same SLA", async () => {
  // A name one edit away from a listed plugin: task 3.3 raises it as `review`,
  // and the policy adopts any such finding rather than inventing a fourth
  // blocking event of its own.
  const r = await run({
    root: registryTree([{ versions: [{ version: "0.1.0" }] }]),
    assets: [conforming({ id: "dice-rollers" })],
  });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_CHECK_HELD"), JSON.stringify(codes(r)));
});

await test("a failed check is a refusal, and the policy says it never got a say", async () => {
  // The licence has to be one `policy/spdx-allowlist.json` really refuses, or
  // there is no failed check and this asserts nothing. It was `GPL-3.0-only`
  // until the copyleft family joined the allowlist — after which the run went
  // green, the decision came back `publish`, and the property under test — that
  // a failed check outranks the policy engine entirely — stopped being
  // exercised at all. `BUSL-1.1` is source-available rather than open source,
  // so it stays refused for as long as POLICY.md §4 says open source only.
  const r = await run({
    root: registryTree([{ versions: [{ version: "0.1.0" }] }]),
    assets: [conforming({ license: "BUSL-1.1" })],
  });
  assertEqual(r.decision.outcome, "refuse", JSON.stringify(r.decision.reasons));
  assertEqual(codes(r).join(","), "P_REFUSED", "one row, and it points at the checks above it");
});

section("the delay");

await test("the tree the publish job commits carries the icon and the README", async () => {
  // There were two writers of a listing: `ingest.mjs`'s, which lays out the
  // tree the validator checks, and `decide.mjs`'s, which lays out the tree the
  // workflow commits. When a listing gained presentation files only the first
  // learned to write them, so validation passed on one tree and the workflow
  // committed a different one — and the run died on this repository's own rule,
  // `icon "icon.svg" is named here but the file is not in plugins/dice-roller/`.
  //
  // Asserting the FILES, not the fields: `plugin.json` naming an icon it did
  // not ship is exactly the state that got through.
  const root = registryTree([{ versions: [{ version: "0.1.0" }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({
    root,
    assets: [conforming({
      extraFiles: [
        { name: "icon.svg", data: '<svg xmlns="http://www.w3.org/2000/svg"><rect width="16" height="16"/></svg>' },
        { name: "README.md", data: "# Dice Roller\n\nRolls dice.\n" },
      ],
    })],
  });
  assertEqual(r.decision.outcome, "publish", JSON.stringify(r.decision.reasons));

  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  const dir = path.join(out, "plugins", "dice-roller");
  const doc = JSON.parse(fs.readFileSync(path.join(dir, "plugin.json"), "utf8"));
  assertEqual(doc.icon, "icon.svg", "the document has to name the icon");
  assertEqual(doc.readme, "README.md", "and the README");
  assert(fs.existsSync(path.join(dir, "icon.svg")),
    "plugin.json names an icon the committed tree does not contain");
  assert(fs.existsSync(path.join(dir, "README.md")),
    "plugin.json names a README the committed tree does not contain");
});

await test("a plugin already holding dom_access waits, even with nothing changed", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["dom_access", "tools"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "dom_access"] })] });
  assertEqual(r.decision.outcome, "delay", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("P_DELAY_HIGH_RISK"), JSON.stringify(codes(r)));
  assertEqual(hours(r.decision.publish_after, NOW), DELAY_HOURS, "24 h from now");
  assert(r.decision.notify_author, "and the author hears about it now, which is the point");
});

await test("a widening inside the non-high-risk set waits too, and publishes itself", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  assertEqual(r.decision.outcome, "delay", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("P_DELAY_WIDENED"), JSON.stringify(codes(r)));
  assert(r.decision.queue_entry.reason.includes("P_DELAY_WIDENED"), "the queue file records why it waited");
  assert(r.comment.includes("Publishing itself at"), "the comment gives the time, not a shrug");
});

await test("a narrowing is not a widening", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools", "tts"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools"] })] });
  assertEqual(r.decision.outcome, "publish", JSON.stringify(r.decision.reasons));
});

await test("the queue entry the workflow commits lands under state/queue/", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  writeOutputs(out, { repo: REPO, tag: TAG, issue: 7 }, r);
  const file = path.join(out, queueFile("dice-roller", "0.2.0"));
  assert(fs.existsSync(file), `expected ${queueFile("dice-roller", "0.2.0")}`);
  const entry = JSON.parse(fs.readFileSync(file, "utf8"));
  assertEqual(entry.repo, REPO, "the repository it is waiting on");
  assertEqual(entry.submitter, SUBMITTER, "and whose ownership gets re-proved when it drains");
  assertEqual(entry.artifact_digests.length, 1, "and the exact bytes the clock is running on");
  assert(!fs.existsSync(path.join(out, "plugins")), "a delayed release publishes nothing yet");
});

await test("when the delay has elapsed the same release publishes, and stops waiting", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const asset = conforming({ capabilities: ["tools", "tts"] });

  // Round one: it queues. Round two: the queue entry is on disk and the clock
  // has run out. The whole ingest runs again — this is not a resume.
  const first = await run({ root, assets: [asset] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(first.decision.queue_entry, null, 2)}\n`);

  const later = new Date(NOW.getTime() + (DELAY_HOURS + 1) * 3600000);
  const out = tmp("astra-policy-out-");
  const second = await run({ root, assets: [asset], now: later });
  assertEqual(second.decision.outcome, "publish", JSON.stringify(second.decision.reasons));
  assert(codes(second).includes("P_DELAY_ELAPSED"), JSON.stringify(codes(second)));
  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, second);
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8").trim(),
    queueFile("dice-roller", "0.2.0"), "and the queue entry is deleted by the same commit");
});

// `iso` is declared further down this file, and these run at import time.
const stamp = (d) => new Date(d).toISOString();

await test("a maintainer can bring the publication forward, which every entry has claimed", async () => {
  // Every queue entry this bot has ever written says "edit publish_after to
  // bring it forward". Nothing read the field: the deadline was recomputed
  // from `queued_at`, so an edited date moved only which entries triage picked
  // up, and the decision put them straight back. The instruction named an
  // action that did nothing.
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const asset = conforming({ capabilities: ["tools", "tts"] });

  const first = await run({ root, assets: [asset] });
  assertEqual(first.decision.outcome, "delay", "it has to be waiting before it can be brought forward");

  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(
    { ...first.decision.queue_entry, publish_after: stamp(NOW) }, null, 2,
  )}\n`);

  const second = await run({ root, assets: [asset], now: new Date(NOW.getTime() + 60_000) });
  assertEqual(second.decision.outcome, "publish", JSON.stringify(second.decision.reasons));
  assert(codes(second).includes("P_DELAY_BROUGHT_FORWARD"),
    `the waiver went unrecorded: ${JSON.stringify(codes(second))}`);
});

await test("but only earlier — a date pushed out cannot park a release", async () => {
  // Earlier-only, so a mistyped year is a typo rather than an indefinite hold,
  // and so this field can never extend a window past what the policy decided.
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const asset = conforming({ capabilities: ["tools", "tts"] });

  const first = await run({ root, assets: [asset] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(
    { ...first.decision.queue_entry, publish_after: stamp(NOW.getTime() + 400 * 24 * 3600000) }, null, 2,
  )}\n`);

  const later = new Date(NOW.getTime() + (DELAY_HOURS + 1) * 3600000);
  const second = await run({ root, assets: [asset], now: later });
  assertEqual(second.decision.outcome, "publish",
    `a date pushed a year out held the release: ${JSON.stringify(second.decision.reasons)}`);
});

await test("a stale entry cannot shorten the window for bytes it was not written for", async () => {
  // An entry naming an earlier date must not survive the assets changing under
  // it, or swapping the release would inherit a waiver granted for something
  // else — which would turn the maintainer override into the swap attack the
  // same-bytes guard exists to stop.
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const first = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(
    { ...first.decision.queue_entry, publish_after: stamp(NOW) }, null, 2,
  )}\n`);

  const swapped = {
    name: bundleName(),
    bytes: makeBundle({ capabilities: ["tools", "tts"], extraFiles: [{ name: "extra.txt", data: "surprise" }] }),
  };
  const second = await run({ root, assets: [swapped], now: new Date(NOW.getTime() + 60_000) });
  assertEqual(second.decision.outcome, "delay",
    `swapped bytes inherited a waiver: ${JSON.stringify(second.decision.reasons)}`);
  assert(codes(second).includes("P_DELAY_BYTES_CHANGED"), JSON.stringify(codes(second)));
});

await test("an asset swapped during the window restarts the clock", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const first = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(first.decision.queue_entry, null, 2)}\n`);

  const later = new Date(NOW.getTime() + (DELAY_HOURS + 1) * 3600000);
  const swapped = {
    name: bundleName(),
    bytes: makeBundle({ capabilities: ["tools", "tts"], extraFiles: [{ name: "extra.txt", data: "surprise" }] }),
  };
  const second = await run({ root, assets: [swapped], now: later });
  assertEqual(second.decision.outcome, "delay", JSON.stringify(second.decision.reasons));
  assert(codes(second).includes("P_DELAY_BYTES_CHANGED"), JSON.stringify(codes(second)));
  assertEqual(hours(second.decision.publish_after, later), DELAY_HOURS,
    "a swap timed for the last minute of the window buys the attacker nothing");
});

await test("a release the checks have since started refusing stops waiting", async () => {
  // The drain re-runs everything, so a queued release whose repository changed
  // hands the decision to a human — and the queue entry is removed rather than
  // left to be retried every hour for ever.
  const root = registryTree([{ repo: "someone-else/dice-roller", versions: [{ version: "0.1.0" }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root });
  assertEqual(r.decision.outcome, "review", "");
  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8").trim(),
    queueFile("dice-roller", "0.2.0"), "");
});

section("the author's track record");

await test(`${CLEAN_RELEASES_FOR_TRUSTED} clean releases buy a shorter delay`, () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([{ id: "other-thing", versions }]);
  const { plugins } = requireSources(root);
  const record = trackRecord(root, REPO, { plugins });
  assertEqual(record.tier, "established", JSON.stringify(record));
  assertEqual(record.delay_hours, TRUSTED_DELAY_HOURS, "");
});

await test("a staging listing is not a clean release", () => {
  const root = registryTree([{ id: "other-thing", versions: [{ version: "0.1.0", staging: true }] }]);
  const { plugins } = requireSources(root);
  assertEqual(trackRecord(root, REPO, { plugins }).clean_releases, 0,
    "nobody could verify its artifact, so it is not evidence of anything");
});

await test("a revocation resets the counter, a yank does not", () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED + 2 }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([{ id: "other-thing", versions }]);
  const { plugins } = requireSources(root);
  const revoked = trackRecord(root, REPO, {
    plugins,
    revocations: [{ plugin_id: "other-thing", version: "0.2.0" }],
  });
  assertEqual(revoked.tier, "new", JSON.stringify(revoked));
  assertEqual(revoked.delay_hours, DELAY_HOURS, "");
});

await test("the shorter delay actually reaches the decision", async () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([
    { versions: [{ version: "0.1.0", capabilities: ["tools"] }] },
    { id: "other-thing", repo: `${SUBMITTER}/other-thing`, versions },
  ]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  assertEqual(r.decision.outcome, "delay", "");
  assertEqual(hours(r.decision.publish_after, NOW), TRUSTED_DELAY_HOURS, JSON.stringify(r.decision.track));
  assert(codes(r).includes("P_TRUSTED_AUTHOR"), JSON.stringify(codes(r)));
});

section("the decision function on its own");

await test("an unknown permission is reported and not blocked", () => {
  const d = decide({
    findings: [],
    derived: {
      plugin: { id: "x" },
      version: { version: "1.0.0", capabilities: ["tools"], permissions: { teleport: {} } },
    },
    existing: { versions: [{ doc: { version: "0.9.0", capabilities: ["tools"] } }] },
    repo: REPO,
    now: NOW,
  });
  assert(d.reasons.some((r) => r.code === "P_UNKNOWN_PERMISSION"), JSON.stringify(d.reasons));
  assertEqual(d.outcome, "delay", "it is still a widening, so it still waits");
});

await test("capabilities and permissions are one question", () => {
  assertEqual(
    requestedAuthority({ capabilities: ["tools"], permissions: { fire_trigger: {}, tools: {} } }).join(","),
    "fire_trigger,tools",
    "declared twice is asked for once",
  );
});

await test("a backported patch is measured against the newest listing, not the last file", () => {
  const existing = {
    versions: [
      { doc: { version: "0.9.0", capabilities: ["tools", "dom_access"] } },
      { doc: { version: "0.10.0", capabilities: ["tools", "dom_access"] } },
    ],
  };
  const d = decide({
    findings: [],
    derived: { plugin: { id: "x" }, version: { version: "0.10.1", capabilities: ["tools", "dom_access"] } },
    existing, repo: REPO, now: NOW,
  });
  assertEqual(d.outcome, "delay", "held dom_access all along; delayed, not reviewed");
  assert(!d.reasons.some((r) => r.code === "R_NEW_HIGH_RISK"), JSON.stringify(d.reasons));
});

await test("every high-risk name blocks on first request", () => {
  for (const name of HIGH_RISK) {
    const d = decide({
      findings: [],
      derived: { plugin: { id: "x" }, version: { version: "1.0.0", permissions: { [name]: {} } } },
      existing: { versions: [{ doc: { version: "0.9.0" } }] },
      repo: REPO, now: NOW,
    });
    assertEqual(d.outcome, "review", `${name} must ask a person`);
  }
});

section("the review SLA, made visible");

await test("a queue past the breach threshold says what to do about it", () => {
  const report = slaReport([
    { number: 1, title: "[listing] a/b", created_at: "2026-08-01T00:00:00Z" },
    { number: 2, title: "[listing] c/d", created_at: "2026-08-10T06:00:00Z" },
  ], NOW);
  assertEqual(report.open, 2, "");
  assertEqual(report.late, 1, "");
  assertEqual(report.breached, 1, "");
  assert(report.verdict.includes("not \"review harder\""), report.verdict);
});

await test("an empty queue is within SLA and says so quietly", () => {
  assertEqual(slaReport([], NOW).verdict, "within SLA", "");
});

// ═══════════════════════════════════════════════════════════════════════════

section("the ping (task 3.4, layer 1)");

await test("/release takes one argument on a listing issue and two on a new one", () => {
  assertEqual(parseReleasePing("/release v0.2.0").tag, "v0.2.0", "");
  assertEqual(parseReleasePing("/release v0.2.0").repo, null, "one argument names no repository");
  const two = parseReleasePing("/release you/dice-roller v0.2.0");
  assertEqual(two.repo, "you/dice-roller", "");
  assertEqual(two.tag, "v0.2.0", "");
});

await test("people paste the address bar, and that is the same repository", () => {
  const p = parseReleasePing("/release `https://github.com/you/dice-roller.git/` v0.2.0");
  assertEqual(p.repo, "you/dice-roller", "");
});

await test("a mention is not a command", () => {
  assert(parseReleasePing("please /release v0.2.0 for me") === null, "");
  assert(parseReleasePing("/releases v0.2.0") === null, "");
  assert(parseReleasePing("") === null, "");
});

await test("a ping cannot smuggle a shell argument or a second repository", () => {
  assert(parseReleasePing("/release you/dice-roller v0.2.0; rm -rf /") === null, "");
  assert(parseReleasePing("/release ../../etc/passwd v1") === null, "");
  assert(parseReleasePing("/release you/dice-roller ../../evil") === null, "a `..` tag is not a tag");
});

await test("an unlabelled ping may only name a repository that is already listed", () => {
  const sources = requireSources(registryTree([{ versions: [{ version: "0.1.0" }] }]));
  assertEqual(findListingByRepo(sources, REPO).id, "dice-roller", "");
  assertEqual(findListingByRepo(sources, "A-Stranger/Dice-Roller").id, "dice-roller",
    "GitHub is case-insensitive here and so is the lookup");
  assertEqual(findListingByRepo(sources, "someone/unlisted"), null,
    "so the worst a stranger can do is re-check a listing that is already pinned");
});

section("the backstop (task 3.4, layer 2)");

await test("a listing that released recently is not polled at all", () => {
  const sources = requireSources(registryTree([
    { id: "fresh", versions: [{ version: "1.0.0", published_at: "2026-08-09T00:00:00Z" }] },
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]));
  const plan = watchPlan(sources, { repos: {} }, NOW);
  assertEqual(plan.quiet.length, 1, JSON.stringify(plan.quiet));
  assertEqual(plan.poll.length, 1, JSON.stringify(plan.poll));
  assertEqual(plan.poll[0].id, "quiet", `only listings quiet for ${WATCH_AFTER_DAYS} days cost anything`);
});

await test("an unlisted plugin is not watched", () => {
  const sources = requireSources(registryTree([
    { id: "gone", unlisted: true, versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]));
  assertEqual(watchPlan(sources, { repos: {} }, NOW).poll.length, 0, "");
});

await test("the batch rotates oldest-checked first", () => {
  const sources = requireSources(registryTree(
    ["a", "b", "c"].map((id) => ({
      id, repo: `someone/${id}`, versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }],
    })),
  ));
  const seen = { repos: {
    "someone/a": { last_checked: "2026-08-09T00:00:00Z" },
    "someone/b": { last_checked: "2026-06-01T00:00:00Z" },
  } };
  const plan = watchPlan(sources, seen, NOW, { batch: 2 });
  assertEqual(plan.poll.map((p) => p.id).join(","), "c,b", "never polled, then longest ago");
  assertEqual(plan.deferred.length, 1, "and the rest wait for the next run rather than being dropped");
});

await test("an unchanged repository costs one 304 and nothing else", async () => {
  let seenHeader = null;
  const res = await pollFeed("someone/quiet", 'W/"abc"', async (url, init) => {
    seenHeader = init.headers["If-None-Match"];
    return { status: 304, ok: false, headers: new Map(), text: async () => { throw new Error("a 304 has no body"); } };
  });
  assertEqual(seenHeader, 'W/"abc"', "the etag is fed back");
  assertEqual(res.changed, false, "");
  assertEqual(res.entries.length, 0, "");
});

const ATOM = `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <entry>
    <id>tag:github.com,2008:Repository/1/v0.3.0</id>
    <updated>2026-08-08T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/someone/quiet/releases/tag/v0.3.0"/>
    <title>v0.3.0</title>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/1/v0.2.0</id>
    <updated>2026-01-01T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/someone/quiet/releases/tag/v0.2.0"/>
    <title>v0.2.0</title>
  </entry>
  <entry>
    <updated>2026-08-09T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/attacker/elsewhere/releases/tag/v9.9.9"/>
    <title>not ours</title>
  </entry>
</feed>`;

await test("the feed parse takes four fields and refuses another repository's releases", () => {
  const entries = parseReleasesAtom(ATOM, "someone/quiet");
  assertEqual(entries.map((e) => e.tag).join(","), "v0.3.0,v0.2.0", "newest first, ours only");
  assertEqual(entries[0].updated, "2026-08-08T10:00:00Z", "");
});

await test("a release already listed, or already tried, is not re-ingested", () => {
  const entries = parseReleasesAtom(ATOM, "someone/quiet");
  assertEqual(newReleases({ listed_tag: "v0.2.0" }, entries, {}).map((e) => e.tag).join(","), "v0.3.0", "");
  assertEqual(newReleases({ listed_tag: "v0.2.0" }, entries, { checked_tags: ["v0.3.0"] }).length, 0,
    "a release this registry refused is not retried every hour for ever");
});

await test("the backstop finds a missed release and hands it to the pipeline", async () => {
  const root = registryTree([
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "0.2.0", tag: "v0.2.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]);
  const { dispatch, seen, log } = await runWatch({
    root,
    now: NOW,
    deps: {
      fetchImpl: async () => ({
        status: 200, ok: true,
        headers: new Map([["etag", 'W/"new"']]),
        text: async () => ATOM,
      }),
      fetchRelease: async (repo, tag) => ({ tag_name: tag, author: { login: "the-author" } }),
    },
  });
  assertEqual(dispatch.length, 1, JSON.stringify(log));
  assertEqual(dispatch[0].repo, "someone/quiet", "");
  assertEqual(dispatch[0].tag, "v0.3.0", "");
  assertEqual(dispatch[0].submitter, "the-author",
    "the ownership that gets proved is the release author's, never the pinger's");
  assertEqual(seen.repos["someone/quiet"].last_seen_tag, "v0.3.0", "and it is remembered");
});

await test("a repository that has gone away is recorded, not fatal", async () => {
  const root = registryTree([
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "0.2.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]);
  const { dispatch, seen } = await runWatch({
    root, now: NOW,
    deps: { fetchImpl: async () => ({ status: 404, ok: false, headers: new Map(), text: async () => "" }) },
  });
  assertEqual(dispatch.length, 0, "");
  assert(seen.repos["someone/quiet"].last_error.includes("404"), JSON.stringify(seen.repos));
});

section("the drain");

await test("only a ripe queue entry is dispatched, and the rest are reported", () => {
  const root = tmp("astra-policy-queue-");
  fs.mkdirSync(path.join(root, "state", "queue"), { recursive: true });
  const write = (id, version, publishAfter) =>
    fs.writeFileSync(path.join(root, queueFile(id, version)), `${JSON.stringify({
      id, version, repo: `someone/${id}`, tag: `v${version}`, submitter: "someone",
      queued_at: "2026-08-09T12:00:00Z", publish_after: publishAfter, reason: "P_DELAY_HIGH_RISK",
    })}\n`);
  write("ripe-one", "1.0.0", "2026-08-10T11:00:00Z");
  write("still-waiting", "2.0.0", "2026-08-11T11:00:00Z");

  assertEqual(readQueue(root).length, 2, "both are visible to a maintainer");
  const { dispatch, log } = runDrain({ root, now: NOW });
  assertEqual(dispatch.length, 1, JSON.stringify(dispatch));
  assertEqual(dispatch[0].repo, "someone/ripe-one", "");
  assertEqual(dispatch[0].submitter, "someone", "whose ownership is proved again on the way in");
  assert(log.some((l) => l.includes("wait") && l.includes("still-waiting")), log.join("\n"));
});

section("what the workflow asks before it spends anything");

/** Write two bodies to files, the way `.github/workflows/ingest.yml` does. */
function bodies({ issue = "", comment = "" }) {
  const dir = tmp("astra-policy-body-");
  fs.writeFileSync(path.join(dir, "issue.md"), issue);
  fs.writeFileSync(path.join(dir, "comment.md"), comment);
  return { issueBody: path.join(dir, "issue.md"), commentBody: path.join(dir, "comment.md") };
}

const FORM = [
  "### Source repository", "", REPO, "",
  "### Release tag carrying the .astraplugin assets", "", TAG, "",
  "### Confirmations", "",
  "- [X] I own or maintain this repository.",
].join("\n");

const releaseBy = (login) => async (repo, tag) => ({ tag_name: tag, author: { login } });

await test("a labelled listing issue is still the submission form's", async () => {
  const out = await triage({
    event: "issues", labels: "listing,needs-triage", root: registryTree([{}]),
    ...bodies({ issue: FORM }),
  }, releaseBy("a-stranger"));
  assertEqual(out.mode, "form", out.why);
});

await test("`/release v0.2.0` on a listing issue takes the repository from the issue", async () => {
  const out = await triage({
    event: "issue_comment", labels: "listing", root: registryTree([{}]),
    ...bodies({ issue: FORM, comment: "/release v0.3.0" }),
  }, releaseBy("the-author"));
  assertEqual(out.mode, "ping", out.why);
  assertEqual(out.repo, REPO, "named by the issue, not by whoever commented");
  assertEqual(out.tag, "v0.3.0", "");
  assertEqual(out.submitter, "the-author", "the release author, never the pinger");
});

await test("an unlabelled ping is honoured only for a listing that already exists", async () => {
  const root = registryTree([{}]);
  const listed = await triage({
    event: "issues", labels: "", root,
    ...bodies({ issue: `/release ${REPO} v0.3.0\n\nnew release!` }),
  }, releaseBy("the-author"));
  assertEqual(listed.mode, "ping", listed.why);

  const stranger = await triage({
    event: "issues", labels: "", root,
    ...bodies({ issue: "/release somebody/brand-new v1.0.0" }),
  }, releaseBy("the-author"));
  // `none` until the intake fix: a stranger's ping for an unlisted repository
  // still starts nothing — that restriction is what makes a ping safe to accept
  // without a token — but it is now a `reply` rather than a silence, and the
  // reply is what points at the form a first listing actually goes through.
  assertEqual(stranger.mode, "reply", "a first listing is not reachable this way");
  assert(stranger.why.includes("template"), stranger.why);
  assert(stranger.reply.includes("already listed"), stranger.reply);
  assert(!stranger.repo && !stranger.tag, "and nothing is queued for verification");
});

await test("a release ping survives being rendered by an issue form", async () => {
  // `.github/ISSUE_TEMPLATE/config.yml` turned blank issues off, so the
  // ping-as-a-new-issue path docs/POLICY.md §5 promises now goes through
  // `release-ping.yml` — and GitHub renders every form as `### <label>`, a
  // blank line, then the value. Under the old first-line-only rule the command
  // was never on line 1 again and the path stopped working the day the form
  // became mandatory.
  const rendered = "### The command\n\n/release " + REPO + " v0.3.0\n";
  const out = await triage({
    event: "issues", labels: "", root: registryTree([{}]),
    ...bodies({ issue: rendered }),
  }, releaseBy("the-author"));
  assertEqual(out.mode, "ping", out.why);
  assertEqual(out.tag, "v0.3.0", "");

  // And the relaxation is exactly two things — a blank line and a heading.
  // Prose above the command still hides it, which is what stops a quoted reply
  // from re-triggering an ingest.
  const prose = await triage({
    event: "issues", labels: "", root: registryTree([{}]),
    ...bodies({ issue: `here you go\n\n/release ${REPO} v0.3.0` }),
  }, releaseBy("the-author"));
  assert(prose.mode !== "ping", `prose above the command must not run it: ${prose.mode}`);
});

await test("/recheck still means recheck, and prose still means nothing", async () => {
  const root = registryTree([{}]);
  assertEqual((await triage({
    event: "issue_comment", labels: "listing", root, ...bodies({ issue: FORM, comment: "/recheck" }),
  }, releaseBy("x"))).mode, "form", "");
  assertEqual((await triage({
    event: "issue_comment", labels: "listing", root,
    ...bodies({ issue: FORM, comment: "any news on this? maybe /release it" }),
  }, releaseBy("x"))).mode, "none", "");
});

await test("a ping for a tag that has no release is dropped, not ingested", async () => {
  const out = await triage({
    event: "issues", labels: "", root: registryTree([{}]),
    ...bodies({ issue: `/release ${REPO} v9.9.9` }),
  }, async () => { throw new Error("no release tagged v9.9.9 (404)"); });
  assertEqual(out.mode, "none", out.why);
  assert(out.why.includes("404"), out.why);
});

// ═══════════════════════════════════════════════════════════════════════════
//
// Defect 1: a submission that reached this registry and was answered with
// nothing at all. Two of them, `#13` and `#14`. Both carried the rendered form
// and zero labels, because there was no `.github/ISSUE_TEMPLATE/config.yml` and
// blank issues were on, so they bypassed the template that applies the label.
// `triage` answered `none`, `targets=[]`, every later job was skipped, and the
// run went green — it had succeeded at deciding to do nothing.

section("no listing request is answered with silence");

/** The two facts, both boxes, and nothing else — a form GitHub has rendered. */
const form = ({ repo = REPO, tag = TAG, boxes = 2, headings = true } = {}) => [
  ...(headings ? ["### Source repository", "", repo, ""] : [repo, ""]),
  ...(headings ? ["### Release tag carrying the .astraplugin assets", "", tag, ""] : [tag, ""]),
  "### Confirmations", "",
  `- [${boxes >= 1 ? "x" : " "}] I own or maintain this repository.`,
  `- [${boxes >= 2 ? "x" : " "}] I have read POLICY.md, including the data-handling section.`,
].join("\n");

/**
 * `mihailinl/astra-registry#14`, verbatim, as `gh issue view 14 --json body`
 * returned it on 2026-08-12 — trimmed only of the prose paragraph, which the
 * bot never reads.
 *
 * Embedded rather than fetched: this suite touches no network, and a regression
 * test that needs GitHub to be up is a regression test that goes quiet on the
 * day the network is the problem. The title and the empty label array are the
 * two facts that mattered.
 */
const ISSUE_14 = {
  title: "[listing] Rel0d1x/command-intent-guard",
  labels: "",
  body: [
    "### Source repository", "", "Rel0d1x/command-intent-guard", "",
    "### Release tag carrying the .astraplugin assets", "", "v0.1.0", "",
    "### What does it do, and why should it be listed?", "",
    "Adds a `tools` capability that tells a spoken command apart from a question.", "",
    "### Confirmations", "",
    "- [x] I own or maintain this repository.",
    "- [x] I have read POLICY.md, including the data-handling section.",
  ].join("\n"),
};

/** The three files the workflow writes, plus the arguments it passes with them. */
function intake({ issue = "", comment = "", title = "", labels = "", action = "opened", event = "issues", root, ...rest }) {
  const dir = tmp("astra-policy-intake-");
  fs.writeFileSync(path.join(dir, "issue.md"), issue);
  fs.writeFileSync(path.join(dir, "comment.md"), comment);
  fs.writeFileSync(path.join(dir, "title.md"), title);
  return {
    event, action, labels, root: root ?? registryTree([{}]),
    registry: "mihailinl/astra-registry",
    issueBody: path.join(dir, "issue.md"),
    commentBody: path.join(dir, "comment.md"),
    issueTitle: path.join(dir, "title.md"),
    ...rest,
  };
}

await test("the real #14 — the form, no labels — no longer decides `none`", async () => {
  const out = await triage(intake({
    issue: ISSUE_14.body, title: ISSUE_14.title, labels: ISSUE_14.labels,
    root: registryTree([{ id: "something-else" }]),
  }), releaseBy("Rel0d1x"));
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("Rel0d1x/command-intent-guard"),
    "the reply has to name the repository the author asked about");
  assert(out.reply.includes("v0.1.0"), "and the tag");
});

await test("the reply names the label, the one click, and why the bot will not click it", async () => {
  const out = await triage(intake({ issue: form(), title: "[listing] a-stranger/dice-roller" }),
    releaseBy("a-stranger"));
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("`listing` label"), "the missing thing has a name");
  assert(/one click/i.test(out.reply), "and a fix that is one action, not a resubmission");
  assert(out.reply.includes("authority token"),
    "an author told to go and ask somebody, with no reason, assumes the bot is broken");
  // The whole argument for replying instead of auto-labelling: the label is an
  // exemption from the already-listed rule, so minting it from the shape of a
  // body would let a stranger choose which repositories this registry
  // downloads archives from.
  assertEqual(out.mode !== "form", true, "and nothing was verified for a repository nobody proved");
});

await test("either signal alone is enough: a rewritten title, or a rewritten body", async () => {
  const titleOnly = await triage(intake({ issue: "please list my plugin, thanks", title: "[listing] me/mine" }),
    releaseBy("me"));
  assertEqual(titleOnly.mode, "reply", titleOnly.why);

  const bodyOnly = await triage(intake({ issue: form(), title: "can you add this one" }), releaseBy("me"));
  assertEqual(bodyOnly.mode, "reply", bodyOnly.why);
});

await test("an ordinary issue is still free, and still silent", async () => {
  const out = await triage(intake({ issue: "the website is down", title: "site 500s" }), releaseBy("x"));
  assertEqual(out.mode, "none", out.why);
  assertEqual(out.reply, undefined, "no comment, no API call, no noise");
});

await test("the bot does not answer its own notices, or the other three forms", async () => {
  for (const title of [
    "[notice] dice-roller 0.2.0 publishes itself at 2026-08-11T12:00:00Z",
    "[appeal] dice-roller",
    "[report] dice-roller",
  ]) {
    const out = await triage(intake({ issue: form(), title }), releaseBy("x"));
    assertEqual(out.mode, "none", `${title} → ${out.why}`);
  }
});

await test("the intake comment is posted once, not on every edit", async () => {
  const opened = await triage(intake({ issue: form(), title: "[listing] x/y", action: "opened" }), releaseBy("x"));
  assertEqual(opened.mode, "reply", opened.why);
  const edited = await triage(intake({ issue: form(), title: "[listing] x/y", action: "edited" }), releaseBy("x"));
  assertEqual(edited.mode, "none", "a bot that repeats itself on every edit is a bot people mute");
});

await test("a labelled form the bot cannot read gets a comment, not a red X", async () => {
  // `bot/read-submission.mjs` exits 2 on an unticked confirmation, and the
  // workflow step runs under `set -e`. That killed the step: no target, no
  // comment job, and a submitter who ticked one box instead of two got a red X
  // and silence. Triage now answers the same question with the same parser
  // first.
  const out = await triage(intake({ issue: form({ boxes: 1 }), title: "[listing] x/y", labels: "listing" }),
    releaseBy("x"));
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("POLICY.md"), "and it names the box that is not ticked");
  assert(out.reply.includes("Edit this issue"), "with a fix that is not 'open a new one'");
});

await test("the release-ping form with a broken command is answered too", async () => {
  const out = await triage(intake({
    issue: "### The command\n\n/release i-forgot-the-tag\n",
    title: "[release] owner/repo v0.0.0",
  }), releaseBy("x"));
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("/release owner/repo v0.2.0"), "and shows the shape that works");
});

// ═══════════════════════════════════════════════════════════════════════════
//
// Defect 2: `outcome: "review"` was a terminus. The bot said "held for a
// maintainer", `decide.mjs` exited 3, and nothing in this repository
// implemented the maintainer's next move — `git grep -nE "/approve|approved-by"`
// over `bot/`, `docs/` and `.github/` returned nothing.

section("the maintainer's two commands");

/** `bot/lib/maintainer.mjs`, answered from a table instead of from GitHub. */
const roles = (table) => async ({ repo, login }) => {
  const role = table[login];
  if (role === undefined) {
    return {
      ok: false,
      role: null,
      detail: `GitHub would not say what @${login} has on ${repo} (HTTP 403 — not visible to the bot), so the command is refused.`,
    };
  }
  if (role === "admin" || role === "maintain") {
    return { ok: true, role, detail: `GitHub reports @${login} has \`${role}\` on ${repo}` };
  }
  return {
    ok: false,
    role,
    detail: `GitHub reports @${login} has \`${role}\` on ${repo}, which is neither \`admin\` nor \`maintain\`.`,
  };
};

const MAINTAINERS = roles({ "the-maintainer": "admin", "a-second-pair-of-eyes": "maintain", "a-stranger": "read", "a-triager": "triage" });

const command = (text, commenter, extra = {}) => triage(
  intake({
    event: "issue_comment", action: "created", labels: "listing",
    issue: form(), title: "[listing] a-stranger/dice-roller",
    comment: text, commenter, issueAuthor: SUBMITTER, now: NOW, ...extra,
  }),
  releaseBy(SUBMITTER),
  { proveMaintainer: extra.prove ?? MAINTAINERS },
);

await test("/approve from somebody with no write access is refused, and told why", async () => {
  const out = await command("/approve", "a-stranger");
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("`/approve` is refused"), out.reply);
  assert(out.reply.includes("`read`"), "the role GitHub actually reported, not a shrug");
  assert(out.reply.includes("author_association"),
    "and the reason the obvious cheaper check was not the one used");
  assert(!out.repo && !out.tag, "and no target — nothing was verified and nothing published");
});

await test("a `triage` collaborator is not a maintainer either", async () => {
  // The exact case `author_association` gets wrong: the event payload calls
  // this account `COLLABORATOR`, and it cannot push a byte to this repository.
  const out = await command("/approve", "a-triager");
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("`triage`"), out.reply);
});

await test("when GitHub will not answer, the command fails closed", async () => {
  const out = await command("/approve", "somebody-unknown");
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("would not say"), out.reply);
  // `proveOwnership` treats a missing answer as "no answer" and falls through
  // to weaker proofs, because refusing every organisation that has not
  // installed an app would make third-party publishing theoretical. There is no
  // equivalent argument here: one repository, this bot's own token, and the
  // cost of being wrong is a published listing rather than a refused one.
  assert(!out.repo, "and no target is emitted on a permission nobody could read");
});

// The real `proveMaintainer`, against a stubbed `fetch`. Every test above
// injects a stub for it, which is exactly why the endpoint's own behaviour has
// never been exercised: `GET /collaborators/{login}/permission` is documented
// as requiring push access, the triage job's `GITHUB_TOKEN` holds
// `contents: read`, and `administration` is not a scope a workflow token can
// request — so a 403 there would make `/approve` refuse the repository's owner
// on every path, silently, and no stubbed test could see it.
const respond = (status, body) => async () => ({
  ok: status >= 200 && status < 300,
  status,
  json: async () => body ?? {},
});

await test("a 403 on the permission endpoint no longer refuses the repository's owner", async () => {
  const denied = await proveMaintainer({
    repo: REGISTRY_REPO, login: "the-maintainer", fetchImpl: respond(403),
  });
  assertEqual(denied.ok, false, "no association: still fails closed, which is the default");

  const owner = await proveMaintainer({
    repo: REGISTRY_REPO, login: "the-maintainer", association: "OWNER", fetchImpl: respond(403),
  });
  assertEqual(owner.ok, true, owner.detail);
  assertEqual(owner.role, "owner", "");
  assert(owner.detail.includes("author_association"), owner.detail);
});

await test("no association below OWNER fills the silence", async () => {
  for (const association of ["COLLABORATOR", "MEMBER", "CONTRIBUTOR", "NONE", "", null]) {
    const out = await proveMaintainer({
      repo: REGISTRY_REPO, login: "a-stranger", association, fetchImpl: respond(403),
    });
    assertEqual(out.ok, false, `${association} must not stand in for a permission`);
  }
});

await test("OWNER never overrides an answer GitHub did give", async () => {
  // The narrowing that keeps this from being a reversal of the module's rule:
  // it fills a silence, it does not outrank a `read`.
  const out = await proveMaintainer({
    repo: REGISTRY_REPO, login: "a-stranger", association: "OWNER",
    fetchImpl: respond(200, { role_name: "read" }),
  });
  assertEqual(out.ok, false, out.detail);
  assertEqual(out.role, "read", "");
});

await test("/approve from a maintainer emits a target carrying the approval, and nothing else", async () => {
  const out = await command("/approve", "the-maintainer");
  assertEqual(out.mode, "approve", out.why);
  assertEqual(out.repo, REPO, "");
  assertEqual(out.tag, TAG, "");
  assertEqual(out.submitter, SUBMITTER, "the issue author, whose ownership is proved again downstream");
  assertEqual(out.approvedBy, "the-maintainer", "");
  assert(/^2026-/.test(out.approvedAt), out.approvedAt);
  // The property the whole design rests on: an approval is a name and a moment.
  // No verdict, no digest, no listing — so there is no second, shorter route
  // into the catalogue for a release somebody said yes to.
  assert(!("findings" in out) && !("derived" in out) && !("decision" in out),
    `an approval must carry no verification with it: ${Object.keys(out).join(", ")}`);
});

await test("/reject with no reason changes nothing and says so", async () => {
  const out = await command("/reject", "the-maintainer");
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("needs a reason"), out.reply);
  assert(out.reply.includes("Nothing has been closed"), out.reply);
});

await test("/reject closes the loop for the author: the reason, and what to do next", async () => {
  const out = await command("/reject the licence is not one this registry allows", "a-second-pair-of-eyes");
  assertEqual(out.mode, "reject", out.why);
  assertEqual(out.close, true, "the issue leaves the review queue");
  assertEqual(out.by, "a-second-pair-of-eyes", "");
  assert(out.reply.includes("the licence is not one this registry allows"),
    "the reason is quoted back on the thread, which is the whole point of the command");
  assert(out.reply.includes("open a fresh listing request"), "a rejection is not permanent");
  assert(!out.repo, "and nothing is ingested");
});

await test("a command on an issue with nothing to decide about says so", async () => {
  const out = await command("/approve", "the-maintainer", {
    issue: "the website is down", title: "site 500s", labels: "",
  });
  assertEqual(out.mode, "reply", out.why);
  assert(out.reply.includes("nothing to act on"), out.reply);
});

await test("prose that mentions the command is not the command", async () => {
  const out = await command("I think we should /approve this one", "the-maintainer");
  assert(out.mode !== "approve", `${out.mode}: ${out.why}`);
});

await test("a quoted reply does not re-run the command", async () => {
  const out = await command("> /approve\n\nno, not yet", "the-maintainer");
  assert(out.mode !== "approve", `${out.mode}: ${out.why}`);
});

section("an approval clears the hold, and only the hold");

/**
 * A world where `dice-roller` is listed and something else has taken its
 * display name, so a re-release is held on `R_DISPLAY_NAME_COLLISION` — a hold
 * that is not about the bytes and not about the permissions, which is what
 * makes it the clean case for "approval clears the hold and the release
 * publishes".
 */
const collidingTree = () => registryTree([
  { versions: [{ version: "0.1.0" }] },
  { id: "bingo-cards", name: "Dice Roller", versions: [{ version: "1.0.0" }] },
]);

await test("without an approval it is held, with the SLA and no listing", async () => {
  const r = await run({ root: collidingTree() });
  assertEqual(r.decision.outcome, "review", JSON.stringify(codes(r)));
  assertEqual(r.decision.publishes_now, false, "");
  assertEqual(r.decision.approved_by, null, "");
});

await test("a maintainer's yes re-runs every check and publishes what THIS run hashed", async () => {
  const assets = [conforming()];
  const r = await run({
    root: collidingTree(), assets,
    approvedBy: "the-maintainer", approvedAt: "2026-08-10T11:59:00Z",
  });
  assertEqual(r.decision.outcome, "publish", JSON.stringify(codes(r)));
  assert(codes(r).includes("P_APPROVED"), JSON.stringify(codes(r)));
  assertEqual(r.decision.approved_by, "the-maintainer", "");
  assertEqual(r.decision.approved_at, "2026-08-10T11:59:00Z", "");

  // The hold is still on the record — the point of an audit trail is that the
  // thing that was cleared is still visible.
  assert(codes(r).includes("R_CHECK_HELD"), JSON.stringify(codes(r)));

  // "Against which digest" has to be the digest of the bytes this run
  // downloaded, or the record is a sentence nobody can check later.
  const expected = crypto.createHash("sha256").update(assets[0].bytes).digest("hex");
  assert(r.decision.artifact_digests.some((d) => d.endsWith(`:${expected}`)),
    `${JSON.stringify(r.decision.artifact_digests)} does not contain ${expected}`);

  // And the comment does not still tell the author to wait for a maintainer.
  assert(r.comment.includes("A maintainer cleared the hold: **@the-maintainer**"), "");
  assert(!r.comment.includes("Nothing to do but wait"),
    "a cleared hold must not keep printing the remedy for an uncleared one");
});

await test("an approval cannot clear a failed check", async () => {
  const r = await run({
    root: collidingTree(),
    assets: [conforming({ license: "BUSL-1.1" })],
    approvedBy: "the-maintainer", approvedAt: "2026-08-10T11:59:00Z",
  });
  assertEqual(r.decision.outcome, "refuse", JSON.stringify(codes(r)));
  assertEqual(codes(r).join(","), "P_REFUSED", "the refusal branch runs first and ends it");
  // Recorded even so: the maintainer did type the command, and a record that
  // omitted an approval the registry then ignored could not be reconciled with
  // the thread.
  assertEqual(r.decision.approved_by, "the-maintainer", "");

  // The rendered markdown is the only artefact the author ever sees, so it is
  // the one worth asserting on. It used to print "Not published. A check above
  // failed; the policy never got a say." and then, in the very next paragraph,
  // "A maintainer cleared the hold" — two sentences that cannot both be true,
  // about a hold that was never raised.
  assert(!r.comment.includes("cleared the hold"),
    "nothing was held on a refusal, so nothing can have been cleared:\n" + r.comment);
  assert(r.comment.includes("typed `/approve`") && r.comment.includes("changed nothing"),
    "the refusal still has to account for the command the maintainer typed:\n" + r.comment);
});

await test("an approval does not waive the publication delay, and the queue remembers it", async () => {
  const r = await run({
    root: collidingTree(),
    assets: [conforming({ capabilities: ["tools", "tts"] })],
    approvedBy: "the-maintainer", approvedAt: "2026-08-10T11:59:00Z",
  });
  assertEqual(r.decision.outcome, "delay", JSON.stringify(codes(r)));
  assert(codes(r).includes("P_APPROVED") && codes(r).includes("P_DELAY_WIDENED"), JSON.stringify(codes(r)));
  assertEqual(hours(r.decision.publish_after, NOW), DELAY_HOURS, "");
  // The hold and the delay answer different questions — *may this be listed at
  // all* versus *has the author had a chance to notice* — and one person's yes
  // does not answer the second one.
  assertEqual(r.decision.queue_entry.approved_by, "the-maintainer",
    "and without this the hourly drain raises the same hold again in 24 h and the release loops");
});

await test("the drain honours the approval in the queue without a second comment", async () => {
  const root = collidingTree();
  const assets = [conforming({ capabilities: ["tools", "tts"] })];
  const first = await run({ root, assets, approvedBy: "the-maintainer", approvedAt: "2026-08-10T11:59:00Z" });
  assertEqual(first.decision.outcome, "delay", "");

  // Commit the queue entry the publish job would have committed, then let the
  // clock run out. No `--approved-by` this time: a cron drain has no comment
  // behind it, which is exactly the run that used to bounce it back to review.
  const entry = first.decision.queue_entry;
  const file = path.join(root, queueFile(entry.id, entry.version));
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(entry, null, 2)}\n`);

  const later = await run({ root, assets, now: new Date(NOW.getTime() + 25 * 3600 * 1000) });
  assertEqual(later.decision.outcome, "publish", JSON.stringify(codes(later)));
  assertEqual(later.decision.approved_by, "the-maintainer", "carried forward from the queue entry");
  assert(codes(later).includes("P_DELAY_ELAPSED"), JSON.stringify(codes(later)));
});

await test("swapping the assets mid-window takes the approval with the clock", async () => {
  const root = collidingTree();
  const first = await run({
    root, assets: [conforming({ capabilities: ["tools", "tts"] })],
    approvedBy: "the-maintainer", approvedAt: "2026-08-10T11:59:00Z",
  });
  const entry = first.decision.queue_entry;
  const file = path.join(root, queueFile(entry.id, entry.version));
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(entry, null, 2)}\n`);

  // Same repository, same tag, different bytes — §5.5's timed swap.
  const swapped = await run({
    root,
    assets: [conforming({ capabilities: ["tools", "tts"], description: "Rolls dice. Differently." })],
    now: new Date(NOW.getTime() + 23 * 3600 * 1000),
  });
  assertEqual(swapped.decision.outcome, "review",
    "the hold comes back, because nobody has approved THESE bytes");
  assertEqual(swapped.decision.approved_by, null,
    "an approval recorded against a digest must never be reused for a different one");
});

section("the document and the code say the same thing");

await test("docs/POLICY.md quotes the numbers the code enforces", () => {
  const doc = fs.readFileSync(path.join(REPO_ROOT, "docs", "POLICY.md"), "utf8");
  for (const needle of [
    `${DELAY_HOURS} h`,
    `${TRUSTED_DELAY_HOURS} h`,
    `${REVIEW_SLA_HOURS} h`,
    `${CLEAN_RELEASES_FOR_TRUSTED} clean`,
    `${WATCH_AFTER_DAYS} days`,
  ]) {
    assert(doc.includes(needle), `docs/POLICY.md never says "${needle}", so the published policy has drifted from the code`);
  }
  for (const name of HIGH_RISK) {
    assert(doc.includes(`\`${name}\``), `docs/POLICY.md does not list ${name} as high-risk`);
  }
  for (const code of Object.keys(POLICY_CODES)) {
    assert(doc.includes(code), `docs/POLICY.md does not explain ${code}, which an author can be shown`);
  }
});

await test("docs/POLICY.md quotes the triage clock the moderation code declares", async () => {
  const { TRIAGE_ACK_HOURS, TRIAGE_HARM_HOURS, TRIAGE_DECISION_DAYS, APPEAL_RESPONSE_DAYS, ACTIONS } =
    await import("../lib/moderation.mjs");
  const doc = fs.readFileSync(path.join(REPO_ROOT, "docs", "POLICY.md"), "utf8");
  for (const needle of [
    `**${TRIAGE_ACK_HOURS} h**`,
    `**${TRIAGE_HARM_HOURS} h**`,
    `**${TRIAGE_DECISION_DAYS} days**`,
    `**${APPEAL_RESPONSE_DAYS} days**`,
  ]) {
    assert(doc.includes(needle),
      `docs/POLICY.md never says "${needle}", so the published triage clock has drifted from the code`);
  }
  // The four escalating actions, each named where a reporter will look for it.
  for (const action of ACTIONS) {
    const titled = action[0].toUpperCase() + action.slice(1);
    assert(doc.includes(`**${titled}**`), `docs/POLICY.md does not name the ${action} action`);
  }
  // And the appeals template, which is what an author is told to use.
  assert(doc.includes("[appeal] <plugin-id>"), "docs/POLICY.md carries no appeals template");
});

await test("POLICY.md points at the detail rather than restating it", () => {
  const doc = fs.readFileSync(path.join(REPO_ROOT, "POLICY.md"), "utf8");
  assert(doc.includes("docs/POLICY.md"), "the listing policy has to link the publication policy");
  assert(doc.includes(`${REVIEW_SLA_HOURS} hours`) || doc.includes(`${REVIEW_SLA_HOURS} h`),
    "and §8 has to carry the number now that there is one");
});

// ── result ──────────────────────────────────────────────────────────────────

console.log();
if (failures.length) {
  console.log(`FAIL  ${passed} passed, ${failures.length} failed`);
  process.exit(1);
}
console.log(`PASS  ${passed} passed, 0 failed`);
