#!/usr/bin/env node
// The publication policy's own suite.  `node bot/tests/policy.test.mjs`
//
// Task 3.5's acceptance is one sentence — *"a normal patch release is live
// without a human; a `dom_access` request is not"* — and both halves are the
// first two tests below, run through the **whole** pipeline against the bot's
// fixture corpus: a real bundle, a real archive walk, the real manifest probe,
// the real derivation, and then the policy. Asserting the policy function in
// isolation would prove that `decide()` returns what `decide()` returns; these
// prove that a release does or does not reach the catalogue.
//
// Everything else here exists because the interesting half of this task is not
// the happy path. A delay that never ends, a queue entry that republishes a
// release the checks have since started refusing, a clock that a swapped asset
// can wait out — each of those is a way for "zero-touch" to mean "unsupervised
// and wrong", and each has a test.
//
// Nothing touches the network.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { decideRelease, writeOutputs } from "../decide.mjs";
import { DEFAULT_SIGNER_WORKFLOW } from "../ingest.mjs";
import {
  CLEAN_RELEASES_FOR_TRUSTED,
  DELAY_HOURS,
  HIGH_RISK,
  POLICY_CODES,
  REVIEW_SLA_HOURS,
  TRUSTED_DELAY_HOURS,
  decide,
  queueFile,
  readQueue,
  requestedAuthority,
  slaReport,
  trackRecord,
} from "../lib/policy.mjs";
import {
  WATCH_AFTER_DAYS,
  findListingByRepo,
  newReleases,
  parseReleasePing,
  parseReleasesAtom,
  watchPlan,
} from "../lib/notify.mjs";
import { pollFeed, runDrain, runWatch } from "../watch.mjs";
import { triage } from "../triage.mjs";
import { makeBundle, fakeGitHub, fakeGh, fakeOwnership } from "../fixtures/ingest/make.mjs";
import { loadSources } from "../../tools/lib/sources.mjs";

const REPO_ROOT = path.resolve(fileURLToPath(new URL("../..", import.meta.url)));

/** `loadSources`, named for what the assertions below are actually asking. */
const requireSources = (root) => loadSources(root);

// ── harness ─────────────────────────────────────────────────────────────────

let passed = 0;
const failures = [];
let group = "";
function section(name) { group = name; console.log(`\n${name}`); }
async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok    ${name}`);
  } catch (e) {
    failures.push({ group, name, error: e });
    console.log(`  FAIL  ${name}\n        ${e.message.split("\n").join("\n        ")}`);
  }
}
function assert(cond, message) { if (!cond) throw new Error(message); }
function assertEqual(actual, expected, message) {
  if (actual !== expected) throw new Error(`${message}\n  expected: ${expected}\n  actual:   ${actual}`);
}

const scratch = [];
process.on("exit", () => { for (const d of scratch) fs.rmSync(d, { recursive: true, force: true }); });
function tmp(prefix) {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  scratch.push(d);
  return d;
}

// ── the world ───────────────────────────────────────────────────────────────

const REPO = "a-stranger/dice-roller";
const TAG = "v0.2.0";
const SUBMITTER = "a-stranger";
const ALLOWED_WORKFLOW_SHA = "0".repeat(40);
const NOW = new Date("2026-08-10T12:00:00Z");

function testRootsFile() {
  const keys = ["root-a", "root-b"].map((n) =>
    JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "tools", "testkeys", `TEST-ONLY-DO-NOT-TRUST-${n}.pub.json`), "utf8")));
  const file = path.join(tmp("astra-policy-roots-"), "root.json");
  fs.writeFileSync(file, JSON.stringify({
    $banner: "TEST ROOTS — generated by bot/tests/policy.test.mjs, never committed, never trusted by a daemon.",
    schema: "astra.registry.root/1",
    status: "provisioned",
    roots: keys.map((k) => ({ key_id: k.key_id, public_key: k.public_key, role: k.role })),
  }, null, 2));
  return file;
}
const ROOTS_FILE = testRootsFile();
const TRUST_FILE = path.join(REPO_ROOT, "tools", "testkeys", "fixtures", "trust-active-signed.json");

/**
 * A registry tree, written from a description.
 *
 * `staging: false` matters here in a way it does not in the ingest suite: a
 * staging entry is not a clean release (nobody could verify its artifact), so
 * the graduation test has to write listings that carry digests.
 */
function registryTree(specs) {
  const dir = tmp("astra-policy-reg-");
  for (const spec of specs) {
    const id = spec.id ?? "dice-roller";
    const repo = spec.repo ?? REPO;
    const pdir = path.join(dir, "plugins", id, "versions");
    fs.mkdirSync(pdir, { recursive: true });
    fs.writeFileSync(path.join(dir, "plugins", id, "plugin.json"), `${JSON.stringify({
      schema: "astra.registry.plugin/1",
      id,
      // Derived from the id unless a test says otherwise. Two fixture listings
      // sharing one display name is now a finding in its own right
      // (R_DISPLAY_NAME_COLLISION covers the byte-identical case), and a
      // fixture that trips a real rule by accident tests the wrong thing.
      name: spec.name ?? (id === "dice-roller" ? "Dice Roller" : id),
      summary: "Rolls dice when you ask it to.",
      license: "MIT",
      source: { kind: "github", repo },
      added_at: "2026-01-01",
      ...(spec.unlisted ? { unlisted: true } : {}),
    }, null, 2)}\n`);
    for (const v of spec.versions ?? [{ version: "0.1.0" }]) {
      const staging = v.staging ?? true;
      fs.writeFileSync(path.join(pdir, `${v.version}.json`), `${JSON.stringify({
        schema: "astra.registry.version/1",
        id,
        version: v.version,
        published_at: v.published_at ?? "2026-01-01T00:00:00Z",
        release: { kind: "github_release", repo, tag: v.tag ?? `v${v.version}` },
        ...(staging
          ? { staging: true, staging_reason: "Test fixture: the release this points at is a fake." }
          : {}),
        // Always recorded, the way `bot/lib/derive.mjs` records it: a listing
        // that predates capability recording reads as "asks for nothing",
        // which makes its next release look like a widening. That is a
        // one-off 24 h delay per legacy listing and it fails safe, but a
        // fixture that reproduced it in every test would be measuring the
        // fixture rather than the policy.
        capabilities: v.capabilities ?? ["tools"],
        ...(v.permissions ? { permissions: v.permissions } : {}),
        artifacts: {
          "linux-x64": {
            url: `https://github.com/${repo}/releases/download/v${v.version}/${id}-${v.version}-linux-x64.astraplugin`,
            filename: `${id}-${v.version}-linux-x64.astraplugin`,
            ...(staging ? {} : { sha256: "b".repeat(64), size: 1024 }),
          },
        },
      }, null, 2)}\n`);
    }
  }
  return dir;
}

const bundleName = (spec = {}) =>
  `${spec.id ?? "dice-roller"}-${spec.version ?? "0.2.0"}-${spec.os === "windows" ? "windows-x64" : "linux-x64"}.astraplugin`;
const conforming = (spec = {}) => ({ name: bundleName(spec), bytes: makeBundle(spec) });

/** One ingest-and-decide against a world assembled from the arguments. */
async function run({
  assets = [conforming()], repo = REPO, tag = TAG, submitter = SUBMITTER, root,
  now = NOW, out = null, issue = null,
} = {}) {
  const github = fakeGitHub({ repo, tag, assets });
  return decideRelease(
    {
      repo, tag, submitter, root, issue, now,
      rootsFile: ROOTS_FILE, trustFile: TRUST_FILE, signerWorkflow: DEFAULT_SIGNER_WORKFLOW,
      out,
    },
    {
      fetchRelease: github.fetchRelease.bind(github),
      headAsset: github.headAsset.bind(github),
      downloadAsset: github.downloadAsset.bind(github),
      proveOwnership: fakeOwnership(true),
      ghRunner: (args) => fakeGh({
        repo,
        signerDigest: ALLOWED_WORKFLOW_SHA,
        subjectDigest: crypto.createHash("sha256").update(fs.readFileSync(args[2])).digest("hex"),
      })(args),
    },
  );
}

const codes = (r) => r.decision.reasons.map((x) => x.code);
const hours = (a, b) => Math.round((new Date(a).getTime() - new Date(b).getTime()) / 3600000);

// ═══════════════════════════════════════════════════════════════════════════

section("the acceptance criterion, end to end");

await test("a normal patch release goes live with no human", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0" }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root });
  assertEqual(r.decision.outcome, "publish",
    `${JSON.stringify(r.findings.filter((f) => f.level === "error" || f.level === "review"))} / ${JSON.stringify(r.decision.reasons)}`);
  assert(r.decision.publishes_now, "and it publishes on this run, not a later one");
  assertEqual(r.decision.publish_after, null, "nothing to wait for");
  assert(codes(r).includes("P_PUBLISHED"), JSON.stringify(codes(r)));

  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assert(fs.existsSync(path.join(out, "plugins", "dice-roller", "versions", "0.2.0.json")),
    "the listing the publish job commits is on disk");
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8"), "", "nothing to delete");
  assert(r.comment.includes("**Published.**"), "and the author is told, in the comment, in those words");
});

await test("a dom_access request does not", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "dom_access"] })] });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_NEW_HIGH_RISK"), JSON.stringify(codes(r)));
  assert(!r.decision.publishes_now, "nothing publishes");
  assertEqual(hours(r.decision.sla_deadline, NOW), REVIEW_SLA_HOURS, "and the author is given the deadline");

  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assert(!fs.existsSync(path.join(out, "plugins")), "no listing is produced for a held release");
  assert(r.comment.includes("R_NEW_HIGH_RISK"), "the comment names the reason");
  assert(r.comment.includes(POLICY_CODES.R_NEW_HIGH_RISK.remedy.slice(0, 40)),
    "…and says what to do about it");
});

section("the three events that block on a person, and nothing else");

await test("a first listing blocks, and says it is the only time", async () => {
  const r = await run({ root: registryTree([{ id: "something-else" }]) });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_FIRST_LISTING"), JSON.stringify(codes(r)));
});

await test("a repository change blocks", async () => {
  const r = await run({ root: registryTree([{ repo: "someone-else/dice-roller" }]) });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_IDENTITY_CHANGED"), JSON.stringify(codes(r)));
});

await test("a first listing that also wants dom_access says it once, not twice", async () => {
  const r = await run({
    root: registryTree([{ id: "something-else" }]),
    assets: [conforming({ capabilities: ["tools", "dom_access"] })],
  });
  assertEqual(r.decision.outcome, "review", "");
  assert(codes(r).includes("R_FIRST_LISTING"), JSON.stringify(codes(r)));
  assert(!codes(r).includes("R_NEW_HIGH_RISK"),
    "a human is already reading it; a second row saying so tells them nothing");
});

await test("a check the bot cannot rule on is held with the same SLA", async () => {
  // A name one edit away from a listed plugin: task 3.3 raises it as `review`,
  // and the policy adopts any such finding rather than inventing a fourth
  // blocking event of its own.
  const r = await run({
    root: registryTree([{ versions: [{ version: "0.1.0" }] }]),
    assets: [conforming({ id: "dice-rollers" })],
  });
  assertEqual(r.decision.outcome, "review", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("R_CHECK_HELD"), JSON.stringify(codes(r)));
});

await test("a failed check is a refusal, and the policy says it never got a say", async () => {
  const r = await run({
    root: registryTree([{ versions: [{ version: "0.1.0" }] }]),
    assets: [conforming({ license: "GPL-3.0-only" })],
  });
  assertEqual(r.decision.outcome, "refuse", JSON.stringify(r.decision.reasons));
  assertEqual(codes(r).join(","), "P_REFUSED", "one row, and it points at the checks above it");
});

section("the delay");

await test("a plugin already holding dom_access waits, even with nothing changed", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["dom_access", "tools"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "dom_access"] })] });
  assertEqual(r.decision.outcome, "delay", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("P_DELAY_HIGH_RISK"), JSON.stringify(codes(r)));
  assertEqual(hours(r.decision.publish_after, NOW), DELAY_HOURS, "24 h from now");
  assert(r.decision.notify_author, "and the author hears about it now, which is the point");
});

await test("a widening inside the non-high-risk set waits too, and publishes itself", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  assertEqual(r.decision.outcome, "delay", JSON.stringify(r.decision.reasons));
  assert(codes(r).includes("P_DELAY_WIDENED"), JSON.stringify(codes(r)));
  assert(r.decision.queue_entry.reason.includes("P_DELAY_WIDENED"), "the queue file records why it waited");
  assert(r.comment.includes("Publishing itself at"), "the comment gives the time, not a shrug");
});

await test("a narrowing is not a widening", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools", "tts"] }] }]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools"] })] });
  assertEqual(r.decision.outcome, "publish", JSON.stringify(r.decision.reasons));
});

await test("the queue entry the workflow commits lands under state/queue/", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  writeOutputs(out, { repo: REPO, tag: TAG, issue: 7 }, r);
  const file = path.join(out, queueFile("dice-roller", "0.2.0"));
  assert(fs.existsSync(file), `expected ${queueFile("dice-roller", "0.2.0")}`);
  const entry = JSON.parse(fs.readFileSync(file, "utf8"));
  assertEqual(entry.repo, REPO, "the repository it is waiting on");
  assertEqual(entry.submitter, SUBMITTER, "and whose ownership gets re-proved when it drains");
  assertEqual(entry.artifact_digests.length, 1, "and the exact bytes the clock is running on");
  assert(!fs.existsSync(path.join(out, "plugins")), "a delayed release publishes nothing yet");
});

await test("when the delay has elapsed the same release publishes, and stops waiting", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const asset = conforming({ capabilities: ["tools", "tts"] });

  // Round one: it queues. Round two: the queue entry is on disk and the clock
  // has run out. The whole ingest runs again — this is not a resume.
  const first = await run({ root, assets: [asset] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(first.decision.queue_entry, null, 2)}\n`);

  const later = new Date(NOW.getTime() + (DELAY_HOURS + 1) * 3600000);
  const out = tmp("astra-policy-out-");
  const second = await run({ root, assets: [asset], now: later });
  assertEqual(second.decision.outcome, "publish", JSON.stringify(second.decision.reasons));
  assert(codes(second).includes("P_DELAY_ELAPSED"), JSON.stringify(codes(second)));
  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, second);
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8").trim(),
    queueFile("dice-roller", "0.2.0"), "and the queue entry is deleted by the same commit");
});

await test("an asset swapped during the window restarts the clock", async () => {
  const root = registryTree([{ versions: [{ version: "0.1.0", capabilities: ["tools"] }] }]);
  const first = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  const qfile = path.join(root, queueFile("dice-roller", "0.2.0"));
  fs.mkdirSync(path.dirname(qfile), { recursive: true });
  fs.writeFileSync(qfile, `${JSON.stringify(first.decision.queue_entry, null, 2)}\n`);

  const later = new Date(NOW.getTime() + (DELAY_HOURS + 1) * 3600000);
  const swapped = {
    name: bundleName(),
    bytes: makeBundle({ capabilities: ["tools", "tts"], extraFiles: [{ name: "extra.txt", data: "surprise" }] }),
  };
  const second = await run({ root, assets: [swapped], now: later });
  assertEqual(second.decision.outcome, "delay", JSON.stringify(second.decision.reasons));
  assert(codes(second).includes("P_DELAY_BYTES_CHANGED"), JSON.stringify(codes(second)));
  assertEqual(hours(second.decision.publish_after, later), DELAY_HOURS,
    "a swap timed for the last minute of the window buys the attacker nothing");
});

await test("a release the checks have since started refusing stops waiting", async () => {
  // The drain re-runs everything, so a queued release whose repository changed
  // hands the decision to a human — and the queue entry is removed rather than
  // left to be retried every hour for ever.
  const root = registryTree([{ repo: "someone-else/dice-roller", versions: [{ version: "0.1.0" }] }]);
  const out = tmp("astra-policy-out-");
  const r = await run({ root });
  assertEqual(r.decision.outcome, "review", "");
  writeOutputs(out, { repo: REPO, tag: TAG, issue: null }, r);
  assertEqual(fs.readFileSync(path.join(out, "remove.txt"), "utf8").trim(),
    queueFile("dice-roller", "0.2.0"), "");
});

section("the author's track record");

await test(`${CLEAN_RELEASES_FOR_TRUSTED} clean releases buy a shorter delay`, () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([{ id: "other-thing", versions }]);
  const { plugins } = requireSources(root);
  const record = trackRecord(root, REPO, { plugins });
  assertEqual(record.tier, "established", JSON.stringify(record));
  assertEqual(record.delay_hours, TRUSTED_DELAY_HOURS, "");
});

await test("a staging listing is not a clean release", () => {
  const root = registryTree([{ id: "other-thing", versions: [{ version: "0.1.0", staging: true }] }]);
  const { plugins } = requireSources(root);
  assertEqual(trackRecord(root, REPO, { plugins }).clean_releases, 0,
    "nobody could verify its artifact, so it is not evidence of anything");
});

await test("a revocation resets the counter, a yank does not", () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED + 2 }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([{ id: "other-thing", versions }]);
  const { plugins } = requireSources(root);
  const revoked = trackRecord(root, REPO, {
    plugins,
    revocations: [{ plugin_id: "other-thing", version: "0.2.0" }],
  });
  assertEqual(revoked.tier, "new", JSON.stringify(revoked));
  assertEqual(revoked.delay_hours, DELAY_HOURS, "");
});

await test("the shorter delay actually reaches the decision", async () => {
  const versions = Array.from({ length: CLEAN_RELEASES_FOR_TRUSTED }, (_, i) => ({
    version: `0.${i + 1}.0`, staging: false,
  }));
  const root = registryTree([
    { versions: [{ version: "0.1.0", capabilities: ["tools"] }] },
    { id: "other-thing", repo: `${SUBMITTER}/other-thing`, versions },
  ]);
  const r = await run({ root, assets: [conforming({ capabilities: ["tools", "tts"] })] });
  assertEqual(r.decision.outcome, "delay", "");
  assertEqual(hours(r.decision.publish_after, NOW), TRUSTED_DELAY_HOURS, JSON.stringify(r.decision.track));
  assert(codes(r).includes("P_TRUSTED_AUTHOR"), JSON.stringify(codes(r)));
});

section("the decision function on its own");

await test("an unknown permission is reported and not blocked", () => {
  const d = decide({
    findings: [],
    derived: {
      plugin: { id: "x" },
      version: { version: "1.0.0", capabilities: ["tools"], permissions: { teleport: {} } },
    },
    existing: { versions: [{ doc: { version: "0.9.0", capabilities: ["tools"] } }] },
    repo: REPO,
    now: NOW,
  });
  assert(d.reasons.some((r) => r.code === "P_UNKNOWN_PERMISSION"), JSON.stringify(d.reasons));
  assertEqual(d.outcome, "delay", "it is still a widening, so it still waits");
});

await test("capabilities and permissions are one question", () => {
  assertEqual(
    requestedAuthority({ capabilities: ["tools"], permissions: { fire_trigger: {}, tools: {} } }).join(","),
    "fire_trigger,tools",
    "declared twice is asked for once",
  );
});

await test("a backported patch is measured against the newest listing, not the last file", () => {
  const existing = {
    versions: [
      { doc: { version: "0.9.0", capabilities: ["tools", "dom_access"] } },
      { doc: { version: "0.10.0", capabilities: ["tools", "dom_access"] } },
    ],
  };
  const d = decide({
    findings: [],
    derived: { plugin: { id: "x" }, version: { version: "0.10.1", capabilities: ["tools", "dom_access"] } },
    existing, repo: REPO, now: NOW,
  });
  assertEqual(d.outcome, "delay", "held dom_access all along; delayed, not reviewed");
  assert(!d.reasons.some((r) => r.code === "R_NEW_HIGH_RISK"), JSON.stringify(d.reasons));
});

await test("every high-risk name blocks on first request", () => {
  for (const name of HIGH_RISK) {
    const d = decide({
      findings: [],
      derived: { plugin: { id: "x" }, version: { version: "1.0.0", permissions: { [name]: {} } } },
      existing: { versions: [{ doc: { version: "0.9.0" } }] },
      repo: REPO, now: NOW,
    });
    assertEqual(d.outcome, "review", `${name} must ask a person`);
  }
});

section("the review SLA, made visible");

await test("a queue past the breach threshold says what to do about it", () => {
  const report = slaReport([
    { number: 1, title: "[listing] a/b", created_at: "2026-08-01T00:00:00Z" },
    { number: 2, title: "[listing] c/d", created_at: "2026-08-10T06:00:00Z" },
  ], NOW);
  assertEqual(report.open, 2, "");
  assertEqual(report.late, 1, "");
  assertEqual(report.breached, 1, "");
  assert(report.verdict.includes("not \"review harder\""), report.verdict);
});

await test("an empty queue is within SLA and says so quietly", () => {
  assertEqual(slaReport([], NOW).verdict, "within SLA", "");
});

// ═══════════════════════════════════════════════════════════════════════════

section("the ping (task 3.4, layer 1)");

await test("/release takes one argument on a listing issue and two on a new one", () => {
  assertEqual(parseReleasePing("/release v0.2.0").tag, "v0.2.0", "");
  assertEqual(parseReleasePing("/release v0.2.0").repo, null, "one argument names no repository");
  const two = parseReleasePing("/release you/dice-roller v0.2.0");
  assertEqual(two.repo, "you/dice-roller", "");
  assertEqual(two.tag, "v0.2.0", "");
});

await test("people paste the address bar, and that is the same repository", () => {
  const p = parseReleasePing("/release `https://github.com/you/dice-roller.git/` v0.2.0");
  assertEqual(p.repo, "you/dice-roller", "");
});

await test("a mention is not a command", () => {
  assert(parseReleasePing("please /release v0.2.0 for me") === null, "");
  assert(parseReleasePing("/releases v0.2.0") === null, "");
  assert(parseReleasePing("") === null, "");
});

await test("a ping cannot smuggle a shell argument or a second repository", () => {
  assert(parseReleasePing("/release you/dice-roller v0.2.0; rm -rf /") === null, "");
  assert(parseReleasePing("/release ../../etc/passwd v1") === null, "");
  assert(parseReleasePing("/release you/dice-roller ../../evil") === null, "a `..` tag is not a tag");
});

await test("an unlabelled ping may only name a repository that is already listed", () => {
  const sources = requireSources(registryTree([{ versions: [{ version: "0.1.0" }] }]));
  assertEqual(findListingByRepo(sources, REPO).id, "dice-roller", "");
  assertEqual(findListingByRepo(sources, "A-Stranger/Dice-Roller").id, "dice-roller",
    "GitHub is case-insensitive here and so is the lookup");
  assertEqual(findListingByRepo(sources, "someone/unlisted"), null,
    "so the worst a stranger can do is re-check a listing that is already pinned");
});

section("the backstop (task 3.4, layer 2)");

await test("a listing that released recently is not polled at all", () => {
  const sources = requireSources(registryTree([
    { id: "fresh", versions: [{ version: "1.0.0", published_at: "2026-08-09T00:00:00Z" }] },
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]));
  const plan = watchPlan(sources, { repos: {} }, NOW);
  assertEqual(plan.quiet.length, 1, JSON.stringify(plan.quiet));
  assertEqual(plan.poll.length, 1, JSON.stringify(plan.poll));
  assertEqual(plan.poll[0].id, "quiet", `only listings quiet for ${WATCH_AFTER_DAYS} days cost anything`);
});

await test("an unlisted plugin is not watched", () => {
  const sources = requireSources(registryTree([
    { id: "gone", unlisted: true, versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]));
  assertEqual(watchPlan(sources, { repos: {} }, NOW).poll.length, 0, "");
});

await test("the batch rotates oldest-checked first", () => {
  const sources = requireSources(registryTree(
    ["a", "b", "c"].map((id) => ({
      id, repo: `someone/${id}`, versions: [{ version: "1.0.0", published_at: "2026-01-01T00:00:00Z" }],
    })),
  ));
  const seen = { repos: {
    "someone/a": { last_checked: "2026-08-09T00:00:00Z" },
    "someone/b": { last_checked: "2026-06-01T00:00:00Z" },
  } };
  const plan = watchPlan(sources, seen, NOW, { batch: 2 });
  assertEqual(plan.poll.map((p) => p.id).join(","), "c,b", "never polled, then longest ago");
  assertEqual(plan.deferred.length, 1, "and the rest wait for the next run rather than being dropped");
});

await test("an unchanged repository costs one 304 and nothing else", async () => {
  let seenHeader = null;
  const res = await pollFeed("someone/quiet", 'W/"abc"', async (url, init) => {
    seenHeader = init.headers["If-None-Match"];
    return { status: 304, ok: false, headers: new Map(), text: async () => { throw new Error("a 304 has no body"); } };
  });
  assertEqual(seenHeader, 'W/"abc"', "the etag is fed back");
  assertEqual(res.changed, false, "");
  assertEqual(res.entries.length, 0, "");
});

const ATOM = `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <entry>
    <id>tag:github.com,2008:Repository/1/v0.3.0</id>
    <updated>2026-08-08T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/someone/quiet/releases/tag/v0.3.0"/>
    <title>v0.3.0</title>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/1/v0.2.0</id>
    <updated>2026-01-01T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/someone/quiet/releases/tag/v0.2.0"/>
    <title>v0.2.0</title>
  </entry>
  <entry>
    <updated>2026-08-09T10:00:00Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/attacker/elsewhere/releases/tag/v9.9.9"/>
    <title>not ours</title>
  </entry>
</feed>`;

await test("the feed parse takes four fields and refuses another repository's releases", () => {
  const entries = parseReleasesAtom(ATOM, "someone/quiet");
  assertEqual(entries.map((e) => e.tag).join(","), "v0.3.0,v0.2.0", "newest first, ours only");
  assertEqual(entries[0].updated, "2026-08-08T10:00:00Z", "");
});

await test("a release already listed, or already tried, is not re-ingested", () => {
  const entries = parseReleasesAtom(ATOM, "someone/quiet");
  assertEqual(newReleases({ listed_tag: "v0.2.0" }, entries, {}).map((e) => e.tag).join(","), "v0.3.0", "");
  assertEqual(newReleases({ listed_tag: "v0.2.0" }, entries, { checked_tags: ["v0.3.0"] }).length, 0,
    "a release this registry refused is not retried every hour for ever");
});

await test("the backstop finds a missed release and hands it to the pipeline", async () => {
  const root = registryTree([
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "0.2.0", tag: "v0.2.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]);
  const { dispatch, seen, log } = await runWatch({
    root,
    now: NOW,
    deps: {
      fetchImpl: async () => ({
        status: 200, ok: true,
        headers: new Map([["etag", 'W/"new"']]),
        text: async () => ATOM,
      }),
      fetchRelease: async (repo, tag) => ({ tag_name: tag, author: { login: "the-author" } }),
    },
  });
  assertEqual(dispatch.length, 1, JSON.stringify(log));
  assertEqual(dispatch[0].repo, "someone/quiet", "");
  assertEqual(dispatch[0].tag, "v0.3.0", "");
  assertEqual(dispatch[0].submitter, "the-author",
    "the ownership that gets proved is the release author's, never the pinger's");
  assertEqual(seen.repos["someone/quiet"].last_seen_tag, "v0.3.0", "and it is remembered");
});

await test("a repository that has gone away is recorded, not fatal", async () => {
  const root = registryTree([
    { id: "quiet", repo: "someone/quiet", versions: [{ version: "0.2.0", published_at: "2026-01-01T00:00:00Z" }] },
  ]);
  const { dispatch, seen } = await runWatch({
    root, now: NOW,
    deps: { fetchImpl: async () => ({ status: 404, ok: false, headers: new Map(), text: async () => "" }) },
  });
  assertEqual(dispatch.length, 0, "");
  assert(seen.repos["someone/quiet"].last_error.includes("404"), JSON.stringify(seen.repos));
});

section("the drain");

await test("only a ripe queue entry is dispatched, and the rest are reported", () => {
  const root = tmp("astra-policy-queue-");
  fs.mkdirSync(path.join(root, "state", "queue"), { recursive: true });
  const write = (id, version, publishAfter) =>
    fs.writeFileSync(path.join(root, queueFile(id, version)), `${JSON.stringify({
      id, version, repo: `someone/${id}`, tag: `v${version}`, submitter: "someone",
      queued_at: "2026-08-09T12:00:00Z", publish_after: publishAfter, reason: "P_DELAY_HIGH_RISK",
    })}\n`);
  write("ripe-one", "1.0.0", "2026-08-10T11:00:00Z");
  write("still-waiting", "2.0.0", "2026-08-11T11:00:00Z");

  assertEqual(readQueue(root).length, 2, "both are visible to a maintainer");
  const { dispatch, log } = runDrain({ root, now: NOW });
  assertEqual(dispatch.length, 1, JSON.stringify(dispatch));
  assertEqual(dispatch[0].repo, "someone/ripe-one", "");
  assertEqual(dispatch[0].submitter, "someone", "whose ownership is proved again on the way in");
  assert(log.some((l) => l.includes("wait") && l.includes("still-waiting")), log.join("\n"));
});

section("what the workflow asks before it spends anything");

/** Write two bodies to files, the way `.github/workflows/ingest.yml` does. */
function bodies({ issue = "", comment = "" }) {
  const dir = tmp("astra-policy-body-");
  fs.writeFileSync(path.join(dir, "issue.md"), issue);
  fs.writeFileSync(path.join(dir, "comment.md"), comment);
  return { issueBody: path.join(dir, "issue.md"), commentBody: path.join(dir, "comment.md") };
}

const FORM = [
  "### Source repository", "", REPO, "",
  "### Release tag carrying the .astraplugin assets", "", TAG, "",
  "### Confirmations", "",
  "- [X] I own or maintain this repository.",
].join("\n");

const releaseBy = (login) => async (repo, tag) => ({ tag_name: tag, author: { login } });

await test("a labelled listing issue is still the submission form's", async () => {
  const out = await triage({
    event: "issues", labels: "listing,needs-triage", root: registryTree([{}]),
    ...bodies({ issue: FORM }),
  }, releaseBy("a-stranger"));
  assertEqual(out.mode, "form", out.why);
});

await test("`/release v0.2.0` on a listing issue takes the repository from the issue", async () => {
  const out = await triage({
    event: "issue_comment", labels: "listing", root: registryTree([{}]),
    ...bodies({ issue: FORM, comment: "/release v0.3.0" }),
  }, releaseBy("the-author"));
  assertEqual(out.mode, "ping", out.why);
  assertEqual(out.repo, REPO, "named by the issue, not by whoever commented");
  assertEqual(out.tag, "v0.3.0", "");
  assertEqual(out.submitter, "the-author", "the release author, never the pinger");
});

await test("an unlabelled ping is honoured only for a listing that already exists", async () => {
  const root = registryTree([{}]);
  const listed = await triage({
    event: "issues", labels: "", root,
    ...bodies({ issue: `/release ${REPO} v0.3.0\n\nnew release!` }),
  }, releaseBy("the-author"));
  assertEqual(listed.mode, "ping", listed.why);

  const stranger = await triage({
    event: "issues", labels: "", root,
    ...bodies({ issue: "/release somebody/brand-new v1.0.0" }),
  }, releaseBy("the-author"));
  assertEqual(stranger.mode, "none", "a first listing is not reachable this way");
  assert(stranger.why.includes("template"), stranger.why);
});

await test("/recheck still means recheck, and prose still means nothing", async () => {
  const root = registryTree([{}]);
  assertEqual((await triage({
    event: "issue_comment", labels: "listing", root, ...bodies({ issue: FORM, comment: "/recheck" }),
  }, releaseBy("x"))).mode, "form", "");
  assertEqual((await triage({
    event: "issue_comment", labels: "listing", root,
    ...bodies({ issue: FORM, comment: "any news on this? maybe /release it" }),
  }, releaseBy("x"))).mode, "none", "");
});

await test("a ping for a tag that has no release is dropped, not ingested", async () => {
  const out = await triage({
    event: "issues", labels: "", root: registryTree([{}]),
    ...bodies({ issue: `/release ${REPO} v9.9.9` }),
  }, async () => { throw new Error("no release tagged v9.9.9 (404)"); });
  assertEqual(out.mode, "none", out.why);
  assert(out.why.includes("404"), out.why);
});

section("the document and the code say the same thing");

await test("docs/POLICY.md quotes the numbers the code enforces", () => {
  const doc = fs.readFileSync(path.join(REPO_ROOT, "docs", "POLICY.md"), "utf8");
  for (const needle of [
    `${DELAY_HOURS} h`,
    `${TRUSTED_DELAY_HOURS} h`,
    `${REVIEW_SLA_HOURS} h`,
    `${CLEAN_RELEASES_FOR_TRUSTED} clean`,
    `${WATCH_AFTER_DAYS} days`,
  ]) {
    assert(doc.includes(needle), `docs/POLICY.md never says "${needle}", so the published policy has drifted from the code`);
  }
  for (const name of HIGH_RISK) {
    assert(doc.includes(`\`${name}\``), `docs/POLICY.md does not list ${name} as high-risk`);
  }
  for (const code of Object.keys(POLICY_CODES)) {
    assert(doc.includes(code), `docs/POLICY.md does not explain ${code}, which an author can be shown`);
  }
});

await test("POLICY.md points at the detail rather than restating it", () => {
  const doc = fs.readFileSync(path.join(REPO_ROOT, "POLICY.md"), "utf8");
  assert(doc.includes("docs/POLICY.md"), "the listing policy has to link the publication policy");
  assert(doc.includes(`${REVIEW_SLA_HOURS} hours`) || doc.includes(`${REVIEW_SLA_HOURS} h`),
    "and §8 has to carry the number now that there is one");
});

// ── result ──────────────────────────────────────────────────────────────────

console.log();
if (failures.length) {
  console.log(`FAIL  ${passed} passed, ${failures.length} failed`);
  process.exit(1);
}
console.log(`PASS  ${passed} passed, 0 failed`);
