// The root keys the bot compiles in, and the one thing that can go wrong
// with compiling them (registry plan B-T1.5, BOT-7).
//
// Two properties, and they pull in opposite directions, which is why both are
// here:
//
//   * the compiled set is the ONLY set — a trust.json signed by any other key
//     is refused, and no file, tree, argument or flag changes that;
//   * the compiled set is not a second opinion — it is the same set
//     `registry/v1/root.json` publishes, and when the two stop agreeing that
//     is an alarm rather than a silently authoritative constant.
//
// The first without the second is a bot that believes a key nobody published;
// the second without the first is what this task replaced.

import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { NO_REPORT_CODE, VERDICT_CHECK, checkRoots, relayVerdict } from "../check-roots.mjs";
import { ingest, parseArgs as ingestArgs } from "../ingest.mjs";
import { parseArgs as decideArgs } from "../decide.mjs";
import { loadRootKeys, loadWorkflowAllowlist } from "../lib/attestation.mjs";
import {
  COMPILED_ROOTS,
  ROOT_CODES,
  ROOT_SOURCE_COMMIT,
  compiledRootKeys,
  compiledSetProblems,
  fingerprintOf,
  rootFileProblems,
} from "../lib/roots.mjs";
import { verdictProblems } from "../lib/alert-verdict.mjs";

const REPO_ROOT = path.resolve(import.meta.dirname, "..", "..");
const ROOT_JSON = path.join(REPO_ROOT, "registry", "v1", "root.json");
const TESTKEYS = path.join(REPO_ROOT, "tools", "testkeys");

const tmp = (stem) => fs.mkdtempSync(path.join(os.tmpdir(), stem));
const published = () => JSON.parse(fs.readFileSync(ROOT_JSON, "utf8"));

/** The clearly-labelled TEST roots, as a root.json-shaped document. */
function testRootsDoc() {
  const keys = ["root-a", "root-b"].map((n) =>
    JSON.parse(fs.readFileSync(path.join(TESTKEYS, `TEST-ONLY-DO-NOT-TRUST-${n}.pub.json`), "utf8")));
  return {
    $banner: "TEST ROOTS — generated by bot/tests/roots.test.mjs, never committed, never trusted by a daemon.",
    schema: "astra.registry.root/1",
    status: "provisioned",
    roots: keys.map((k) => ({
      key_id: k.key_id,
      role: k.role,
      algorithm: "ed25519",
      public_key: k.public_key,
      fingerprint_sha256: fingerprintOf(k.public_key),
    })),
  };
}

// ── the compiled table, on its own ──────────────────────────────────────────

test("the compiled table does not contradict itself", () => {
  // Asked before anything is compared with anything: two corrupted halves can
  // agree, and a fingerprint that matches nothing is a fingerprint nobody can
  // use to tell which half was edited.
  assert.equal(compiledSetProblems().join("\n"), "");
  assert.ok(COMPILED_ROOTS.length >= 1, "no root is compiled in, so this bot would verify no trust.json at all");
  assert.ok(COMPILED_ROOTS.some((r) => r.role === "active"), "no compiled root is the one that signs today");
});

test("a compiled key whose fingerprint was not recomputed is caught by this file alone", () => {
  // The mutation a hand edit makes: one base64 character changed, everything
  // else left as it was. Nothing outside this module has to be consulted.
  const [first, ...rest] = COMPILED_ROOTS.map((r) => ({ ...r }));
  const bytes = Buffer.from(first.public_key, "base64");
  bytes[0] ^= 0x01;
  first.public_key = bytes.toString("base64");
  const problems = compiledSetProblems([first, ...rest]);
  assert.match(problems.join("\n"), /the compiled public key fingerprints as/);
});

test("compiledRootKeys() hands a verifier the keys and calls them compiled", () => {
  const set = compiledRootKeys();
  assert.equal(set.status, "compiled", "`provisioned` would send a reader to look for the file");
  assert.equal(set.keys.length, COMPILED_ROOTS.length);
  assert.deepEqual(set.keys.map((k) => k.key_id), COMPILED_ROOTS.map((r) => r.key_id));
});

// ── the compiled table against the published file ───────────────────────────

test("the published root.json is the compiled set, today", () => {
  // The live coupling. If this goes red, one of the two moved: either a
  // rotation is under way and `bot/lib/roots.mjs` is the half that has to
  // move next, or somebody edited the published file and the bot's anchor did
  // not follow.
  const out = checkRoots();
  assert.equal(out.problems.join("\n"), "");
  assert.equal(out.expected.join("\n"), "");
  assert.equal(out.verdict.status, "green");
  assert.equal(out.verdict.check, VERDICT_CHECK);
  assert.equal(verdictProblems(out.verdict).join("\n"), "", "the green verdict is not one the channel would carry");
});

test("the source commit named in bot/lib/roots.mjs is a 40-hex commit", () => {
  assert.match(ROOT_SOURCE_COMMIT, /^[0-9a-f]{40}$/);
});

test("a published root.json with one altered key is an alarm", () => {
  const doc = published();
  const bytes = Buffer.from(doc.roots[0].public_key, "base64");
  bytes[0] ^= 0x01;
  doc.roots[0].public_key = bytes.toString("base64");
  const out = rootFileProblems(doc);
  assert.match(out.problems.join("\n"), /publishes a DIFFERENT public key under this id/);
  assert.equal(out.expected.join("\n"), "", "an edited key is not a rotation and must not be excused as one");

  const file = path.join(tmp("astra-roots-altered-"), "root.json");
  fs.writeFileSync(file, JSON.stringify(doc, null, 2));
  const verdict = checkRoots({ rootsFile: file });
  assert.equal(verdict.ok, false);
  assert.deepEqual(verdict.verdict.codes, [ROOT_CODES.DIVERGED]);
  assert.equal(verdict.verdict.status, "red");
  assert.equal(verdictProblems(verdict.verdict).join("\n"), "", "the alarm this raises is one the channel refuses");
});

test("a published root.json carrying a key the bot does not hold is an alarm", () => {
  const doc = published();
  const stranger = JSON.parse(fs.readFileSync(path.join(TESTKEYS, "TEST-ONLY-DO-NOT-TRUST-stranger.pub.json"), "utf8"));
  doc.roots.push({
    key_id: "astra-root-2027a",
    role: "active",
    algorithm: "ed25519",
    public_key: stranger.public_key,
    fingerprint_sha256: fingerprintOf(stranger.public_key),
  });
  const out = rootFileProblems(doc);
  assert.match(out.problems.join("\n"), /publishes a root key this bot does not hold/);
});

test("SERVE-92 step 1 is reported and does not page anybody", () => {
  // The compiled set holds the incoming root and the published file has not
  // caught up. That is the middle of a rotation done correctly, and a check
  // that alarmed on it would be a check the next rotation works around.
  const doc = published();
  const dropped = doc.roots.pop();
  const out = rootFileProblems(doc);
  assert.equal(out.problems.join("\n"), "", "the correct middle of a rotation raised an alarm");
  assert.match(out.expected.join("\n"), new RegExp(`${dropped.key_id} is compiled into the bot`));
});

test("a root.json that cannot be read is still an alarm, and says the bot still has its roots", () => {
  const file = path.join(tmp("astra-roots-gone-"), "root.json");
  const out = checkRoots({ rootsFile: file });
  assert.equal(out.ok, false);
  assert.deepEqual(out.verdict.codes, [ROOT_CODES.UNREADABLE]);
  assert.match(out.problems.join("\n"), /The bot still has its roots — they are compiled in/);
});

// ── the compiled set is the only set ────────────────────────────────────────

test("a trust.json signed by a testkeys root is refused against the compiled set", () => {
  const verdict = loadWorkflowAllowlist({
    trustFile: path.join(TESTKEYS, "fixtures", "trust-active-signed.json"),
  });
  assert.equal(verdict.ok, false, "a fixture signed by a TEST key delivered a production allowlist");
  assert.equal(verdict.code, "E_TRUST_UNPROVISIONED");
});

test("editing root.json to include the signing key changes nothing", async () => {
  // The whole of B-T1.5, run end to end as the attack it is: a commit that
  // adds a key to `registry/v1/root.json` and lands a `trust.json` signed by
  // it. Before the keys were compiled in, this tree would have yielded a
  // verified allowlist and the ingest would have gone on to check an
  // attestation against a reusable workflow of the attacker's choosing.
  //
  // The tree is complete — root.json AND trust.json, both consistent with
  // each other — so nothing here fails for a boring reason like a missing
  // file. `deps` is empty: this is the production path, and it must refuse
  // before it fetches anything, which is also why no network stub is needed.
  const dir = tmp("astra-roots-attack-");
  fs.mkdirSync(path.join(dir, "registry", "v1"), { recursive: true });
  fs.writeFileSync(path.join(dir, "registry", "v1", "root.json"), JSON.stringify(testRootsDoc(), null, 2));
  fs.copyFileSync(
    path.join(TESTKEYS, "fixtures", "trust-active-signed.json"),
    path.join(dir, "registry", "v1", "trust.json"),
  );

  // Proof the tree is not broken: the same two documents DO verify against
  // each other when the roots are the ones handed in. Without this the test
  // below would pass over a typo.
  const asItsOwnAnchor = loadWorkflowAllowlist({
    trustFile: path.join(dir, "registry", "v1", "trust.json"),
    roots: loadRootKeys(path.join(dir, "registry", "v1", "root.json")),
  });
  assert.equal(asItsOwnAnchor.ok, true, asItsOwnAnchor.message ?? "the attacker's own tree does not verify");

  const result = await ingest({ repo: "a-stranger/dice-roller", tag: "v0.2.0", submitter: "a-stranger", root: dir }, {});
  const codes = result.findings.filter((f) => f.level === "error").map((f) => f.code);
  assert.deepEqual(codes, ["E_TRUST_UNPROVISIONED"]);
  assert.equal(result.findings.length, 1, "it stops at the anchor rather than spending a stranger's bandwidth");
});

test("no command line can name a roots file", () => {
  // Asked of the parsers rather than of the files' text: a grep for `--roots`
  // passes the day the string moves into a variable.
  for (const [name, parse] of [["bot/ingest.mjs", ingestArgs], ["bot/decide.mjs", decideArgs]]) {
    assert.throws(
      () => parse(["--repo", "a/b", "--tag", "v0.1.0", "--roots", "/tmp/anything.json"]),
      /unknown argument: --roots/,
      `${name} still takes a roots file on the command line, which is the anchor as an argument`,
    );
    // And the flags that are meant to be there still are, so this test cannot
    // pass by the parser having stopped parsing.
    assert.equal(parse(["--repo", "a/b", "--tag", "v0.1.0", "--trust", "/tmp/t.json"]).trustFile, "/tmp/t.json");
  }
});

test("ingest asks for no roots file at all", () => {
  const src = fs.readFileSync(path.join(REPO_ROOT, "bot", "ingest.mjs"), "utf8");
  const call = /loadWorkflowAllowlist\(\{[\s\S]*?\}\);/.exec(src)?.[0] ?? "";
  assert.ok(call, "bot/ingest.mjs no longer calls loadWorkflowAllowlist, so this file is watching nothing");
  assert.doesNotMatch(call, /rootsFile/, "the production call names a roots file again");
  assert.match(call, /roots: deps\.rootKeys/, "the only way a test's roots get in is the deps seam");
});

// ── what the alert job sends ────────────────────────────────────────────────

test("a relayed verdict passes through, and an absent one becomes the alarm", () => {
  const good = checkRoots().verdict;
  assert.deepEqual(relayVerdict(JSON.stringify(good)), good);

  // Each of these is the `roots` job having died before it could report, and
  // each has to be a red alarm rather than a quiet green or a refused send.
  for (const relayed of [undefined, "", "   ", "not json", '{"schema":"wrong"}', "[]", '{"status":"red"}']) {
    const out = relayVerdict(relayed);
    assert.equal(out.status, "red", `a relayed ${JSON.stringify(relayed)} did not become an alarm`);
    assert.deepEqual(out.codes, [NO_REPORT_CODE]);
    assert.equal(verdictProblems(out).join("\n"), "", "the fallback alarm is one the channel refuses to carry");
  }
});

test("the verdict names a subject and not a receiver check", async () => {
  // `ingest.yml`'s alert job posts no BOT-85 heartbeat — BOT-51's schedule is
  // outside BOT-85's list because the plugins service's BOT-47 watches it — so
  // there is no receiver check behind this name, and creating one would make a
  // check nothing posts to.
  const { CHECKS } = await import("../lib/alert-checks.mjs");
  assert.ok(
    !CHECKS.some((c) => c.name === VERDICT_CHECK),
    `bot/lib/alert-checks.mjs now lists a receiver check called ${VERDICT_CHECK}. Either ingest.yml has started ` +
    "posting a heartbeat — in which case its alert job must name the check instead of a reason — or a check was " +
    "created that nothing posts to, which pages on silence for ever.",
  );
});

test("the fingerprint is sha256 over the raw key, as the ceremony computes it", () => {
  // tools/keygen-root.sh: `openssl pkey -pubout -outform DER | tail -c 32 | dgst -sha256`.
  for (const r of COMPILED_ROOTS) {
    const raw = Buffer.from(r.public_key, "base64");
    assert.equal(raw.length, 32);
    assert.equal(crypto.createHash("sha256").update(raw).digest("hex"), r.fingerprint_sha256);
  }
});
